### ISSUE TITLE
Array: Array sorting according another array.

### ISSUE THREAD

**Issue by Diksha-11** [Algo-Phantoms/Algo-Tree#1000]
Take an array as input then Sort the array according to the order of another array.
e.g. if array_1 is  3 8 9 9 8 3 7 & array_2 is  3 8 9 7

Then according array_2 , array_1 will be sorted as 3 3 8 8 9 9 7

I request maintainers  @plazzy99 @rudrakshi99 @nakul-19 @raksha009 @anjul2000 to allow me to this add this imp question to Algo Tree CodeC++

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue in "Java" as a GSSoC 2021 participant
kindly assign me the issue

**Comment by Diksha-11** [comment]
Respected Maintainer,
Please assign this issue to me.

**Comment by shreyanspoddar** [comment]
Not a valid issue, must comply with some sorting algorithm.
