### ISSUE TITLE
XOR of Sum of All Pairs in an Array | Bit Manipulation

### ISSUE THREAD

**Issue by HitainKakkar** [Algo-Phantoms/Algo-Tree#1005]
Greetings sir/Mam,
I would like to contribute the code for this issue in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by Jagruthi13** [comment]
Hey @tarun26091999 @rudrakshi99
I would like to do it in python.
could you please assign me this issue.

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 @tarun26091999  please assign me this issue

**Comment by shubhidua** [comment]
Hello, I would like to contribute to the above in java. Kindly assign me this issue.
