### ISSUE TITLE
Longest common substring

### ISSUE THREAD

**Issue by lucifer2502** [Algo-Phantoms/Algo-Tree#1006]
I would like to add this problem to the Dynamic programming(DP) section.
I will implement the code in C++ with proper comments , time complexity, space complexity and test cases.

**Comment by Jagruthi13** [comment]
Hey @tarun26091999 @rudrakshi99
I would like to do it in python.
could you please assign me this issue.

**Comment by simarjeet30** [comment]
I will implement the code in C++ /C/python with proper comments , time complexity, space complexity and test cases.

**Comment by ANSHIKA1806** [comment]
I'm a GSSOC'21 participant and I would like to work on this issue in C++.
I will write clean code and use proper comments.
Thank you.

**Comment by madhvi02** [comment]
@tarun26091999 
Please Assign this to me.I would like to code this in C++. I m a GSSOC'21 Partcipant .I will assure you that I will provide a commented code with efficient time complexity.
Regards 
Madhvi .

**Comment by tarun26091999** [comment]
present at #425
