### ISSUE TITLE
Subset Sum - Wheather subset of given sum is present in an array or not.

### ISSUE THREAD

**Issue by lucifer2502** [Algo-Phantoms/Algo-Tree#1007]
I would like to add this problem Dynamic Programming Section(DP).
I will implement the code in C++ with proper comments, time complexity, space complexity and test cases.

**Comment by Jagruthi13** [comment]
Hey @tarun26091999 @rudrakshi99 
I would like to do it in python.
could you please assign me this issue.

**Comment by HanyaAdel** [comment]
I'm a GSSOC'21 participant and I would like to work on this issue in Java 
I will write clean code and use proper comments.
Thank you,

**Comment by tarun26091999** [comment]
present at #148
