### ISSUE TITLE
Standard Template Library[GSSOC'21]

### ISSUE THREAD

**Issue by anumshka** [Algo-Phantoms/Algo-Tree#1009]
Hello,
Standard Template Library is a soul of C++ language.
I have a code that provides basics of vectors, maps and sets in C++.It would be a perfect guide for beginners in competitive programming.
Please assign this to me.
Thankyou.

**Comment by tanyalava** [comment]
Although STL is a vast topic, I will try to cover it in such a way that all of its sub topics gets covered with clean code and theory in C++ language.

**Comment by Upasana1216** [comment]
Hello, I'm a C++ coder and I have a vast knowledge of STL. I'll provide a great guide for STL. Please assign this to me.

**Comment by tarun26091999** [comment]
multiple topics cannot be covered in single issue.
