### ISSUE TITLE
C : Kadanes's Algorithm

### ISSUE THREAD

**Issue by Soham-Official** [Algo-Phantoms/Algo-Tree#1023]
Hey, I want to add the code of Kadane's Algorithm( C ).
please assign it to me.
This is regarding to GSSOC'21

**Comment by mandepsingh** [comment]
Hello, I am a participant of GSSoC'21. I can contribute to this issue.
Please assign me this task
Thank you!

**Comment by hw0105** [comment]
Hey, i am a participant of GSSOC'21.I would like to contribute to this issue.(C++).Please assin me this task

**Comment by tarun26091999** [comment]
issue present at #178 and C is not accepted
