### ISSUE TITLE
Searching in Python (GSSoC'21)

### ISSUE THREAD

**Issue by sayantani11** [Algo-Phantoms/Algo-Tree#1027]
Will implement Binary Search and Linear Search using Python?
Please assign this issue to me

**Comment by ANSHIKA1806** [comment]
please assign this to me.
I'm 3 star coder at HackerRank in python

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. Thanks!

**Comment by sayantani11** [comment]
@plazzy99 please assign this to me

**Comment by sayantani11** [comment]
@raksha009
