### ISSUE TITLE
Sorting in Python (GSSoC'21)

### ISSUE THREAD

**Issue by sayantani11** [Algo-Phantoms/Algo-Tree#1028]
Implement various kind of sort:
bubble sort
insertion sort
merge sort
wave sort and etc.
Please assign me this issue to me.

**Comment by Aj7t** [comment]
hi, I am a Gssoc'21 participant I want to work on "sorting" 
I am comfortable in both python and C++.
please assign me this work.

**Comment by ritikasharma99** [comment]
Hi I am GSSOC'21 participant. I would like to implement various sorting techniques in Java.

**Comment by batul02** [comment]
Hi, I a GSSOC'21 participant. I would like to work on this issue. I am comfortable with python and have a decent knowledge of sorting algorithms. Please, assign me this issue.

**Comment by ANAMIKA1410** [comment]
hii,
I m Anamika jain , a GSSoC participant 
please assign this to me :)

**Comment by ANAMIKA1410** [comment]
def bubbleSort(arr): 
    n = len(arr) 
  
    # Traverse through all array elements 
    for i in range(n-1): 
    # range(n) also work but outer loop will repeat one time more than needed. 
  
        # Last i elements are already in place 
        for j in range(0, n-i-1): 
  
            # traverse the array from 0 to n-i-1 
            # Swap if the element found is greater 
            # than the next element 
            if arr[j] > arr[j+1] : 
                arr[j], arr[j+1] = arr[j+1], arr[j]

**Comment by ANAMIKA1410** [comment]
# Python program for implementation of Insertion Sort 
# Function to do insertion sort
 def insertionSort(arr):      
           # Traverse through 1 to len(arr)     
           for i in range(1, len(arr)):           
                   key = arr[i]         
                   # Move elements of arr[0..i-1], that are        
                   # greater than key, to one position ahead 
                   # of their current position
                   j = i-1 
                   while j >=0 and key < arr[j] :
                           arr[j+1] = arr[j]  
                           j -= 1    
                   arr[j+1] = key
--

**Comment by ANAMIKA1410** [comment]
def insertionSort(arr): 
  
    # Traverse through 1 to len(arr) 
    for i in range(1, len(arr)): 
  
        key = arr[i] 
  
        # Move elements of arr[0..i-1], that are 
        # greater than key, to one position ahead 
        # of their current position 
        j = i-1
        while j >=0 and key < arr[j] : 
                arr[j+1] = arr[j] 
                j -= 1
        arr[j+1] = key

**Comment by raksha009** [comment]
Issue for all sorting algorithms present at #124
