### ISSUE TITLE
LinkList Deletion 

### ISSUE THREAD

**Issue by avijit1999** [Algo-Phantoms/Algo-Tree#103]
Delete node(s) in  a LinkList having a specific value

**Comment by avijit1999** [comment]
@rudrakshi99 please assign me

**Comment by Manzee1609** [comment]
I would like to work on this issue, I have implemented same thing in my college assignment.

**Comment by harshbhalala-04** [comment]
I would like to work on this issue using c++, I am a GSSOC'21 participant. Please assign me this issue.

**Comment by nikitajuneja1** [comment]
Hi, I have implemented all types of operations on the Linked list. Please assign this issue to me. I am a GSSOC'21 participant.

**Comment by avijit1999** [comment]
I wanted to do it in java

**Comment by khushi123456789** [comment]
I am  GSSOC'2021 participant. I am good at C++,C.Please assign this issue to me.
 Thankyou!

**Comment by AasthaGoyalgit** [comment]
Hey!!

I am interested in this issue in java problems as a GSSOC'21 participant .
I'll be glad to work on this issue.

Thanks!!

**Comment by tarun26091999** [comment]
duplicate issue.
