### ISSUE TITLE
Find Kth Element in Two Sorted Arrays [GSSOC'21]

### ISSUE THREAD

**Issue by SalmaZakaria** [Algo-Phantoms/Algo-Tree#1034]
Find Kth Element is a Divide and Conquer Problem with O(log N) complexity in C++
Please Assign it to me
Thank You Very Much

**Comment by yogitasaini** [comment]
please assign this task to me in java....under GSSOC 21

**Comment by Upasana1216** [comment]
Please assign this task to me. I can solve this problem using c++.

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. Thanks!
