### ISSUE TITLE
JAVA CURRENCY CONVERTOR

### ISSUE THREAD

**Issue by ANSHIKA1806** [Algo-Phantoms/Algo-Tree#1048]
I WANT TO ADD A CURRENCY CONVERTOR.

[java currency formatter.txt](https://github.com/Algo-Phantoms/Algo-Tree/files/6142214/java.currency.formatter.txt)
Sample Input

12324.134
Sample Output

US: $12,324.13
India: Rs.12,324.13
China: ￥12,324.13
France: 12 324,13 €

**Comment by shreyanspoddar** [comment]
The Issue is not a valid issue

**Comment by ANSHIKA1806** [comment]
> The Issue is not a valid issue

WHY?

**Comment by shreyanspoddar** [comment]
> > The Issue is not a valid issue
> 
> WHY?

It's not related to any algorithm, we are looking for specific algorithm based issues. See the other issues you'll get an idea of it.
