### ISSUE TITLE
binary search implementation

### ISSUE THREAD

**Issue by Deadbullfrog05** [Algo-Phantoms/Algo-Tree#106]
i wish to add a full documentary on binary search.

**Comment by yashikajotwani12** [comment]
@rudrakshi99 Please assign me this , I would write the most easy and understandable theory on binary search and would also code the implementation part for the same in c++.

**Comment by Vansh-Gupta4** [comment]
I am GSSoC participant ...would love to contribute in this..
I would add all theory and implementation of BST ..as i have thorough knowledge of it..as i have studied it many times through different courses...

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by tarun26091999** [comment]
@pallavidhere23 do it in python
@Deadbullfrog05 do it in java
@yashikajotwani12 do it in cpp

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. I will be using Java. Thanks!

**Comment by einhawking** [comment]
I am a participant of GSSOC'21
I would like to contribute in this

**Comment by einhawking** [comment]
I am a participant of GSSOC'21
I would like to contribute in this

**Comment by eunoia7** [comment]
@tarun26091999 @plazzy99 As there in no implementation in c++ yet and as #1509 is not merged since a long time, can I take up the task ?
