### ISSUE TITLE
All possible Subsets

### ISSUE THREAD

**Issue by krishnmohan19** [Algo-Phantoms/Algo-Tree#1062]
@anubhavitis @dheerajkotwani @tarun26091999 @avijit1999 @todi-2000
Hey, I want to add Subsets problem ,which find all possible subset from given array with unique element in the Algo-Tree I will start working on it as soon as I get assigned!! I am a part of GSSoC'21, so I would like to implement this in the java Language.

Kindly assign this issue to me!

**Comment by SwarnimaShishodia** [comment]
Hey pls assign this issue to me. I can solve this using C++. @anubhavitis  @dheerajkotwani

**Comment by simarjeet30** [comment]
Hey pls assign this issue to me. I can solve this using python/C/C++.
I have good knowledge of data structure and algorithms
 @anubhavitis @dheerajkotwani

**Comment by tarun26091999** [comment]
issue present at #747 and #736
