### ISSUE TITLE
Rat In Maze - A Backtracking problem

### ISSUE THREAD

**Issue by kratimitra** [Algo-Phantoms/Algo-Tree#1070]
Hey,
I am Krati Mitra (Discord username Krati(P)#8709), a GSSOC'21 participant.
I want to add the code for the issue "Rat In Maze".

Task:
We are given a maze of size N x N. The top-left cell is the source and  bottom right cell is the destination for the rat. Some blocks of the binary matrix are valid to move and some blocks are blocked. If one rat has to move from start cell , we have to find is there any path that can lead the mouse to the destination.

Input :Binary matrix.
In the matrix, the value 1 indicates the free area and 0 indicates blocked area.
Output :Binary matrix considering 1 from the source block to the destination block is the solution path.

For example,
Example #1:
Input: 
{1, 0, 0, 0}
{1, 1, 0, 1}
{0, 1, 0, 0}
{1, 1, 1, 1}
Output: 
{1, 0, 0, 0}
{1, 1, 0, 0}
{0, 1, 0, 0}
{0, 1, 1, 1}
Explanation: Following the 1 from source to destination provides us a solution 

I can contribute to solve this issue using C++.
This problem can be solved using
BackTracking with time complexity of O(2^(n^2)). 
Space Complexity: O(n^2). 

I'll try to inculcate this approach in my code.
Please assign me this task.

Thank You

**Comment by Manya1609** [comment]
Hey!..I'm a GSSOC'21 Participant and would like to work on this issue. I would like to explain the concept and the code in C++. 
Can anyone please assign me this issue??

**Comment by kratimitra** [comment]
I have raised this issue, I'll be providing the code in C++ .
@plazzy99 @rudrakshi99 @aaadddiii @anubhavitis @dheerajkotwani @tarun26091999 could you please assign this issue to me.

**Comment by tarun26091999** [comment]
we do not accept the problems from the CP platforms. We only deal in standard algorithms and data structures.
