### ISSUE TITLE
2D Array (Spiral Print and Wave Print) | C++

### ISSUE THREAD

**Issue by yashkumar7889** [Algo-Phantoms/Algo-Tree#1075]
Hello, I'm a GSSoC'21 participant. I would like to implement Spiral  Print and Wave Print with proper function description in C++. Kindly assign me this task. Thank You.

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 @tarun26091999  please assign me this issue

**Comment by tarun26091999** [comment]
cannot solve two ques in same issue.
