### ISSUE TITLE
Sum of all  elements of array

### ISSUE THREAD

**Issue by kshithih** [Algo-Phantoms/Algo-Tree#1078]
**Explanation**:

Given an array of size N, print sum of all elements in array i.e. elements from 1to N .
where first input is T ,number of testcases ,N is size of array, a[] are the elements of array.

**Example**

T=2
N=6
23 12 124 54 21 6
N=5
12 12 12 12 12 
sum=240
sum=60

Hello @rudrakshi99 I want to add this question to "Algo-Tree/Code/C++/"

**Comment by Avnish5** [comment]
Kindly assign this issue to me under GSSOC 2021.
I can write this code in c++,java or c.

**Comment by niyatitotala** [comment]
Hello, Can I work on this? @tarun26091999

**Comment by Athira1601** [comment]
i would like to contribute to this issue. i am gssoc participant. kindly assign me this issue.

**Comment by simarjeet30** [comment]
Hi I am participating in GSSOC'21 .
I would like to contribute to this project.
Explanation:

Given an array of size N, print sum of all elements in array i.e. elements from 1to N .
where first input is T ,number of testcases ,N is size of array, a[] are the elements of array.

Example

T=2
N=6
23 12 124 54 21 6
N=5
12 12 12 12 12
sum=240
sum=60
the code is ready with proper comments .
Kindly assign this issue to me!

**Comment by drishika2002** [comment]
Hello, I would like to code this question in C language as a GSSOC'21 participant.
Kindly assign this issue to me.

**Comment by PrerakMathur20** [comment]
Hi, @anubhavitis @dheerajkotwani @diyajaiswal11 @geekquad @nakul-19 @plazzy99 @rudrakshi99 @tarun26091999 @todi-2000 @Simar05519 
I am a GSSoC'21 Participant,
Its my request that you please assign this issue to me.
I ensure you efficient and neat code in C++.
