### ISSUE TITLE
merging two sorted arrays

### ISSUE THREAD

**Issue by ShrutiOmer** [Algo-Phantoms/Algo-Tree#1088]
I want to add a code in array section for merging the two sorted arrays using O(1) space in C++

I am a Gssoc participant, @tarun26091999  please assign this issue to me

**Comment by Athira1601** [comment]
i would like to contribute to  this  project, i am a gssoc participant.kindly assign the issue to me.

**Comment by PrerakMathur20** [comment]
Hi, @anubhavitis @dheerajkotwani @diyajaiswal11 @geekquad @nakul-19 @plazzy99 @rudrakshi99 @tarun26091999 @todi-2000 @Simar05519 
I am a GSSoC'21 Participant,
Its my request that you please assign this issue to me.
I ensure you efficient and neat code in C++.

**Comment by tarun26091999** [comment]
> i would like to contribute to this project, i am a gssoc participant.kindly assign the issue to me.

specify the language.

**Comment by ShrutiOmer** [comment]
Thanku sir assigning this issue I will implement in C++

**Comment by sandipswain** [comment]
Hey @tarun26091999 , I am a GSSo'C participant and I would like to take up this issue and solve it using python.Please assign me.

**Comment by Manya1609** [comment]
Hey!..I'm a GSSOC'21 Participant and would like to work on this issue. I would like to explain the concept and the code in C++. 
Can anyone please assign me this issue??

**Comment by pragati-kumar** [comment]
Hello @Simar05519 @anubhavitis @tarun26091999 @dheerajkotwani @diyajaiswal11 @geekquad @nakul-19 @plazzy99 @rudrakshi99  @todi-2000!
I am a GSSOC'21 participant and would like to contribute to this issue. I am proficient in C++ and have taken two courses for the same owing to which I can guarantee you a neat code with descriptive comments. My approach will include two pointer traversal of the sorted arrays in which I'll be swapping the elements on encountering that the array with the larger first element is now coming out to be smaller than the incremented first pointer's index.

**Comment by Vishal-Singh-1996** [comment]
@tarun26091999 pls assign it to me would like to create or do this problem in java with proper indentation and space and time complexity also include...

**Comment by Poojasingh5** [comment]
Hello!
I am a GSSoC'21 participant.
I would like to contribute the code for this issue in C++/CPP.
Kindly assign it to me.

**Comment by sandipswain** [comment]
@tarun26091999 can you add the gssoc label
