### ISSUE TITLE
Adding Graph Algorithms - Prim and Bellman Ford in C++

### ISSUE THREAD

**Issue by noob-26** [Algo-Phantoms/Algo-Tree#109]
I want to add the Prim and Bellman-Ford algorithm implemented in C++

**Comment by yashikajotwani12** [comment]
I Want to add Prim and Bellman-Ford algorithm in C++. Please assign me this  i would love to contribute in this.

**Comment by yashikajotwani12** [comment]
@nakul-19 Please assign me this issue . I want to contribute , I am a Gssoc'21 participant and I would add theory as well as implementation , with proper comments so that understanding it would be easy.

**Comment by nakul-19** [comment]
@yashikajotwani12  we really appreciate your interest in working on this issue, but the issues are assigned to those who comment first.

**Comment by tarun26091999** [comment]
closing the issue as it's been 9 days already.
