### ISSUE TITLE
Palindrome using Python 

### ISSUE THREAD

**Issue by Gautam204** [Algo-Phantoms/Algo-Tree#1093]
Hi I am  participating in GSSOC'21 .
I would like to contribute to check whether a string is Palindrome  in Python to this project.

Kindly assign this issue to me!
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by simarjeet30** [comment]
Hi I am Simarjeet ,participating in GSSOC'21 .
I would like to check whether a string is Palindrome in Python /C/C++.

Kindly assign this issue to me!
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by tarun26091999** [comment]
present at #450 and #586
