### ISSUE TITLE
Find LCA(lowest common ancestor) in a Binary tree!

### ISSUE THREAD

**Issue by reerajput930** [Algo-Phantoms/Algo-Tree#1101]
Hello, I would like to contribute to this issue in c++ language.
->in O(n) time complexity
->in O(n) space complexity
I am a GSsoc'21 participant. assign me the issue.
waiting for a positive response.

**Comment by Jassi10000** [comment]
Being a GSSOC'21 participant ,I would like to work on this issue , can you please assign me

**Comment by Aarti002** [comment]
hello @tarun26091999 @rudrakshi99 can i work on this issue in python?
Thank you!

**Comment by tarun26091999** [comment]
present at #374
