### ISSUE TITLE
Deletion of alternate nodes in Linked List

### ISSUE THREAD

**Issue by kshithih** [Algo-Phantoms/Algo-Tree#1106]
**EXPLANATAION:**
Given a Singly Linked List of size N, deletion of alternate nodes are implemented in this program.
Input 1 consists of number of testcases i.e. T
Input 2 consists of number of Nodes i.e. N

**EXAMPLE**
INPUT:1->2->3->4->5
OUTPUT: 1->3->5

Hello  @tarun26091999  please assign this to me .I would implement it using either C++.

**Comment by Aarti002** [comment]
hello @tarun26091999 @rudrakshi99 can i work on this issue in python?
Thank you!
