### ISSUE TITLE
Reverse Linked List

### ISSUE THREAD

**Issue by shubhgupta9** [Algo-Phantoms/Algo-Tree#1108]
To print a singly linked list in reverse order.

example input:-
1 3 5 6 7 -1 (-1 to end linked list)
example output:-
7 6 5 3 1 

I will add it in C++.

@tarun26091999 Please assign me this issue.

**Comment by Aarti002** [comment]
hey @tarun26091999 can i work on this issue in python?
Thank you!

**Comment by varshakr1298** [comment]
@tarun26091999 Can I work on this issue ?
