### ISSUE TITLE
In Place Merge Sort in C++

### ISSUE THREAD

**Issue by Harikrishnan6336** [Algo-Phantoms/Algo-Tree#1110]
The current implementation of merge sort in C++, is by using a temporary storage array. I can implement an improvised algorithm, where we do not need extra space.

Kindly assign this issue to me @tarun26091999

**Comment by theSatvik** [comment]
I will add it in C++.

@tarun26091999 Please assign me this issue.

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.
