### ISSUE TITLE
Remove the duplicates from sorted array in C++.

### ISSUE THREAD

**Issue by CSAURABH** [Algo-Phantoms/Algo-Tree#112]
Example:-
Input  : arr[] = {1, 2, 2, 3, 4, 4, 4, 5, 5}
Output : arr[] = {1, 2, 3, 4, 5}

**Comment by CSAURABH** [comment]
@rudrakshi99 I would like to solve this issue in C++. Please assign this to me under GSSOC'21.

**Comment by XZANATOL** [comment]
I would like to work in this too using Python
#GSSOC21

**Comment by soukarsha122** [comment]
I would like to work on this issue. I am a beginner and am very much interested to work on this using C++.

**Comment by Shashi2001** [comment]
i want to work on this issue using c++ under GSSOC'21.

**Comment by CSAURABH** [comment]
@nakul-19 Please assign me this issue. I want to contribute, I am a Gssoc'21 participant.

**Comment by harshbhalala-04** [comment]
I would like to work on this issue using c++, I am a GSSOC'21 participant. Please assign me this issue.

**Comment by nikitajuneja1** [comment]
I would love to contribute to solving the problem, I am a GSSOC'21 participant. Please assign it to me. Will try my best.

**Comment by Amit366** [comment]
Can I work on this issue using Java?
I am a GSSOC partiocipant.

**Comment by yogitasaini** [comment]
please assign this task to me in java under GSSOC'21 as participate

**Comment by AnjaliSrivastava722** [comment]
I would like to solve this in C++ using properties of XOR in O(N) time complexity please assign issue to me.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by XZANATOL** [comment]
@nakul-19 Any updates about the reviews of the added pull requests?
