### ISSUE TITLE
Linked list types

### ISSUE THREAD

**Issue by XZANATOL** [Algo-Phantoms/Algo-Tree#113]
I would like to work on this under the mentorship of GSSOC21.

# Details
* Stating the difference between Single, Double, and Circular linked lists and how we can implement them.
* Explaining how we can search through each type.

I can code using Python, and C++.

**Comment by manishaag7** [comment]
I would like to do it in c++.

**Comment by vedant-jain03** [comment]
I would love to fix this issue. I will provide a good description in every line so that code is easy to understand I can write code in C++

**Comment by Vansh-Gupta4** [comment]
i like to contribute to this project ...my code will be in java with proper comments and test cases

**Comment by shreyanspoddar** [comment]
Not a valid issue, refer the guidelines and other issue.
