### ISSUE TITLE
Declare, initialize and access Three Dimensional Array elements

### ISSUE THREAD

**Issue by drishika2002** [Algo-Phantoms/Algo-Tree#1134]
Hello, I am a GSSOC'21 participant.
I would like to code this issue in C++.
Kindly assign this issue to me.

**Comment by U-c0de** [comment]
Hello, I am a participant of GSSOC'21
I can code in C++ the declaration, initialize and access of the 3-D Array Elements
Kindly assign the issue to me...

I really want to contribute and want just a chance_
Assign the issue to me for the best solution.
