### ISSUE TITLE
Kadane's Algorithm 

### ISSUE THREAD

**Issue by Snehakri022** [Algo-Phantoms/Algo-Tree#1140]
I want to add this algorithm in C++. @avijit1999 @dheerajkotwani @tarun26091999  please assign to me
eg: Given an array arr of N integers. Find the contiguous sub-array with maximum sum.

**Comment by Naman-12911** [comment]
Hello sir I want to solve this issue please assign me under GSSOC.

**Comment by raksha009** [comment]
Already present at #178
