### ISSUE TITLE
KADANE'S ALGORITHM

### ISSUE THREAD

**Issue by aditi1403** [Algo-Phantoms/Algo-Tree#1147]
Sir
I would like to add the "Kadane's Algorithm" to the algorithm section. 
I am a GSSOC'21 participant. I write my code mostly in C++ and Python. I will make sure I write a clean code and follow the code of conduct. Kindly assign this issue to me.

Regards
Aditi Yadav

**Comment by debanjan-2002** [comment]
Sir,
Please assign this algorithm to me. I have already made PR regarding Brian's algorithm and it has been approved by you (yet to be merged) , and hence I know what format you demand in your codes. So I would be easily able to do this.
Regards,
Debanjan Poddar
@raksha009 
@tarun26091999 
@nakul-19 
@shreyanspoddar

**Comment by raksha009** [comment]
Already present at #178
