### ISSUE TITLE
[GSSOC'21] Diameter of a binary tree

### ISSUE THREAD

**Issue by neha030** [Algo-Phantoms/Algo-Tree#1151]
I am a GSSOC'21 participant and want to provide the C++ code.
Please assign me this.

**Comment by khusheekapoor** [comment]
Hello! I am a participant in GSSoC'21. I am really intrigued by this issue. Would be highly obliged if you could assign this to me. Thanks!

**Comment by Nikitha2309** [comment]
### Proposal 
Hello, I am a GSSoc'21 participant. Having a good interest knowledge of working with binary trees, I request you to assign this issue to me. 

### Protocol 
* The diameter of a Tree is the largest value among the diameter of its left subtree, the diameter of its right subtree and
the longest path between leaves that go through the root of the tree which can be computed from the heights of the subtrees of the tree. 
* Hence this can be implemented by recursively calculating and storing the diameter of each subtree by using above idea.

### Eligibility
* I have already worked on algorithms related to the diameter of a binary tree
* Hence I can provide an easy, understandable algorithm with quality code and highly understandable comments in languages C , C++ and Python. 

### Request 
Hence I request project admin to assign this issue to me.
Looking forward to this issue getting assigned to me and work on it, Thank you.

**Comment by raksha009** [comment]
Issue exists at #291
