### ISSUE TITLE
Reverse K nodes in a linked list.

### ISSUE THREAD

**Issue by sayantani11** [Algo-Phantoms/Algo-Tree#1161]
We will be given a linked list :
1->2->3->4->5->6->NULL
if the value of k=2, after reversing it will look like:
2->1->4->3->6->5->NULL

Will implement the concept of pointers and recursion to implement the problem, with comments at every step to make it clean and understandable

Want to do it in C++

**Comment by Aarti002** [comment]
hello , can i contribute to this issue in python  
thank you!

**Comment by Athira1601** [comment]
I would like to implement this using c++.kindly assign me this issue.

**Comment by sayantani11** [comment]
@raksha009 please assign
