### ISSUE TITLE
Merge 2 sorted Linked List

### ISSUE THREAD

**Issue by sayantani11** [Algo-Phantoms/Algo-Tree#1162]
We will be given 2 sorted linked list and will merge it to one sorted linked list.

Using the concept of pointers and merge sort with the help of a dummy node.

I would like to work on this issue using C++

**Comment by Fatema110** [comment]
I want to solve this issue using python 

Approach 
Traversing through a  two linked list and always choosing the node containing the smaller key to containing traversing from 

Complexity 
Time Complexity: O( m+n )
Space Complexity: O(n)

please assign me @tarun26091999

**Comment by aastha621** [comment]
I can solve this using Java. 
Time on Leetcode- 0ms, faster than 100% users
Time complexity-O(m+n)

Kindly assign it to me! @tarun26091999

**Comment by tarun26091999** [comment]
present at #468
