### ISSUE TITLE
Quicksort

### ISSUE THREAD

**Issue by OjusWiZard** [Algo-Phantoms/Algo-Tree#12]
The repo seems to be missing the Quicksort algorithm in C++

**Comment by rudrakshi99** [comment]
@OjusWiZard Yes, you can work on this algorithm and update the link in the [Algorithm/Searching_Sorting](https://github.com/Algo-Phantoms/Algo-Tree/tree/main/Algorithm/Searching_Sorting).

**Comment by rudrakshi99** [comment]
@OjusWiZard Nice :+1:
