### ISSUE TITLE
Bit Manipulation algorithms C++

### ISSUE THREAD

**Issue by somya51p** [Algo-Phantoms/Algo-Tree#1200]
As I have analyzed there are no example **questions on Bit manipulation** in this repo. I wish to add few questions for better clarity.
 
Basic questions like, _**Check for Power of 4, Reverse Bits of a Number, Swap all odd and even bits, Rotate bits**_ and many more would be added for better reference to the topic.

The programs would be implemented in **C++ language.**

I request mentors to assign me this issue for **GSSOC '21.**
@dheerajkotwani @tarun26091999 @anubhavitis @dheerajkotwani @rudrakshi99 @plazzy99 @nakul-19

**Comment by rudrakshi99** [comment]
@somya51p Open an issue for the single algorithm.
