### ISSUE TITLE
Using stack of arrays, covert infix expression into its postfix expression.

### ISSUE THREAD

**Issue by Diksha-11** [Algo-Phantoms/Algo-Tree#1207]
I want to add an algorithm that uses stack operations to convert a given infix expression into its postfix expression. The stack will be implemented using array. 
I want to add this algorithm in c++.

i request maintainers to please assign this issue to me.
@rudrakshi99 @plazzy99 @nakul-19 @tarun26091999 @OjusWiZard @shreyanspoddar @anjul2000

**Comment by Aarti002** [comment]
hey @tarun26091999 can i work on this issue in python?
Thank you!

**Comment by Diksha-11** [comment]
@tarun26091999 @rudrakshi99 Please /assign me this issue.

**Comment by tarun26091999** [comment]
#511
