### ISSUE TITLE
Tree traversal on binary tree.

### ISSUE THREAD

**Issue by Diksha-11** [Algo-Phantoms/Algo-Tree#1208]
I want to implement an algorithm to treverse a binary tree.

First we create root node having value, let 10 . Then, insert node values into the tree (left & right). suppose we insert 20,30, 40,50, 60,70. 
Output: Preorder 10 20 40 50 30 60 70
              inorder  40 20 50 10 60 30 70
              postorder 40 50 20 60 70 30 10 

I want add this algorithm in c++

Thus, I request maintainers to allow me to add this algo.
@rudrakshi99 @plazzy99 @nakul-19 @tarun26091999 @OjusWiZard @shreyanspoddar @anjul2000

**Comment by Diksha-11** [comment]
@rudrakshi99 @plazzy99 please /assign me this issue.

**Comment by tarun26091999** [comment]
#144
