### ISSUE TITLE
Swapping two numbers using friend function

### ISSUE THREAD

**Issue by PANKAJ3590** [Algo-Phantoms/Algo-Tree#1221]
**Is your feature request related to a problem? Please describe.**
swapping of two numbers from different classes using friend function

**Describe the solution you'd like**
I will create two classes , one class will have one number and other class will have another number. And then I will create a friend function which will swap both the numbers.

******Example*******
input: x=3, y=2
output: x=2, y=3

**Do you want to work on it**
c++

**Comment by PANKAJ3590** [comment]
@tarun26091999 @rudrakshi99 @plazzy99 @nakul-19 please assign this issue to me I have created the code neat and easily readable. I am new to open source and GSSOC'21 participant. Thankyou

**Comment by omniasalah276** [comment]
I'm a gssoc'21 participant and would like to implement this in python please assign it to me
