### ISSUE TITLE
Multilevel inheritance

### ISSUE THREAD

**Issue by PANKAJ3590** [Algo-Phantoms/Algo-Tree#1222]
**Is your feature request related to a problem? Please describe.**
calculating the marks of four subjects, input student information , displaying them using different classes with the help of multilevel inheritance.

**Describe the solution you'd like**
I will create a class which will take input of student information, another class which will take input of marks of 4 subjects, and by another class I will display this all using multilevel inheritance.

**Do you want to work on it**
c++

**Comment by PANKAJ3590** [comment]
@tarun26091999 @rudrakshi99 @plazzy99 @nakul-19 please assign this issue to me I have created the code neat and easily readable. I am new to open source and GSSOC'21 participant. Thankyou

**Comment by tarun26091999** [comment]
this is not relevant to this repo.
