### ISSUE TITLE
Count the number of set bits for a particular number[Bit Manipulation]

### ISSUE THREAD

**Issue by Maitryee-Choudhary** [Algo-Phantoms/Algo-Tree#1229]
**Is your feature request related to a problem? Please describe.**
A program to count the number of set bits of a particular number that comes under bit manipulation.
The program will be written in C++.

**Describe the solution you'd like**
I will be adding the program for the above problem

**Do you want to work on it**
C++

hey @rudrakshi99  will u please assign to me

**Comment by nikhv** [comment]
I would like to add the work on this issue 

Do you want to work on it
        I want to work on this issue in the C++

I request mentors to assign me this issue for GSSOC '21.
@dheerajkotwani @tarun26091999 @anubhavitis @dheerajkotwani @rudrakshi99 @plazzy99 @nakul-19

**Comment by shubhidua** [comment]
I would like to work on this in java. Kindly assign me this issue.

**Comment by nikhv** [comment]
I have made push request ,#1389 for issue 1229 please merge it
@dheerajkotwani  @tarun26091999  @anubhavitis  @dheerajkotwani  @rudrakshi99  @plazzy99  @nakul-19

**Comment by nikhv** [comment]
@tarun26091999  , I'm a GSSOC'21 participant , please assign this to me

**Comment by tarun26091999** [comment]
present at #44
