### ISSUE TITLE
Finding Matrix follows Teoplitz Matrix Algorithm or Not ?

### ISSUE THREAD

**Issue by krishna-NIT** [Algo-Phantoms/Algo-Tree#1231]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 @tarun26091999  please assign me this issue

**Comment by Srishti013** [comment]
Hi, 
I am a GSSOC'21 participant.
I would like to solve this issue in C++. Please assign it to me.
