### ISSUE TITLE
Add Sorting Algorithms

### ISSUE THREAD

**Issue by diptendunandi** [Algo-Phantoms/Algo-Tree#124]
- [x] C++
    - [ ] Bubble Sort
    - [ ] Insertion Sort
    - [ ] Selection Sort
    - [ ] Merge Sort
    - [ ] Quick Sort
 - [x] Java
    - [x] Bubble Sort
    - [x] Insertion Sort
    - [x] Selection Sort
    - [ ] Merge Sort
    - [ ] Quick Sort
- [x] Python
    - [ ] Bubble Sort
    - [ ] Insertion Sort
    - [ ] Selection Sort
    - [ ] Merge Sort
    - [ ] Quick Sort

**Comment by rohitsigar** [comment]
@diptendunandi please assign this task to me, I have experience writing blogs on DSA and competitive programming.
I am selected as a Mentee at GirlScript Summer of Code and this project really excites me so I would love to contribute to such an amazing repo.
I will do it in C++

**Comment by yashikajotwani12** [comment]
Please Assign me this. I have practiced this before , I am a beginner in contributing so please  assign me this , i would probably do it.

**Comment by soukarsha122** [comment]
Please assign me this. I am very much willing to participate on this issue...

**Comment by harshbhalala-04** [comment]
I would like to work on this issue using c++, I am a GSSOC'21 participant. Please assign me this issue.

**Comment by yashikajotwani12** [comment]
> Please Assign me this. I have practiced this before , I am a beginner in contributing so please assign me this , i would probably do it.

I can do the same in python as well as c++.
please assign me this issue @nakul-19

**Comment by yashikajotwani12** [comment]
> Please Assign me this. I have practiced this before , I am a beginner in contributing so please assign me this , i would probably do it.
I can do this in python as well as c++.
Please assign me this issue. @nakul-19

**Comment by Aastha26-lab** [comment]
Hello @rudrakshi99 @nakul-19 @plazzy99
I am a GSSoC'21 participant. 

I would like to work on this issue in Java. Please assign this issue to me.

**Comment by RhuthuHegde** [comment]
can I work on this issue under gssoc'21?

**Comment by yogitasaini** [comment]
Please , assign this issue to me in java under gssoc'21

**Comment by pinkuchoudhury69** [comment]
Hello @rudrakshi99 @nakul-19 @plazzy99 
I am a GSSoC'21 participant.
I would like to work on this issue in Python as well as Java.
It would be really great if you assign this issue to me.
Hoping for a good outcome from your side.

**Comment by nikitajuneja1** [comment]
I would love to contribute to solving the problem, I am a GSSOC'21 participant. Please assign it to me. Will try my best.

**Comment by plazzy99** [comment]
> Please Assign me this. I have practiced this before , I am a beginner in contributing so please assign me this , i would probably do it.

always mention the language in which you want to contribute

**Comment by plazzy99** [comment]
> I would love to contribute to solving the problem, I am a GSSOC'21 participant. Please assign it to me. Will try my best.

Always remember to mention the language in which you wanted to contribute.

**Comment by nikitajuneja1** [comment]
@plazzy99  I will implement these algorithms in Cpp and Java.

**Comment by plazzy99** [comment]
> @plazzy99 I will implement these algorithms in

It is now assigned to others you can work on other issue

**Comment by yogitasaini** [comment]
please , assign this task to me in java under GSSOC'21 as participate

**Comment by arnab031** [comment]
I would like to implement these algorithm in python as a part of GSSoC 2021. I would be thankful to you if you please assign me this.

**Comment by Adrenalinerush07** [comment]
I am a GSSoC'21 participant.
I assure you I can handle this issue as I am extremely good at DSA, problem-solving, and C++.

It would be really great if you assign this issue to me.
Hoping for a good outcome from your side.

**Comment by jainstuti** [comment]
Hi, I can contribute to writing any of these algorithms in c++. I will write the code with proper comments ans conventions mentioned in the readme. Please assign this to me as a part of gssoc21

**Comment by anushka00** [comment]
Hi, I am a gssoc'21 participant and want to contribute in this  great project. I'll write the code  in compliance to all the noted guidelines with proper comments .  I would like to work on this issue. I will write all sorting algorithms in C++ .

**Comment by khushi123456789** [comment]
I am  GSSOC'2021 participant. I am good at C++,C.Please assign this issue to me.
 Thankyou!

**Comment by harshsinha03** [comment]
I am GSSOC'2021 participant. I am good at python and i already have all the sorting programs ready with me in python.
Please assign this issue to me.
Thankyou!

**Comment by Swetha126** [comment]
Hey I am a GSSOC'21 participant.
I can code proficiently in C,C++ and Python with appropriate comments.
Please assign me this issue

**Comment by EkjotKaur** [comment]
Hey I am a GSSOC'21 participant.
I would like to contribute on following sorting algorithms

1. Heap Sort
2. Shell Sort
3. Count sort
4. Radix sort
5. Bucket sort

Please asign me this issue @tarun26091999

**Comment by tarun26091999** [comment]
> Hey I am a GSSOC'21 participant.
> I would like to contribute on following sorting algorithms
> 
> 1. Heap Sort
> 2. Shell Sort
> 3. Count sort
> 4. Radix sort
> 5. Bucket sort
> 
> Please assign me this issue @tarun26091999

do them in C++ and raise seprate PR for every algorithm. Also go through the guidelines before raising the PR.

**Comment by Swetha126** [comment]
Hey I am a GSSOC'21 participant.
I would like to code the following in Python along with time complexity and appropriate comments : 
 1. Time sort
 2. Quick sort
 3. Merge sort 
 4. Insertion sort 
 5. Bubble sort
 6. Heap sort 
Please assign me this issue

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on it.
I can give the code in C++ with proper indentation, comment and description.
1.Bubble sort
2.merge sort
3.quick sort
4.Insertion sort
5.Selection sort
please assign me this task.

**Comment by MaitriDA** [comment]
Hey I am a GSSOC'21 participant.
I would like to work on this problems. I am skilled in C++. I will make sure that the code works well with almost all the type of number array. I will give proper comments. Please assign this issue to me

**Comment by anubhab-code** [comment]
I am a GSSoC'21 participant.
I can contribute to this issue in Python3 language.
If this hasn't been assigned to anyone with Python3 language, I would love to work on it.

**Comment by rudrakshi99** [comment]
> I would love to contribute to solving the problem, I am a GSSOC'21 participant. Please assign it to me. Will try my best. I can implement these algorithms in Cpp and Java.

Are you working on all these algorithms in CPP?

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Add Sorting Algorithms 

I can contribute this much algorithms 

                           in C++
 Bubble Sort
 Insertion Sort
 Selection Sort
 Merge Sort
 Quick Sort
 Count Sort
 Bucket Sort 
 Radix Sort 
 Wave Sort 

 Java
 Bubble Sort
 Insertion Sort
 Selection Sort
 Merge Sort
 Quick Sort
 Count Sort
 Bucket Sort 
 Radix Sort 
 Wave Sort 

i will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.

so i would like @rudrakshi99 , @nakul-19  ,  @plazzy99  to please assign this Issue to me :)

**Comment by eishagoel15** [comment]
I am a Gssoc'21 participant and I want to contribute to this issue. I can give the code for all the sorting algorithms in python. So, please assign this issue to me.

**Comment by plazzy99** [comment]
> Hey I am a GSSOC'21 participant.
> I would like to code the following in Python along with time complexity and appropriate comments :
> 
> 1. Time sort
> 2. Quick sort
> 3. Merge sort
> 4. Insertion sort
> 5. Bubble sort
> 6. Heap sort
>    Please assign me this issue

Raise diffferent issue for that with no duplicasy

**Comment by neha07kumari** [comment]
Hello!! I'm a GSSOC'21 participant .Please assign me the task . I would like to solve the following sorting algorithms in C++
Bubble Sort
 Insertion Sort
 Selection Sort
 Merge Sort
 Quick Sort
@tarun26091999

**Comment by anshika272** [comment]
hello @tarun26091999, I am anshika dubey a gssoc21 participant please assign me this issue. I will be using the C++ language. 
I would like to contribute to merge sort and quick sort.
