### ISSUE TITLE
Implementing Stack Concepts

### ISSUE THREAD

**Issue by Shreyash41** [Algo-Phantoms/Algo-Tree#127]
Hey there, I would like to Implement multiple Stack Concepts using C++ Language. 
Here is some stuff that I would like to add :
1. Stock Span Problem
2. Balanced Parenthesis.
3. Largest Rectangular Area in Histogram.
4. Infix to Prefix Conversion.

I would like to contribute as a participant of GSSOC'21.

**Comment by Shreyash41** [comment]
@nakul-19 Hey there, I would like to contribute to this please assign it to me.

**Comment by Nik-09** [comment]
Hello @nakul-19 @plazzy99 I would like to work on this issue as GSSoC participant.
My language of work is python. please assign me .
Thanks.

**Comment by plazzy99** [comment]
@Shreyash41 please mention the language in which you are going to contribute

**Comment by AnjaliSrivastava722** [comment]
I would like to add solutions to stock span and balanced paranthesis problems in Java with test cases .Please assign this issue to me.#GSSOC21

**Comment by Vansh-Gupta4** [comment]
Hey there, I would like to Implement multiple Stack Concepts using C++ Language.
Here is some stuff that I would like to add :
Stock Span Problem
Balanced Parenthesis.
Largest Rectangular Area in Histogram.
Infix to Prefix Conversion.


I would love to contribute in this ...i will do it using java

**Comment by Shreyash41** [comment]
@plazzy99 @nakul-19  Sir Since this is for GSSoC'21 it would be really nice if any mentor could add a GSSOC'21 label for this issue to avoid confusion.

**Comment by Suvraneel** [comment]
@plazzy99  @rudrakshi99 
I'd love to submit the C++ solution to the above problems (in multiple time complexities for stock span - > O(n^2) & O(n))
Please assign me all these problems in C++ under GSSOC '21. Thanks

**Comment by tarun26091999** [comment]
you cannot solve multiple problems in single issue.

**Comment by Shreyash41** [comment]
I have already completed some parts. I make a new issue please assign it to me.
