### ISSUE TITLE
Implement heap in python 

### ISSUE THREAD

**Issue by hridhi** [Algo-Phantoms/Algo-Tree#1278]
**Is your feature request related to a problem? Please describe.**
This problem is related to implementing heap datastructure.
**Describe the solution you'd like**
It will have different functions like hepify , delete the element etc.
**Do you want to work on it**
Yes i want to work on it and i would like to implement it in python language 
please assign me the issue under GSSoC label thanks !!
@anubhavitis @dheerajkotwani @tarun26091999 @avijit1999 @todi-2000

**Comment by AparnaJha17** [comment]
Can I work on the same issue but in C++ language?
Mentors please assign that to me.
@anubhavitis @dheerajkotwani @tarun26091999 @avijit1999 @todi-2000

**Comment by Aarti002** [comment]
hey @tarun26091999 @rudrakshi99 can i work on this issue in python
Thank you!

**Comment by hridhi** [comment]
@Aarti002  I thought on working in python language hope you can choose some other language thank you !

**Comment by Aarti002** [comment]
@hridhi No issue , go ahead ! i thought you haven't mention language , anyways it will be assigned to you if u have commented first.

**Comment by tarun26091999** [comment]
present at #279
