### ISSUE TITLE
Diameter of Binary Tree in C++

### ISSUE THREAD

**Issue by SrishtiSingh2001** [Algo-Phantoms/Algo-Tree#1321]
**Description**
The diameter of a binary tree is the number of nodes on the longest path between two end nodes.

**Motivation**
To help learn this important program of binary trees.

I would like to add a C++ program to find Diameter of Binary Tree under GSSoC'21 . 
Kindly assign this issue to me.

**Comment by Mugdha-Hazra** [comment]
Hello,  @SrishtiSingh2001 @aaadddiii @anubhavitis @veenit1802 @dheerajkotwani  I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by AnushkaS09** [comment]
Please /assign
I will work on it in c++

**Comment by jasleen5900** [comment]
I will work on it in C++. Kindly assign me this issue.. I am part of GSSoC'21.

**Comment by shahina-bano** [comment]
I want to work on in Python. So please assign me this issue @plazzy99

**Comment by yashmita** [comment]
I would like to work on this issue in Java. Kindly assign it to me @raksha009 .

**Comment by raksha009** [comment]
Issue exists at #291
