### ISSUE TITLE
Code for KMP algorithm, Manacher's algorithm and Rabin Carp in C++

### ISSUE THREAD

**Issue by earnsans** [Algo-Phantoms/Algo-Tree#1337]
These are popular string algorithms, 
KMP algorithm and Rabin Carp are used for pattern matching.
Manacher's algorithm is used to find the longest palindrome substring in a string.

I want to raise this issue, I'll be providing the code in C++ with the implementation of OOP's concept.

I'm a participant at GSSOC'21.
@plazzy99 @rudrakshi99 @aaadddiii @anubhavitis @dheerajkotwani @tarun26091999
 could you please assign this issue to me ?

**Comment by Mugdha-Hazra** [comment]
Hello, @earnsans @aaadddiii @anubhavitis @veenit1802 @dheerajkotwani  I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by earnsans** [comment]
Hi @Mugdha-Hazra I'm also a participant at GSSOC'21 and have raised this issue lately. The Admins would assign the issue, so lets wait for them to respond.

**Comment by tarun26091999** [comment]
cannot solve multiple problems in same issue.
