### ISSUE TITLE
Remove loop from a linked list.  

### ISSUE THREAD

**Issue by KhushiChaudhary744** [Algo-Phantoms/Algo-Tree#1339]
The user shall enter the linked list.
I will be implementing this in python java and C++

**Comment by AnushkaS09** [comment]
I will implement it in c++. Please /assign it to me

**Comment by tarun26091999** [comment]
> The user shall enter the linked list.
> I will be implementing this in python java and C++

do it in java

**Comment by omniasalah276** [comment]
@tarun26091999 I will implement this in python, please assign me this.

**Comment by thekanishkagupta** [comment]
Hello, I am a GSSoc'21 participant. 
I will implement this in java, requesting you to assign this issue to me.

**Comment by Shreya0229** [comment]
Hey, I am a GSsoc'21 participant too. Kindly assign this to me. I'll work in java on this problem if that has not been already done.

**Comment by KhushiChaudhary744** [comment]
I am currently assigned to do it in Java. I shall upload by tomorrow afternoon

**Comment by Srishti013** [comment]
Hi,
I am a GSSOC'21 participant. I would like to solve this issue in Python. Please assign it to me.
