### ISSUE TITLE
Check if a linked list is a palindrome or not.

### ISSUE THREAD

**Issue by KhushiChaudhary744** [Algo-Phantoms/Algo-Tree#1340]
This is a general program, the user shall enter the linked list.

I will be implementing this in java C++ and python 3.

**Comment by AnushkaS09** [comment]
Please /assign 
I will be implementing it in c++

**Comment by Shreya0229** [comment]
Hey, kindly assign it to me. I'll work in java on this problem. [GSsoc'21]

**Comment by raksha009** [comment]
@KhushiChaudhary744 go ahead with python
@AnushkaS09  go ahead with cpp
@Shreya0229 go ahead with java

**Comment by divyanshu450** [comment]
I would like to work on this issue using java. Kindly assign it to me

@raksha009
