### ISSUE TITLE
Prim's Algorithm, Connected components and Articulation point in JAVA, Python and C++

### ISSUE THREAD

**Issue by earnsans** [Algo-Phantoms/Algo-Tree#1341]
Hi I am a participant at GSSOC'21.
And I felt important to raise this issue., as these have been missing under the topic Graphs.

Prim's Algorithm is used to find the minimum spanning tree of a graph. 
and
To list the Connected components and Articulation points.

I'll give the code in Python, C++ and JAVA.

@plazzy99 @rudrakshi99 @aaadddiii @anubhavitis @dheerajkotwani @tarun26091999 
 could you please assign this issue to me.

**Comment by Yuvraj-kadale** [comment]
If possible , i would like to contribute in python :)

**Comment by tarun26091999** [comment]
you cannot solve multiple ques in same issue and all the issues has been assigned before.
