### ISSUE TITLE
Pangram, String, Python

### ISSUE THREAD

**Issue by chicken-biryani** [Algo-Phantoms/Algo-Tree#1345]
**Is your feature request related to a problem? Please describe.**
_A string containing every letter of the alphabet is called a Panagram_ 
Example: "  A quick brown fox jumps over the lazy dog " --> This string is a pangram

**Describe the solution you'd like**
I would like to add this program under string

**Do you want to work on it**
Pyhton

**Comment by chicken-biryani** [comment]
I would like to work on this issue under GSSOC'21.

**Comment by Atif-reyaz-khan** [comment]
I would like to implement pangram in c++

**Comment by raksha009** [comment]
issue at #925
