### ISSUE TITLE
Tower of Hanoi using recursion in Python

### ISSUE THREAD

**Issue by Koushik890** [Algo-Phantoms/Algo-Tree#1350]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
The story of the Tower of Hanoi:
• 3 tall spikes
• Stack of 64 different sized discs –start on one spike
• Need to move the stack to second spike (at which point universe ends)
• Can only move one disc at a time, and a larger disc can never cover up a small disc

**Describe the solution you'd like**
Just think recursively!
• Solve a smaller problem
• Solve a basic problem
• Solve a smaller problem

**Do you want to work on it**
Mention the one language you want to be assigned for this issue.
Tower of Hanoi using recursion in Python. Recently I've been practising the Recursion and found the Tower Of Hanoi problem very interesting. So I would like to solve the problem of the Tower of Hanoi using Recursion in Python. As a participant of GSSoC'21 please assign this issue to me.

Hey @tarun26091999, I want to add this program to `Algo-Tree/Code/Python/`

**Comment by raksha009** [comment]
Issue present at #828
