### ISSUE TITLE
Binary Search 

### ISSUE THREAD

**Issue by walaa5** [Algo-Phantoms/Algo-Tree#1352]
**Is your feature request related to a problem? Please describe.**
It's the Implementation of Binary Search algorithm in c++.

**Describe the solution you'd like**
I will just implement Binary Search function, that it will take a sorted array, and a variable to search for it,
then implement the Binary Search algorithm and return the position of the variable.

**Do you want to work on it**
c++ .

**Comment by walaa5** [comment]
please, assign this issue to me.

**Comment by jasleen5900** [comment]
I would like to work in C++, please assign me this issue.

**Comment by thenextgoogler** [comment]
Please assign me this issue.

**Comment by AdityaGarg00** [comment]
Please assign this issue to me I am a beginner in open source I am quite familiar with binary search so i would like to contribute to this and ill do my best

**Comment by muthuannamalai12** [comment]
I would love to work on this issue in python. Kindly assign it to me @tarun26091999

**Comment by khusheekapoor** [comment]
Hello! I am a participant in GSSoC'21. I would like to work on this using Java. Please assign it to me.
