### ISSUE TITLE
Subset sum equal to k

### ISSUE THREAD

**Issue by anshika272** [Algo-Phantoms/Algo-Tree#1359]
**Is your feature request related to a problem? Please describe.**
Given an array A of size n and an integer K, return all subsets of A which sum to K.

**Describe the solution you'd like**
I want the solution to be using recursion.
**Do you want to work on it**
I would like to work on this issue and would be using the C++ language.

**Comment by raksha009** [comment]
Hey, we want to add the most optimised solution to be added. Would be able to solve this using dp ?

**Comment by madhvi02** [comment]
I would like to code this in C++. I m a GSSOC'21 Partcipant .I will assure you that I will provide a most optimized code and 
commented code with efficient time complexity.@tarun26091999 @dheerajkotwani @anubhavitis @dheerajkotwani @rudrakshi99 @plazzy99 @nakul-19 please assign this to me .
Regards
Madhvi .

**Comment by raksha009** [comment]
> **Is your feature request related to a problem? Please describe.**
> Given an array A of size n and an integer K, return all subsets of A which sum to K.
> 
> **Describe the solution you'd like**
> I want the solution to be using recursion.
> **Do you want to work on it**
> I would like to work on this issue and would be using the C++ language.

hey, plz reply if you would be able to solve via dp else assigning the issue to others.

**Comment by tarun26091999** [comment]
@raksha009 isn't this issue same as #148

**Comment by raksha009** [comment]
> @raksha009 isn't this issue same as #148

Ohh yess, my bad. Thanks
