### ISSUE TITLE
Tower of Honai Game using recursion

### ISSUE THREAD

**Issue by anshika272** [Algo-Phantoms/Algo-Tree#1360]
**Is your feature request related to a problem? Please describe.**
Tower of Hanoi is a mathematical puzzle where we have three rods and n disks. The objective of the puzzle is to move all disks from source rod to destination rod using third rod (say auxiliary). The rules are :
1) Only one disk can be moved at a time.
2) A disk can be moved only if it is on the top of a rod.
3) No disk can be placed on the top of a smaller disk.
Print the steps required to move n disks from source rod to destination rod.
**Describe the solution you'd like**
using recursion.
**Do you want to work on it**
I would like to work on this issue using C++ language.

**Comment by sayantani11** [comment]
This is already done.
