### ISSUE TITLE
Check whether a given binary tree is a Binary Search Tree 

### ISSUE THREAD

**Issue by Meghna180401** [Algo-Phantoms/Algo-Tree#137]
I would like to implement the solution to check if a binary tree is a Binary Search Tree in Java.
I would include test cases,complexities as well as the detailed algorithmic explanation for the same and also the common approach which leads to wrong answers.
@rudrakshi99 @nakul-19 @plazzy99 Kindly assign this to me as a part of GSSOC'21.

**Comment by sakshi2707** [comment]
Hello, I am from GSSoC 2021, I would like to contribute to this issue. Could you assign me this? I will implement it in Java/c++

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you .
Thank you .

**Comment by tarun26091999** [comment]
@sakshi2707 do it in cpp

**Comment by khushboojoshi3** [comment]
I would like to work on this issue in c++, please assign it to me.

**Comment by Deepaliiii** [comment]
I would like to work on this issue in c++, please assign it to me.

**Comment by shahina-bano** [comment]
I would like to work on this issue in python. Kindly assign it to me @plazzy99  @tarun26091999

**Comment by einhawking** [comment]
I am a participant of GSSOC'21
I would like to contribute in this

**Comment by purohitmansi** [comment]
Please do assign this to me.
