### ISSUE TITLE
Height balanced Binary tree

### ISSUE THREAD

**Issue by sayantani11** [Algo-Phantoms/Algo-Tree#1374]
**Is your feature request related to a problem? Please describe.**
For each node the difference between the heights of the left subtree and right subtree is <=1.

**Do you want to work on it**
would like to work on it in C++

**Comment by raksha009** [comment]
Plz give a little more detailed description of yr problem statement

**Comment by sayantani11** [comment]
@raksha009 
Consider a height-balancing scheme where following conditions should be checked to determine if a binary tree is balanced.
An empty tree is height-balanced. A non-empty binary tree T is balanced if:
1) Left subtree of T is balanced
2) Right subtree of T is balanced
3) The difference between heights of left subtree and right subtree is not more than 1

**Comment by Srishti013** [comment]
Hi,
I am a GSSOC'21 participant. I would like to solve this issue in Python. Please assign it to me.

**Comment by Srijan0519** [comment]
Hi 
I would like to solve this issue using java. Please assign me.
