### ISSUE TITLE
Traversing, Adding and Deleting an Element from a Circular Queue.

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1388]
**Is your feature request related to a problem? Please describe.**
Implementing the Circular Queue Data Structure to Traverse, Add and Delete an Element from a Circular Queue.

**Do you want to work on it**
Yes, I would want to work on this using Java.
My code will have Time Complexity O(1).

Kindly assign me this issue @raksha009 @rudrakshi99 @tarun260919. Thank you!
This will be the first ever issue I opened, so please tell me if I did it correctly :)

**Comment by raksha009** [comment]
Issue Present at #58
