### ISSUE TITLE
Wanted to Add program using  recursion 

### ISSUE THREAD

**Issue by UG-SEP** [Algo-Phantoms/Algo-Tree#1397]
**Is your feature request related to a problem? Please describe.**
I wanted to add program like decimal to octal conversion , decimal to binary conversion , tower of hanoi etc.     
In algorithm->recursion
**Describe the solution you'd like**
 I will create also the program using recursion in c language..
**Do you want to work on it**
Yes i wanted  to get assign for this . Please Assign me

**Comment by raksha009** [comment]
Heyy, a issue deals with only 1 problem statement at a time. Plz keep this in mind and also add a little detail about yr problem statement in the issue next time onwards :)

**Comment by UG-SEP** [comment]
ok
