### ISSUE TITLE
double ended queue in c using array

### ISSUE THREAD

**Issue by UG-SEP** [Algo-Phantoms/Algo-Tree#1403]
**Is your feature request related to a problem? Please describe.**
this is a queue data structure trending question.
**Describe the solution you'd like**
In this i let the user to insert or delete data from both side front and end for that i make some function which will perform this work and an struct named deque and then create the menu which give 4 option to user 1: Insert from Front 2: Insert from rear 3: Delete from front 4: Delete from rear 
**Do you want to work on it**
Yes I wanted to work so please assign me .

**Comment by khusheekapoor** [comment]
Hey! I would want to work on this using Java. Please assign this to me. Thanks!

**Comment by Athira1601** [comment]
I would like to implement this using c++. Kindly assign me this issue.

**Comment by UG-SEP** [comment]
anyone please assign @rudrakshi99 @tarun26091999

**Comment by khusheekapoor** [comment]
Hello! I would like to work on this using Java under GSSoC'21. Could you please assign it to me? Thanks.
