### ISSUE TITLE
Adding Disjoint-Set data structure in C++

### ISSUE THREAD

**Issue by adityabandal** [Algo-Phantoms/Algo-Tree#1405]
**Is your feature request related to a problem? Please describe.**
I want to add disjoint set data structure (union-find) algorithm to this repository.

**Describe the solution you'd like**
I will be adding most efficient version of disjoint set data structure.

**Do you want to work on it**
C++

**Comment by Athira1601** [comment]
I would like to implement this using c++.kindly assign me this issue
