### ISSUE TITLE
Hashing in C++

### ISSUE THREAD

**Issue by Debashish-hub** [Algo-Phantoms/Algo-Tree#1419]
**Is your feature request related to a problem? Please describe.**
Using Hashing in C++ various problems can be solved like  Is sudoku valid, triplet sum in array, Key pair, Intersection of two arrays etc.

**Describe the solution you'd like**
Problems like  Is sudoku valid, triplet sum in array, Key pair, Intersection of two array will be solved using hashing.

**Do you want to work on it**
C++

**Comment by shreyanspoddar** [comment]
Multiple problems cannot be raised in a single issue, please raise them in individually and kindly before raising an issue check if it's previously present or not.
