### ISSUE TITLE
Reverse a Linked List

### ISSUE THREAD

**Issue by gayatri517** [Algo-Phantoms/Algo-Tree#142]
Given a linked list, the task is to reverse it. 
I want to work on this issue in C++. I will provide 2 testcases as comments in the code. 
I will also add comments to ensure it is well understood by others.

I am a participant of GSSOC'21 please assign this issue to me @rudrakshi99 
Thank you.

**Comment by yashikajotwani12** [comment]
I want to take this issue in python . I would probably implement it  , I am a Participant in Gssoc'21 . and please assign me this issue. @nakul-19 .

**Comment by Aastha26-lab** [comment]
I would love to work on this issue in Java. I am a Gssoc'21 participant. @nakul-19 sir pls assign me this issue.

**Comment by nikitajuneja1** [comment]
I would love to contribute to solving the problem, I am a GSSOC'21 participant. Please assign it to me. I will try my best and provide proper comments for better understanding.

**Comment by ChetasShree** [comment]
I want to solve this issue using python...
Please assign this issue to me under GSSOC 21 ,using python language.
Looking forward to contribute here...

**Comment by Amit366** [comment]
I want to solve this issue using C.
Please assign this issue to me under GSSOC 21 ,using C language.

**Comment by vedant-jain03** [comment]
Hello
I am GSSOC21 PARTICIPANT
And I can code this issue in C++, C,python along with line comments and best time complexity.
Please assign me this issue.

**Comment by gayatri517** [comment]
@nakul-19 @plazzy99 @rudrakshi99 kindly review this issue and please assign it to me. I want to work on this code in C++ as a participant of GSSOC'21.

**Comment by sumitsantape30** [comment]
I can code this issue in Java, along with line comments & time complexity.
Please assign me this issue.
I am GSSOC21 PARTICIPANT.

**Comment by Vansh-Gupta4** [comment]
i would like to contribute to this project ...my code will be in java with proper comments and test cases

**Comment by Aditya7494** [comment]
I am a GSSOC'21 participant and i would like to solve the problem reverse a linkedlist in java programming language.
Can you please assign it to me?
