### ISSUE TITLE
Graph Traversal Algorithms

### ISSUE THREAD

**Issue by muthuannamalai12** [Algo-Phantoms/Algo-Tree#143]
Graphs are a powerful and versatile data structure that easily allows you to represent real-life relationships between different types of data (nodes). Graphs are one of the most difficult topics of data structure.
I would love to work on Breadth-First Search (BFS) and Depth-First Search (DFS) Graph traversal algorithms in python as a part of Girl Script Summer Of Code. @rudrakshi99 @nakul-19 @plazzy99 Kindly assign it to me

- [x] C++
    - [ ] BFS
    - [ ] DFS  
- [x] Java
    - [ ] BFS
    - [ ] DFS
- [x] Python
    - [ ] BFS
    - [ ] DFS

**Comment by yashikajotwani12** [comment]
I can implement it in c++. Assign me for this.

**Comment by nikitajuneja1** [comment]
I would love to contribute to solving the problem, I am a GSSOC'21 participant. Please assign it to me. Will try my best. I can implement it in C, C++, Java and Python.

**Comment by plazzy99** [comment]
> I would love to contribute to solving the problem, I am a GSSOC'21 participant. Please assign it to me. Will try my best. I can implement it in C, C++, Java and Python.

go ahead with java

**Comment by muthuannamalai12** [comment]
I have created a PR for this issue @tarun26091999
