### ISSUE TITLE
Union of two arrays in python

### ISSUE THREAD

**Issue by soumik2012** [Algo-Phantoms/Algo-Tree#1452]
## 🚀 Feature

Union of the two arrays can be defined as the set containing distinct elements from both the arrays. If there are repetitions, then only one occurrence of element should be printed in union.

### Have you read the Contributing Guidelines on Pull Requests?

Yes I have read 

## Motivation

Want to contribute to Algo-Tree

## Pitch
Union of the two arrays can be defined as the set containing distinct elements from both the arrays. If there are repetitions, then only one occurrence of element should be printed in union.

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 participant. I would like to implement this in Java. Would be obliged if you could assign it to me. Thanks!

**Comment by dikshajoshi18** [comment]
hey, I can do this in c++.
discord: diksha#6684
please assign it to me. @rudrakshi99

**Comment by madhvi02** [comment]
Sir @tarun26091999 @rudrakshi99 ma'am 
Please assign this problem to me. I would like to solve this in c++.
I will surely provide the code with proper documentation and comments.

**Comment by soumik2012** [comment]
Sir @tarun26091999 @rudrakshi99 ma'am I made the PR please check and add the GSSOC'21 label

**Comment by tarun26091999** [comment]
present at #216

**Comment by soumik2012** [comment]
@tarun26091999  this is on python
