### ISSUE TITLE
Insertion at start

### ISSUE THREAD

**Issue by XZANATOL** [Algo-Phantoms/Algo-Tree#146]
In the Array/Readme.md file there are links to the "Insertion at start" algorithm for files built in Java and Python. But they link to 404 page. I have checked the code folder for these files and found out that they don't exist.

I would like to add the Python algorithm, and I can update the Readme.md link for it if I am allowed to.

# Details
* Will add test cases.
* Code will be commented to make it easy to read the code flow.
* Will promote the user to add his/her own desired number to the algorithm. (Instead of building a pure driver code.)

#GSSOC21

**Comment by tarun26091999** [comment]
@XZANATOL do it in java
