### ISSUE TITLE
Subset Sum Algorithm using Dynamic Programming

### ISSUE THREAD

**Issue by shawavisek35** [Algo-Phantoms/Algo-Tree#148]
Hello @rudrakshi99 @nakul-19 @plazzy99
I am a GSSoC21 participant.

What I want to contribute :

Optimized approach for Subset Sum Algorithm using Dynamic programming
My code will be in C++
The code will be commented for easy understanding, including 2 test cases
Please assign this issue to me.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you .
Thank you .

**Comment by Aarti002** [comment]
hey @plazzy99 can i work on this issue in python under gssoc'21 in the most efficient algorithm possible with explanatory comments to make it easier to understand.
Please assign this to me
Thank you!

**Comment by Vansh-Gupta4** [comment]
thanks for assigning it  to me

**Comment by Aarti002** [comment]
@plazzy99 can you plz merge my PR
Thank you!
