### ISSUE TITLE
Perform operations on Linked list

### ISSUE THREAD

**Issue by nikitajuneja1** [Algo-Phantoms/Algo-Tree#152]
Hi, 
Given a linked list, I will implement the program in C++ or JAVA with proper comments and test cases involving operations like:- - - [ ] Printing the elements 
- [ ] Inserting and deleting the node at the beginning, end, or at nth position
- [ ]  Reverse a linked list
- [ ] Sort a linked list
I am a GSSOC'21 participant and I want to gain a better understanding and implementation of data structures and algorithms. Please assign this issue to me @rudrakshi99

**Comment by apmit2704** [comment]
@nakul-19 @plazzy99 @rudrakshi99 please assign me this issue. I will add 2 test cases in each.

**Comment by yashikajotwani12** [comment]
please assign me this issue in python or c++. i will implement it in proper ways.

**Comment by yogitasaini** [comment]
please assign this task to me in java under GSSOC'21

**Comment by lucifer2502** [comment]
Hello , I am a GSOCC21 participant & would like to contribute to this issue. 
MY code will be in C++ with proper comments explanation and best complexity.

**Comment by plazzy99** [comment]
> Hi,
> Given a linked list, I will implement the program in C++ or JAVA with proper comments and test cases involving operations like:- - - [ ] Printing the elements
> 
> * [ ]  Inserting and deleting the node at the beginning, end, or at nth position
> * [ ]   Reverse a linked list
> * [ ]  Sort a linked list
>   I am a GSSOC'21 participant and I want to gain a better understanding and implementation of data structures and algorithms. Please assign this issue to me @rudrakshi99

go ahead with java

**Comment by plazzy99** [comment]
> please assign me this issue in python or c++. i will implement it in proper ways.

go with python

**Comment by plazzy99** [comment]
> please assign this task to me in java under GSSOC'21

assigned java

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by himali08** [comment]
hey I am a GSSOC 2021 participant and I am looking forward to work on this

**Comment by khushi123456789** [comment]
I am  GSSOC'2021 participant. I am good at C++,C.Please assign this issue to me.
 Thankyou!

**Comment by Swetha126** [comment]
I am a GSSOC'21 participant.
I am looking forward to working on C and C++ in this project

**Comment by AasthaGoyalgit** [comment]
Hey!!

I am interested in this issue in java as a GSSOC'21 participant .
I'll be glad to work on this issue.

Thanks!!

**Comment by neha030** [comment]
I am GSSOC'2021 participant. I want to work on this issue.
I can provide a C++ code with proper indentation ,comments and description.
1.deletion  from end, beginning ,any position.
2.sort a linked list.
3.add new node  from end, beginning ,any position.
4.count no. of nodes.
5.reverse a linked list.

**Comment by kushal13112001** [comment]
I am GSSOC'2021 participant. I want to work on this issue.
I can provide a Python code with proper indentation ,comments and description.
1.deletion from end, beginning ,any position.
2.sort a linked list.
3.add new node from end, beginning ,any position.
4.count no. of nodes.
5.reverse a linked list.

**Comment by Himani-D** [comment]
I am GSSOC'2021 participant. I want to work on this issue. Please assign me.

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Perform operations on Linked list

i can implement this much operations in linked list 

1. INSERT AT FRONT   
2. INSERT AT LOCATION (INSERT BEFORE DATA , INSERT AFTER DATA )
3. INSERT AT END     
4. DELETE AT FRONT   
5. DELETE AT LOCATION (DELETE BEFORE DATA , DELETE AFTER DATA )
6. DELETE AT END     
7. SEARCH
8. SWAP NODES'S DATA 
9.  REVERSE LL   
10. LENGTH
11. FIND MID 

i will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.

so i would like @rudrakshi99 , @nakul-19  , @plazzy99  to please assign this Issue to me :)
