### ISSUE TITLE
Print Right View of a Binary Tree

### ISSUE THREAD

**Issue by AmanBisht01** [Algo-Phantoms/Algo-Tree#1530]
Given a Binary Tree, print Right view of it. Right view of a Binary Tree is set of nodes visible when tree is visited from Right side.

The right view of following tree is 1 3 7 
          1\
       /     \\
     2        3\
   /   \     /  \\
  4     5   6    7
           
I would like to work on this issue under gssoc in c++ language.

**Algo-Tree/Code/C++/**

**Comment by purohitmansi** [comment]
Please assign this to me.
