### ISSUE TITLE
Selection Sort and Bubble Sort

### ISSUE THREAD

**Issue by apmit2704** [Algo-Phantoms/Algo-Tree#154]
Hi,
I am GSSOC'21 participant

Here's what I want to add in the repo:
  - Selection Sort Algorithm
  - Bubble Sort Algorithm
  
My code will be in C++ with proper comment and 2 test cases.
Please assign me this issue.
Happy contributing:)

**Comment by apmit2704** [comment]
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by plazzy99** [comment]
The above issue has been already raised
