### ISSUE TITLE
 Bubble Sort Algorithm 

### ISSUE THREAD

**Issue by PritomDutta89** [Algo-Phantoms/Algo-Tree#1543]
**Is your feature request related to a problem? Please describe.**
 Bubble Sort Algorithm 

**Describe the solution you'd like**
In this sorting algorithm 1st compared adjacent elements, if elements are in wrong order then swapped to make it correct sequence.

**Do you want to work on it**
I would like to implement this in C++

**Comment by khusheekapoor** [comment]
Hello! I would like to work on this using Java under GSSoC'21. Could you please assign it to me?

**Comment by Poojasingh5** [comment]
Hello!
I am a GSSoC'21 participant.
I would like to contribute the code for this issue in  cpp and python both.
Kindly assign it to me.

**Comment by PritomDutta89** [comment]
Please assign it to me. ( GSSOC 21)

**Comment by dchhavi** [comment]
I have a great understanding of bubble sort algorithm. I would love to work on this!!

**Comment by Himanshi2997** [comment]
Hello,
I would like to work on this issue. I can code bubble sort in python and C++ .I am a participant of GSSoC'21 .
Will you please assign this issue to me @raksha009 @tarun26091999

**Comment by madhvi02** [comment]
I am a gssoc'21 participant.
I would like to contribute to this problem in C++.
please assign this to me.
I will surely provide you with the commented code.
@plazzy99 @rudrakshi99 @nakul-19 @tarun26091999 @shreyanspoddar @raksha009 @anjul2000 @OjusWiZard

**Comment by purohitmansi** [comment]
Please assign this to me.
