### ISSUE TITLE
Transpose of a matrix(2D array)

### ISSUE THREAD

**Issue by apmit2704** [Algo-Phantoms/Algo-Tree#155]
Hi,
I am GSSOC'21 participant

Here's what I want to add to this amazing repo:
 -Given a 2D array, find its transpose

My code will be in C++ with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by yashikajotwani12** [comment]
I would love to code it in python , with proper implementation and theory , please assign me this issue.@plazzy99

**Comment by vedant-jain03** [comment]
I can add Transpose of matrix in java 
Please assign me this issue so that I can go further on this.
@plazzy99

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

Here's what I want to add to this amazing repo:
-Given a 2D array, find its transpose

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue for JAVA

**Comment by deepthiteki** [comment]
Hi @plazzy99 ,
I would like to contribute to this issue under GSSOC'21
I can implement it in C++, Java and Python.
Kindly, assign this to me so that I can start working on this

**Comment by Vansh-Gupta4** [comment]
i like to contribute to this project ...my code will be in java with proper comments and test cases

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.
