### ISSUE TITLE
Matrix Multiplication

### ISSUE THREAD

**Issue by apmit2704** [Algo-Phantoms/Algo-Tree#156]
Hi,
I am a GSSOC'21 participant.

I want to add matrix multiplication in the Number Theory folder under Algorithms.
My code will be in C++ with proper comments and test cases.
@nakul-19 @rudrakshi99 @plazzy99 please assign me this issue.

**Comment by vedant-jain03** [comment]
I know the basics of Matrix and I am also have knowledge of DSA using C++ language.
Please assign me this issue so that I can work further on this @nakul-19 @rudrakshi99 @plazzy99 
I am also GSSOC 2021 participant

**Comment by krishna-NIT** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by Amit366** [comment]
I want to solve this issue using C..
Please assign this issue to me under GSSOC 21 ,using C language.
 @nakul-19 @rudrakshi99 @plazzy99

**Comment by yogitasaini** [comment]
please assign this task to me in java under GSSOC'21

**Comment by ankitasantape** [comment]
Kindly assign this issue to me I would like to implement it under GSSOC 2021 using java.

**Comment by iamvs-2002** [comment]
Kindly assign the issue to me. 
I'll implement the same in time complexity lesser than O(n^3).

**Comment by sakshi2707** [comment]
Hi,
I am a GSSOC'21 participant.

I want to add matrix multiplication in the Number Theory folder under Algorithms.
My code will be in C++/JAVA with proper comments and test cases.
@nakul-19 @rudrakshi99 @plazzy99 please assign me this issue.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by tarun26091999** [comment]
issue already present #86
