### ISSUE TITLE
Implementation of Stack using Linked List [Python]

### ISSUE THREAD

**Issue by noviicee** [Algo-Phantoms/Algo-Tree#1562]
**Is your feature request related to a problem? Please describe.**
I will add the program to implement stack considering all the main methods along with some other methods also with the help of linked lists in Python.

**Do you want to work on it**
Yes!

**Languages used**
Python

**Participant of GSSOC'21**

**Comment by Himanshi2997** [comment]
Is your feature request related to a problem ? Please describe.
I have already done this program in C++. I can do the same in Python.

Describe the solution you'd like.
I will make different functions for checking if the stack is empty or full and to perform push, pop operations and for displaying the stack. 

Do you want to work on it?
I would like to contribute to this issue

I am a participant of GSSoC'21.
Will you please assign this issue to me @raksha009 @tarun26091999

**Comment by Rajashri14** [comment]
I want to work on this issue. Please assign this issue to me.
