### ISSUE TITLE
Checking if a number is a prime number or not

### ISSUE THREAD

**Issue by soukarsha122** [Algo-Phantoms/Algo-Tree#157]
Hello @nakul-19  @rudrakshi99 @plazzy99 
I am a GSSOC '21 participant. 

I wish to contribute a C++ code for the following problem:
Find if a number is a prime number or not.

My code will have comment lines to make it explanatory and understandable to everyone. 
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by maanpatel2492** [comment]
I would like to work on this issue.
(under GSSOC21)

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by Amit366** [comment]
Hi,
I am GSSOC'21 participant

I will code in C.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by yogitasaini** [comment]
please assign this task to me in java under GSSOC'21

**Comment by lucifer2502** [comment]
Hello , I am a GSOCC21 participant & would like to contribute to this issue. 
MY code will be in C++ with proper comments explanation and best complexity.

**Comment by rudrakshi99** [comment]
> Hello @nakul-19 @rudrakshi99 @plazzy99
> I am a GSSOC '21 participant.
> 
> I wish to contribute a C++ code for the following problem:
> Find if a number is a prime number or not.
> 
> My code will have comment lines to make it explanatory and understandable to everyone.
> I will be very happy if I am assigned this issue and allowed to work on this.

This code is already present in our repo.

**Comment by anushka00** [comment]
Hi, I am a gssoc'21 participant and want to contribute in this  great project. I'll write the code  in compliance to all the noted guidelines with proper comments .  I will write the code in C++ with proper comments. Looking forward to work on this issue.

**Comment by yashika03** [comment]
I am a GSSOC'21 participant and would like to contribute a C++ code for this issue. Please assign this issue to me.

**Comment by khushi123456789** [comment]
I am  GSSOC'2021 participant. I am good at C++,C.Please assign this issue to me.
 Thankyou!

**Comment by himali08** [comment]
hey I am a GSSOC'21 participant and I am looking forward to work on this in C and C ++.

**Comment by kushal13112001** [comment]
Hey, I am a GSSOC'21 participant. I would like to contribute the code of this problem statement in PYTHON language. Please assign this issue to me.

**Comment by ShrutiKhatri826** [comment]
I wish to contribute to this issue with proper comments, clear explanation and proper indentation resulting in a clean code. My code will be in C++. Please assign me this issue, Hope to hear from you soon @rudrakshi99

**Comment by MaitriDA** [comment]
Hey..
I am GSSOC'21 Participant. I am good at C++, I would like to contribute to the problem. Please assign this issue to me. I will explain the code using proper comments and also provide some examples

**Comment by RYzen-009** [comment]
hello sir,
I am Tanmay Mathur-a GSSOC'21 participant.
I would like to contribute to this using C++. I will solve this question using sieve of eratosthenes technique with proper comments along with some test cases

**Comment by anjalibanerjee01** [comment]
I am a GSSOC'21 participant and I would like to contribute in this using python with proper code and comments.
Please assign me this.

**Comment by Himani-D** [comment]
I am a GSSOC'21 participant and I would like to contribute in this using python  and java.
Please assign me this.

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Checking if a number is a prime number or not using C++
i will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.

so i would like @rudrakshi99 to please assign this Issue to me :)

**Comment by anushka00** [comment]
Hi i am a **Gssoc'21** participant. Assign me this issue, i will implement ***Sieve of Eratosthenes*** to check prime number validity of a number with proper comments to give idea of the used algorithm. I will write code in c++. @rudrakshi99  assign me this issue.

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. I will be using Java. Thanks!

**Comment by Nishayadav-bit** [comment]
Hey , I'm a GSSOC'21 participant . I would like to work on this issue please assign me .

**Comment by yasharth291** [comment]
closing it as it is merged
