### ISSUE TITLE
Left Rotate Array by d elements 

### ISSUE THREAD

**Issue by RYzen-009** [Algo-Phantoms/Algo-Tree#1596]
Is your feature request related to a problem? Please describe.
A We need to left rotate a given array by d elements 

Describe the solution you'd like
A I would like to solve this problem in C++ with help of  Reversal Algorithm and will also provide a naive approach for better understanding

Do you want to work on it
I want to work on it with C++ as a GSSOC'21 participant.

**Comment by AmitSamui** [comment]
Hey! Can I work on this issue as it seems interesting! And my code will be in java with proper comments and test cases.

**Comment by RYzen-009** [comment]
@AmitSamui I have created this issue and I wanted to work on this issue why did you commited the changes even without my permission.Pls remove this changes as soon as possible because I am working on this issue.
