### ISSUE TITLE
Add Next Permutation into Numerical Folder (Math)

### ISSUE THREAD

**Issue by NEERAJAP2001** [Algo-Phantoms/Algo-Tree#1603]
Implement next permutation, which rearranges numbers into the lexicographically next greater permutation of numbers.
If such an arrangement is not possible, it must rearrange it as the lowest possible order (i.e., sorted in ascending order).
Link : [HERE](https://leetcode.com/problems/next-permutation/)

I'd like to work on this issue as part of GSSOC-21 (I'll work in python)

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.
