### ISSUE TITLE
Kth minimum/maximum element in an array

### ISSUE THREAD

**Issue by apmit2704** [Algo-Phantoms/Algo-Tree#162]
Hi,
I am a GSSOC'21 participant.
I want to add the various solutions of finding the Kth smallest/largest element in an array. A simple and straightforward that everyone probably knows is simple sorting that takes O(N log N) time.  I will discuss the various implementations in linear time complexity.
* My code will be in C++
* I will add proper test cases explaining every approach to the problem

C++
- [ ] Minimum
- [ ] Maximum

Java
- [ ] Minimum
- [ ] Maximum

Python
- [ ] Minimum
- [ ] Maximum

Please assign me this issue @nakul-19 @plazzy99 @rudrakshi99

**Comment by vedant-jain03** [comment]
Hello 
I am GSSOC21 PARTICIPANT
And I can code this issue in C++,python and C along with line comments and best time complexity.
Please assign me this issue.

**Comment by krishna-NIT** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by Amit366** [comment]
Hello
I am GSSOC21 PARTICIPANT

Can I code it using python??

**Comment by shivangi-04** [comment]
Hi, I'm a GSSOC'21 participant.
I would like to contribute to this issue.
My code will be in c++ with comments to make it eay to understand.

**Comment by Radhika025** [comment]
I am a GSSoC participant and would like to contribute to this issue in C++

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by tarun26091999** [comment]
@krishna-NIT @vedant-jain03 @Amit366 raise separate PR for both minimum and maximum, and also implement the most optimized approach only.

**Comment by Nishayadav-bit** [comment]
Hey , I'm a GSSOC'21 participant . I would like to work on this issue please assign me .

**Comment by Amit366** [comment]
@tarun26091999 please review my PRs

**Comment by tarun26091999** [comment]
@Amit366 link your PRs to this issue so that we can see them here.

**Comment by tarun26091999** [comment]
@Vansh-Gupta4 raise separate PR for both minimum and maximum, and also implement the most optimized approach only.
