### ISSUE TITLE
Seive of Eratosthenes

### ISSUE THREAD

**Issue by Op-panda** [Algo-Phantoms/Algo-Tree#1626]
**Is your feature request related to a problem? Please describe.**
It is an algorithm to find prime number between two ranges

**Describe the solution you'd like**
I will be using this algorithm which says mark all non prime and print prime.

**Do you want to work on it**
CPP

**Comment by Op-panda** [comment]
@rudrakshi#2361  @vatsal kesarwani#2606  @Tanyx#7069  @Raksha#9246  @tarun_10#1663  @Nakul#7751  @shrey#7147

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by Simi06** [comment]
**@tarun26091999 @rudrakshi99 @plazzy99 @nakul-19 **, i would like to contribute to the above problem in CPP. am a GSSoC'21 participant. kindly assign this to me.

**Comment by Op-panda** [comment]
@raksha009 @nakul-19
@nakul-19

**Comment by Mugdha-Hazra** [comment]
Hello, @shubhidua @Simi06 @Op-panda @aaadddiii @anubhavitis  I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by tarun26091999** [comment]
present at #47
