### ISSUE TITLE
spiral matrix 

### ISSUE THREAD

**Issue by Op-panda** [Algo-Phantoms/Algo-Tree#1628]
**Is your feature request related to a problem? Please describe.**
In this question, elements of the array are to be printed while travelling through matrix

**Describe the solution you'd like**
I will be using Iterative method 

**Do you want to work on it**
CPP

**Comment by Op-panda** [comment]
@rudrakshi#2361  @vatsal kesarwani#2606  @Tanyx#7069  @Raksha#9246  @tarun_10#1663  @Nakul#7751  @shrey#7147

**Comment by Op-panda** [comment]
@raksha009 @nakul-19
@nakul-19

**Comment by madhvi02** [comment]
I am a gssoc'21 participant.
I would like to contribute to this problem in C++.
please assign this to me.
@plazzy99 @rudrakshi99 @nakul-19 @tarun26091999 @shreyanspoddar @raksha009 @anjul2000 @OjusWiZard

**Comment by Bushra109** [comment]
I am a gssoc'21 participant.
I wish to contribute to this problem in C++.
please assign this to me.
@plazzy99 @rudrakshi99 @nakul-19 @tarun26091999 @shreyanspoddar @raksha009 @anjul2000 @OjusWiZard

**Comment by tanyagupta0201** [comment]
I am a gssoc'21 participant. I would like to contribute to the above code in C++. Please assign this problem to me. Thanks.

**Comment by tanyagupta0201** [comment]
I am a gssoc'21 participant. I would like to contribute to the above code in C++. Please assign this problem to me. Thanks.
@rudrakshi99 @tarun26091999 @nakul-19 @raksha009 @anjul2000 @shreyanspoddar

**Comment by tarun26091999** [comment]
present at #1261
