### ISSUE TITLE
Transpose of a matrix

### ISSUE THREAD

**Issue by nidhivanjare** [Algo-Phantoms/Algo-Tree#1640]
**Is your feature request related to a problem? Please describe.**
I want to write a code to give the transpose of a matrix. 

**Describe the solution you'd like**
Take input of a matrix and will print the transpose of that matrix. 

I will write the code in Java. 

**Do you want to work on it**
I am a GSSOC'21 participant and would like to work on this issue.

**Comment by Himanshi2997** [comment]
Hello,
I would like to work on this issue. I can code in Python, C++ and Java .I am a participant of GSSoC'21 .
Will you please assign this issue to me.

**Comment by Simi06** [comment]
@tarun26091999 @rudrakshi99 @plazzy99 @nakul-19, I would like to contribute to the above problem in CPP. am a GSSoC'21 participant. Kindly assign this to me.

**Comment by nidhivanjare** [comment]
@rudrakshi99 Can I work on this ?

**Comment by parvezahsen** [comment]
Hi there, I would like to work on this issue

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.
