### ISSUE TITLE
Pronic Numbers

### ISSUE THREAD

**Issue by ShrutiOmer** [Algo-Phantoms/Algo-Tree#1650]
**Is your feature request related to a problem? Please describe.**
Want to add program that will print the pronic numbers in given range.
A pronic number is a number which is the product of two consecutive integers, that is, a number of the form n(n + 1). The first few pronic numbers are: 0, 2, 6, 12, 20, 30, 42, 56, etc.

**Do you want to work on it**
Please assign this issue to me, I want to implement in C++ , python

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by Sathwika-02** [comment]
Hi,
I am GSSOC'21 participant,
My code will be in python with proper comments and test cases.
@tarun26091999 @rudrakshi99 Please assign me this. Thankyou!!

**Comment by muskan26062000** [comment]
Please assign this to me in C++.I am a GSSOC'21 participant. @tarun26091999 @rudrakshi99

**Comment by tarun26091999** [comment]
@ShrutiOmer do it in C++.
