### ISSUE TITLE
Jump Search in C++

### ISSUE THREAD

**Issue by ShubhamGupta577** [Algo-Phantoms/Algo-Tree#1651]
## Jump Search
Jump Search is a searching algorithm for sorted arrays. The basic idea is to check fewer elements (than linear search) by jumping ahead by fixed steps or skipping some elements in place of searching all elements.
- **Time complexity- O(sqrt(n))**
- **Space complexity-O(1)**

**Do you want to work on it**
Yes, I want to work on this using C++.

**Comment by ShubhamGupta577** [comment]
@rudrakshi99 , @tarun26091999, Under GSSOC21 I want to work on this issue. Please assign me this issue.

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by tarun26091999** [comment]
issue present at #1024 , you can ask there for assignment.
