### ISSUE TITLE
Printing Longest Common Subsequence using dp

### ISSUE THREAD

**Issue by bitaashna** [Algo-Phantoms/Algo-Tree#166]
An algorithm to print longest common subsequence 
I would like to contribute to it as a GSSoC'21 participant.
My code will be in C++ with proper comments and test cases.
@nakul-19 @rudrakshi99 @plazzy99 please assign me this issue.

**Comment by vedant-jain03** [comment]
Hello
I am GSSOC21 PARTICIPANT
And I can code this issue in C++ along with line comments and best time complexity.
Please assign me this issue.

**Comment by lucifer2502** [comment]
Hello , I am a GSOCC21 participant &  would like to contribute to this issue. MY code will be in C++ with proper comments explanation and best complexity.

**Comment by Amit366** [comment]
Hello
I am GSSOC21 PARTICIPANT

Can I work on this using Java??

**Comment by sg-iitg** [comment]
I am GSSOC'21 participant. I would like to contribute the python solution for this problem statement. Please assign the issue to me. Thankyou!

**Comment by jatinjain29** [comment]
Hello, I am a GSSOC'21 participant and I would like to contribute Java code for the algorithm to find  Longest Common Subsequence. Shall I work on this issue?

**Comment by plazzy99** [comment]
#21 
refer
