### ISSUE TITLE
Red Black Tree

### ISSUE THREAD

**Issue by mehak6569** [Algo-Phantoms/Algo-Tree#1679]
A **red-black tree** is a self-balancing binary search tree where each node has an extra bit, and that bit is often interpreted as the colour (red or black).
It reduces the searching time to O(log n), where n is the total number of elements in the tree. 

I want to implement **Insertion and Deletion** in Red Black Tree using **C++**.

Please assign me this issue.[](url)

**Comment by Mugdha-Hazra** [comment]
Hello, @mehak6569 @aaadddiii @anubhavitis @veenit1802 @ssaksham, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by tarun26091999** [comment]
@mehak2323 make it a user driven code and implement both methods neatly.

**Comment by Tejal18** [comment]
@tarun26091999 @Mugdha-Hazra  I want to contribute to the code. 
I want to code the insertion and deletion in red black tree in **JAVA**.
Please this to me too.
thanks.

**Comment by U-c0de** [comment]
@tarun26091999 @Mugdha-Hazra I want to contribute to the code.
I want to code the  Red Black Tree in Python
Please assign this issue to me .

**Comment by U-c0de** [comment]
@ Rohan27s @rish-singhal 
Assign me this in Python
