### ISSUE TITLE
Peak Element using Binary Search in C++

### ISSUE THREAD

**Issue by bitaashna** [Algo-Phantoms/Algo-Tree#168]
An algo to find peak element
I would like to contribute as a part of GSSoC'21 .
My code will be in C++ with proper comments and test cases.
@nakul-19 @rudrakshi99 @plazzy99 please assign me this issue.

**Comment by vedant-jain03** [comment]
Hello 
I am GSSOC21 PARTICIPANT
And I can code this issue in C++, C along with line comments and best time complexity.
Please assign me this issue.

**Comment by lucifer2502** [comment]
Hello , I am a GSOCC21 participant & would like to contribute to this issue. 
MY code will be in C++ with proper comments explanation and best complexity.

**Comment by DevilAJ** [comment]
I would like to do Java version on this code.
I am a GSSOC '21 participant.
My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by plazzy99** [comment]
> An algo to find peak element
> I would like to contribute as a part of GSSoC'21 .
> My code will be in C++ with proper comments and test cases.
> @nakul-19 @rudrakshi99 @plazzy99 please assign me this issue.

you have been assigned to many issues

**Comment by plazzy99** [comment]
> > An algo to find peak element
> > I would like to contribute as a part of GSSoC'21 .
> > My code will be in C++ with proper comments and test cases.
> > @nakul-19 @rudrakshi99 @plazzy99 please assign me this issue.
> 
> you have been assigned to many issues

After your pr's are merged you will be assigned more

**Comment by DevilAJ** [comment]
If I am the only one assigned, should I work only on Java version or java and c++ both.

**Comment by vedant-jain03** [comment]
@plazzy99 in which lang. I should move ahead?

**Comment by DevilAJ** [comment]
@vedant-jain03 
Bro if you want you can work on java version of this issue.

**Comment by vedant-jain03** [comment]
@DevilAJ Bro actually I havent study java yet
So please if you can do it in java
I will move ahead with cpp

**Comment by DevilAJ** [comment]
@vedant-jain03 
Actually I already implemented it in cpp.
Ok let @plazzy99  decide further.

**Comment by shahina-bano** [comment]
I would like to work on this issue in python. Kindly assign it to me @plazzy99  @tarun26091999
