### ISSUE TITLE
Searching in BST

### ISSUE THREAD

**Issue by Prerna-07** [Algo-Phantoms/Algo-Tree#1682]
**Is your feature request related to a problem? Please describe.**
Searching in BST

**Describe the solution you'd like**
The solution will be done using recursion. If element is less than the present node data then search in left, else search in right. There will be two base cases
i) if node data is equal to desired data return true
ii)If node reached to null return false. 

**Do you want to work on it**
Yes, I am a GSSOC'21 participant I would like to solve it in Java.

**Comment by Prerna-07** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99

**Comment by Rajashri14** [comment]
I want to work on this issue in java. Please assign this issue to me.

**Comment by madhvi02** [comment]
I am a  GSSOC'21 Participant 
@nakul-19 @raksha009 @plazzy99 @tarun26091999 please assign this issue to me . I will provide you with the commented and optimized code.
Language: C++

**Comment by rish-singhal** [comment]
Assigned for java @Prerna-07

**Comment by rish-singhal** [comment]
@madhvi02 the code is already there for C++. Thanks for your interest! :)

**Comment by U-c0de** [comment]
@rish-singhal 
Please assign issue to me  I can code it in Python

**Comment by rish-singhal** [comment]
@U-c0de done
