### ISSUE TITLE
Balanced Bracket Problem

### ISSUE THREAD

**Issue by Prerna-07** [Algo-Phantoms/Algo-Tree#1683]
**Is your feature request related to a problem? Please describe.**
Balanced Bracket Problem
Explanation :- To check if the expression is balanced i.e. closing brackets and opening brackets match up well.

**Describe the solution you'd like**
It will be an iterative solution in which loop will iterate over each character of expression, if opening brackets encountered then simply push in stack, if closing brackets encountered then if stack is empty return false or if top element of stack is not brackets significant other return false. After Iterating whole expression if stack not empty means some opening brackets doesn't have closing hence not balanced. At end if stack is empty means expression is balanced. 

**Do you want to work on it**
Yes, I am a GSSOC'21 participant I would like to solve it in Java.

**Comment by Prerna-07** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99

**Comment by rish-singhal** [comment]
Hey you were not assigned this issue, you need to be assigned first before submittin your PR. As of now I am assigning you, please from next time wait for being assigned first.

**Comment by Prerna-07** [comment]
@rish-singhal  ok sir

**Comment by Srishti013** [comment]
Hi,
I am a GSSOC'21 participant, I would like to solve this in C++. Please assign this issue to me.

**Comment by rish-singhal** [comment]
@Srishti013 assigned you.

**Comment by Srishti013** [comment]
The solution in C++ is already in the repo. Can I solve it in python?

**Comment by rish-singhal** [comment]
@Srishti013 sure
