### ISSUE TITLE
Stock Span Problem

### ISSUE THREAD

**Issue by Prerna-07** [Algo-Phantoms/Algo-Tree#1684]
**Is your feature request related to a problem? Please describe.**
Stock Span Problem
Explanation  : Stock span is defined as the number of days passed between the current day and the first day before today when price was higher than today.

**Describe the solution you'd like**
A simple and concise approach which is implemented using Stack, it is somewhat as finding max on the left.

**Do you want to work on it**
Yes, I am a GSSOC'21 participant I would like to solve it in Java.

**Comment by Prerna-07** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99

**Comment by rish-singhal** [comment]
Done @Prerna-07

**Comment by Prerna-07** [comment]
@rish-singhal  thank you sir

**Comment by rish-singhal** [comment]
@Prerna-07 no need to call me sir :p

**Comment by Srishti013** [comment]
Hi,
I would like to solve this issue in C++. Please assign it to me.

**Comment by U-c0de** [comment]
I am a GSSOC'21 participant, I would like to solve this in Python with proper test cases. Please assign this issue to me.
@rish-singhal  @nakul-19 @raksha009 @plazzy99 @tarun26091999

**Comment by rish-singhal** [comment]
Done
