### ISSUE TITLE
Rearrange array in alternating positive & negative items in extra space O(1) in python 

### ISSUE THREAD

**Issue by soumik2012** [Algo-Phantoms/Algo-Tree#1695]
## 🚀 Feature

Given an array of positive and negative numbers, arrange them in an alternate fashion such that every positive number is followed by negative and vice-versa maintaining the order of appearance. 
A number of positive and negative numbers need not be equal. If there are more positive numbers they appear at the end of the array. If there are more negative numbers, they too appear in the end of the array

### Have you read the Contributing Guidelines on Pull Requests?

Yes, I have read.

## Motivation

To contributing to GSSOC'21

## Pitch

Input:  {1, 2, 3, -4, -1, 4}
Output: {-4, 1, -1, 2, 3, 4}

**Comment by soumik2012** [comment]
@tarun26091999 please assign me this is issue

**Comment by tarun26091999** [comment]
present at #708
