### ISSUE TITLE
Sorting Techniques [GSSOC'21]

### ISSUE THREAD

**Issue by anishsingh42** [Algo-Phantoms/Algo-Tree#1696]
**Bubble Sort:-** 
The simplest sorting algorithm, that works on repeatedly swapping the adjacent elements if in wrong order.
 
**Selection Sort:-**
The algorithm repeatedly find the minimum element of the unsorted part and put in the beginning. There are always two part in selection sort algorithm:-  
1)  The sorted subarray;
2)  The  unsorted subarray.

**Insertion Sort:-**
In insertion sort algorithm , the element from the unsorted array is inserted to its correct position in the sorted array. 

**Bubble Sort :-** 
Time complexity: O(n*n)
Space complexity: O(1)

**Selection Sort:**
Time complexity: O(n*n)
Space complexity: O(1)

**Insertion Sort:**
Time complexity: O(n*n)
Space complexity: O(1)

Language: Python.

Please assign me this issue.
@tarun26091999, @rudrakshi99 

Thank you.

**Comment by Tejal18** [comment]
Hello , @tarun26091999 @rudrakshi99 @plazzy99 I want to contribute to this issue . 
I will write all the codes in JAVA.
Please do assign me this issue.
Thanks.

**Comment by tarun26091999** [comment]
all sorting techniques are already being worked upon.

**Comment by anishsingh42** [comment]
Non till now are added yet. if you allow me I can work upon them.
