### ISSUE TITLE
Block Sum of Matrix

### ISSUE THREAD

**Issue by U-c0de** [Algo-Phantoms/Algo-Tree#1698]
**Is your feature request related to a problem? Please describe.**
Sub matrices sum(in given coordinates value) to form a summation matrix  | Dynamic Programming

**Describe the solution you'd like**
Through coordinates value forming a new matrix which stores sum of submatrices  by using class & objects

**Do you want to work on it**
Assign this issue to me in C++.

**Comment by AdityaRaj-ar** [comment]
I Request you to please assign this issue to me. I really want to work on this issue and I will solve this issue in C++. I would be grateful if you assign this issue to me. Therefore I request you to assign this issue to me.

**Comment by U-c0de** [comment]
@Rohan27s @rish-singhal

Please assign me this issue in C++

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by Rohan27s** [comment]
@shubhidua first solve earlier issues that you are assigned on

**Comment by shubhidua** [comment]
@Rohan27s okay

**Comment by U-c0de** [comment]
@Rohan27s  assign me this

**Comment by U-c0de** [comment]
@plazzy99  Assign me this
