### ISSUE TITLE
Bitwise manipulation 

### ISSUE THREAD

**Issue by ssaumyaa7** [Algo-Phantoms/Algo-Tree#1701]
In bitwise manipulation it is important to describe the topic operator overloading. 

In various tricky programming questions,  the answers and the output vary due to operator overloading. 

So do check on the pull request generated to do the same.

**Comment by rish-singhal** [comment]
Hi you can not work on this issue before you are assigned.

**Comment by rish-singhal** [comment]
@rudrakshi99 Can you look into this?

**Comment by Mugdha-Hazra** [comment]
Hello, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by Rohan27s** [comment]
@ssaumyaa7 Mention the language

**Comment by ssaumyaa7** [comment]
> @ssaumyaa7 Mention the language

I am part of gsoc21 so I created pull request to add the topic Overator Overloading under Bitwise Manipulation in python language.

**Comment by Rohan27s** [comment]
@ssaumyaa7 You can't create a pull request until you are assigned on the issue

**Comment by Rohan27s** [comment]
@ssaumyaa7 Kindly checkout #1153 for the rules to contribute :)

**Comment by ssaumyaa7** [comment]
How and who is assigning issues may I know .. ?

**Comment by Mugdha-Hazra** [comment]
Thank you @Rohan27s sir for assigning me this task!.
sir, can you please explain to me which topics I have to cover for this code? like sir can you please explain the question once?

**Comment by rish-singhal** [comment]
As I can see, the given issue doesn't specify any algorithmic problem to solve.

**Comment by Rohan27s** [comment]
@Mugdha-Hazra Make PR for Bitwise operator overloading

**Comment by Mugdha-Hazra** [comment]
@Rohan27s ok

**Comment by U-c0de** [comment]
@Rohan27s  Please assign me this issue in python

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by muskan26062000** [comment]
Please assign this issue to me in C++
