### ISSUE TITLE
Find Transition Point

### ISSUE THREAD

**Issue by U-c0de** [Algo-Phantoms/Algo-Tree#1702]
Description:
Given a sorted array containing only 0s and 1s, find the transition point.
The transition point is a point where “0” ends and “1” begins.

**Do you want to work on it**
Assign this to me
I want to submit the code in C++

**Comment by Srishti013** [comment]
Hi, 
I can provide the solution of this in python a well as in C++ please assign this to me.

**Comment by Mugdha-Hazra** [comment]
Hello, @aaadddiii @anubhavitis @veenit1802 @ssaksham sir, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by U-c0de** [comment]
@rish-singhal  Please assign me this in C++
