### ISSUE TITLE
Add Selection Sort implemented in Python

### ISSUE THREAD

**Issue by Pushpit07** [Algo-Phantoms/Algo-Tree#1704]
I would like to implement the selection sort algorithm in Python. 
@yasharth291 Can you please assign this to me?

**Comment by Srishti013** [comment]
Hi,
I can do this in python please assign this issue to me.

**Comment by Pushpit07** [comment]
@Rohan27s here

**Comment by yasharth291** [comment]
@Srishti013 sorry first come first serve

**Comment by Mugdha-Hazra** [comment]
Hello, @aaadddiii @anubhavitis @veenit1802 @ssaksham sir, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.
