### ISSUE TITLE
Binary Representation

### ISSUE THREAD

**Issue by U-c0de** [Algo-Phantoms/Algo-Tree#1713]
A binary representation where we will calculate maximum 0's between 1's and vice versa.

**Do you want to work on it**
Assign this to me.
I will code it in C++

**Comment by Srishti013** [comment]
Hi,
I would like to work on this please assign this to me.
I will provide the code in C++

**Comment by Mugdha-Hazra** [comment]
Hello, @aaadddiii @anubhavitis @veenit1802 @ssaksham sir, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by U-c0de** [comment]
@rish-singhal @rudrakshi99 @nakul-19 @Rohan27s 

Please assign me this
