### ISSUE TITLE
Toeplitz Matrix Code.

### ISSUE THREAD

**Issue by Junaid55** [Algo-Phantoms/Algo-Tree#1715]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Do you want to work on it**
Mention the one language you want to be assigned for this issue.

**Comment by Junaid55** [comment]
This issue is related to toeplitz matrix problem.
 A Toeplitz matrix or diagonal-constant matrix, named after Otto Toeplitz, is a matrix in which each descending diagonal from left to right is constant.
Please asign this issue to me I will provide a solution in java.

**Comment by rish-singhal** [comment]
mention the issue number as #issue_number

**Comment by Mugdha-Hazra** [comment]
Hello, @aaadddiii @anubhavitis @veenit1802 @ssaksham sir, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by krishna-NIT** [comment]
already at 1231 so, comment there and close this issue so, that mentors will not be disturbed
