### ISSUE TITLE
Tarjan's algorithm

### ISSUE THREAD

**Issue by jainsras** [Algo-Phantoms/Algo-Tree#1733]
**Is your feature request related to a problem? Please describe.**
It is used to find strongly connected components of a directed graph.

**Describe the solution you'd like**
It involves only one DFS traversal, unlike Kosaraju's algorithm. The DFS search produces a dfs tree and the SCCs form the subtrees of the dfs tree. Then we find the lowlinks for every node.

**Do you want to work on it**
I can code in C++ and Java. Please assign this issue to me. I am a GSSoC participant

**Comment by tarun26091999** [comment]
present at #1296
