### ISSUE TITLE
Trimorphic Number in Java

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1736]
**Is your feature request related to a problem? Please describe.**
The program will check whether the number input by the user is trimorphic or not.

**Describe the solution you'd like**
A number n is a trimorphic number if n^3 ends in n.

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the Number Theory category.

Please assign it to me @rish-singhal @yasharth291 @raksha009 @rudrakshi99 @plazzy99 @OjusWiZard @tarun26091999

**Comment by rish-singhal** [comment]
Done @khusheekapoor

**Comment by khusheekapoor** [comment]
> Done @khusheekapoor

Thank you!

**Comment by Srishti013** [comment]
Hi,
If you also the solution in C++ please assign it to me.

**Comment by U-c0de** [comment]
@rish-singhal @yasharth291 @raksha009 @rudrakshi99 @plazzy99 @OjusWiZard @tarun26091999 @Rohan27s 
Assign this issue to me I can put the code in Python

**Comment by Mugdha-Hazra** [comment]
Hello @aaadddiii @anubhavitis @veenit1802 @ssaksham @malavikarajeshvikraman, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by Rohan27s** [comment]
@Mugdha-Hazra Sorry it is already assigned in every language

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.
