### ISSUE TITLE
Sliding Window Maximum in java

### ISSUE THREAD

**Issue by Prerna-07** [Algo-Phantoms/Algo-Tree#1750]
**Is your feature request related to a problem? Please describe.**
Sliding Window Maximum - Function to find and print the maximum element in every window of size k.

**Describe the solution you'd like**
A simple and concise approach which is implemented using Stack, it is somewhat as finding max on the right.

**Do you want to work on it**
Yes, I am a GSSOC'21 participant I would like to solve it in Java.

**Comment by Prerna-07** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.

**Comment by Mugdha-Hazra** [comment]
Hello @aaadddiii @anubhavitis @veenit1802 @ssaksham @malavikarajeshvikraman @yasharth291, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by rish-singhal** [comment]
@shubhidua java has already been assigned to the first one who asked.

If you want to contribute you can do it in python

**Comment by U-c0de** [comment]
@rish-singhal  I am ready to contribute in Python . please assign this to me

**Comment by rish-singhal** [comment]
@unicode-Ind done

**Comment by U-c0de** [comment]
@rish-singhal  check the pull request

**Comment by Palakgupta0908** [comment]
Please assign this to me in java
