### ISSUE TITLE
Sudoku Solver 

### ISSUE THREAD

**Issue by Akash20x** [Algo-Phantoms/Algo-Tree#176]
I would like to implement the solution to find the sudoku solver in python. 
with proper comments.

please assign me this issue as a part of GSSOC 2021.

**Comment by TanviDeore** [comment]
I would like to work on this issue as a participant in GSSoC'21

**Comment by priyamourya** [comment]
I am GSSOC'21 participant and l would like to work on this problem and would make sure to implement a neat and clean code ,and make it easy to understand using comments.

**Comment by shreyanspoddar** [comment]
> I would like to implement the solution to find the sudoku solver in python.
> with proper comments.
> 
> please assign me this issue as a part of GSSOC 2021.

Go ahead and do it in Python

**Comment by shreyanspoddar** [comment]
> I would like to work on this issue as a participant in GSSoC'21

Can you specify the language you want to work in?

**Comment by shreyanspoddar** [comment]
> I am GSSOC'21 participant and l would like to work on this problem and would make sure to implement a neat and clean code ,and make it easy to understand using comments.

Can you specify the language you want to work in?

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@shreyanspoddar, kindly assign this to me, thank you for your time and consideration !!

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant.
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue
Hope to hear from you.

@shreyanspoddar M], @tarun26091999, SIR PLEASE ASSIGN THIS TO ME
Thank you for your time

**Comment by tk315** [comment]
I would like to do this in JAVA under GSSOC

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by khushboojoshi3** [comment]
Hey, I'm a GSSOC'21 participant. I would like to work on this issue in C++, please assign it to me.

**Comment by Akash20x** [comment]
@shreyanspoddar  Please check my pull request
