### ISSUE TITLE
Geek-onacci Number

### ISSUE THREAD

**Issue by U-c0de** [Algo-Phantoms/Algo-Tree#1764]
**Describe the solution you'd like**
Geek created a random series and given a name geek-onacci series. Given four integers A, B, C, N. A, B, C represents the first three numbers of geek-onacci series. Find the Nth number of the series. The nth number of geek-onacci series is a sum of the last three numbers (summation of N-1th, N-2th, and N-3th geek-onacci numbers)

**Do you want to work on it**
Yes, I want to write the code in C++

**Comment by U-c0de** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal

**Comment by rish-singhal** [comment]
@U-c0de done

**Comment by Mugdha-Hazra** [comment]
Hello @aaadddiii @anubhavitis @veenit1802 @ssaksham @malavikarajeshvikraman @rish-singhal, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in Java

**Comment by Srishti013** [comment]
Hi,
I am a GSSOC'21 participant, I would like to solve this issue in python. Please assign it to me.

**Comment by khusheekapoor** [comment]
Hello. I would like to work on this using java. Please assign it to me. Thanks!

**Comment by Rohan27s** [comment]
@Srishti013 @khusheekapoor done

**Comment by khusheekapoor** [comment]
> @Srishti013 @khusheekapoor done

Thank you @Rohan27s !
