### ISSUE TITLE
Jump Game

### ISSUE THREAD

**Issue by vanshikachokhani** [Algo-Phantoms/Algo-Tree#177]
What I want to contribute:
1.Find the minimum number of jumps to reach the end of array if each element in the array represents the maximum jump length at that position assuming that it is always possible to reach the end of array.Initially we are positioned to start index of the array.
2.My code will be in C++.
3. The code will consist of complete explanation of my approach and will be commented for better understanding.
4. Also it will include some test cases.  

@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue under GSSoC21

**Comment by Amanduttbhagat** [comment]
Hello,
I am a GSSoC 2021 Participant and would like contribute to Jump Game in Java
kindly assign me the issue

**Comment by plazzy99** [comment]
> What I want to contribute:
> 1.Find the minimum number of jumps to reach the end of array if each element in the array represents the maximum jump length at that position assuming that it is always possible to reach the end of array.Initially we are positioned to start index of the array.
> 2.My code will be in C++.
> 3. The code will consist of complete explanation of my approach and will be commented for better understanding.
> 4. Also it will include some test cases.
> 
> @rudrakshi99 @nakul-19 @plazzy99 please assign me this issue under GSSoC21

make sure point 3 is meet

**Comment by sg-iitg** [comment]
I am a GSSOC'21 participant. I would like to contribute the python code for this problem statement. I will make sure the code is easily understandable and commented properly.  Please assign this issue to me. Thankyou!

**Comment by Adrenalinerush07** [comment]
I am a GSSoC'21 participant.
I assure you I can handle this issue as I am extremely good at DSA, problem-solving, and C++.

It would be really great if you assign this issue to me.
Hoping for a good outcome from your side.

**Comment by khushi123456789** [comment]
I am  GSSOC'2021 participant. I am good at C++,C.Please assign this issue to me.
 Thankyou!

**Comment by Naman-12911** [comment]
I am a participant of GSSOS  please assign me this issue I can solve it easily .
I am a cpp programer.

**Comment by abhishek-iiit** [comment]
As a GSSOC21 participant,
Can, i too work on this issue @plazzy99  ?
If so,can you please assign me this issue...

**Comment by Amanduttbhagat** [comment]
Hello @plazzy99,
I did made the Pull Request 2 days back ( #628 )
Can you please review it
Thanks,
