### ISSUE TITLE
Applications of Stack

### ISSUE THREAD

**Issue by aish2002** [Algo-Phantoms/Algo-Tree#179]
Hi, I am a GSSOC'21 Participant .I can implement the following **Applications of Stack** in C++, Java and Python.

1. Expression evaluation.(Postfix, Infix and Prefix) 
2. Check parenthesis matching in an expression.   
3. Conversion of one form of expression to another.

Kindly assign this issue to me.

**Comment by Vansh-Gupta4** [comment]
i like to contribute to this project ...my code will be in java with proper comments and test cases

**Comment by varshakr1298** [comment]
I would like to contribute applications of stack in C++
Infix to Postfix
Evaluation of Postfix expression
Creating expression tree
Balancing symbols

**Comment by Radhika025** [comment]
As a GSSoC participant, I would like to contribute and implement different applications of stack in C++

**Comment by ShrutiKhatri826** [comment]
I wish to contribute to this issue with proper comments, clear explanation and proper indentation resulting in a clean code. My code will be in C++. Please assign me this issue, Hope to hear from you soon!

**Comment by tarun26091999** [comment]
cannot solve multiple problems in single issue.
