### ISSUE TITLE
Factorial, Fibonacci, BFS, DFS and many more in java

### ISSUE THREAD

**Issue by Ayan-10** [Algo-Phantoms/Algo-Tree#18]
I can write existing C++ code in Java. Please assign me.

**Comment by RuchiGitHu** [comment]
Good Evening,
Please let me know little more about this issue and send me a link of github repo for this link.
I also want to add java code in array folder....

**Comment by sunidhi1999-c** [comment]
I have been selected for GSSOC'21, and I am really interested in Algorithms , so I would like to contribute in this amazing repository.I can contribute for this ,I am 2 star codechef candidate and would be great to contribute to open source programs like this one. I can write these articles if given a chance.
Thanks.
Sunidhi,
3rd year,CSE at NMAMIT,Nitte,Karnatak

**Comment by yogitasaini** [comment]
Please assign this task to me java under GSSOC'21

**Comment by RuchiGitHu** [comment]
Hi @rudrakshi99. Please assign this issue for solving Factorial and fibonacci code in java.
I am looking forward to contribute here...
Thanks in advance.

**Comment by ankitasantape** [comment]
Kindly assign this issue to me I would like to implement it under GSSOC 2021 using java.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by rudrakshi99** [comment]
@Ayan-10 Please make separate issues for each algorithm.
