### ISSUE TITLE
prefix to postfix

### ISSUE THREAD

**Issue by aaadddiii** [Algo-Phantoms/Algo-Tree#1819]
**Is your feature request related to a problem? Please describe.**

prefix to postfix in c++

**Describe the solution you'd like**
prefix to postfix is a classic problem in data structures, It is also an application of stack

**Do you want to work on it**
I would like to implement this in C++.
Please assign me this issue as part of GSSOC `21

**Comment by aaadddiii** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal

**Comment by U-c0de** [comment]
Please assign it to me in JAVA . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal

**Comment by Anushka0483** [comment]
i would like to work on this in python. please assign this to me @rish-singhal @aaadddiii @Srishti013 .

**Comment by aman7100** [comment]
i would like to work on it in C++.Please assign it to me @rish-singhal .

**Comment by muskan26062000** [comment]
Please assign this issue to me in C++
