### ISSUE TITLE
painting fence problem 

### ISSUE THREAD

**Issue by aaadddiii** [Algo-Phantoms/Algo-Tree#1820]
**Is your feature request related to a problem? Please describe.**
problem statement :
Given a fence with n posts and k colors, find out the number of ways of painting the fence such that at most 2 adjacent posts have the same color. 

**Describe the solution you'd like**
This is a classic problem in dynamic programming

**Do you want to work on it**
I would like to implement this in c++  
Please assign me this issue as part of GSSOC '21

**Comment by aaadddiii** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal

**Comment by U-c0de** [comment]
Please assign it to me in Python . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal

**Comment by Srishti013** [comment]
Please assign this to me in Java.

**Comment by U-c0de** [comment]
Please assign it to me in Python . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal
