### ISSUE TITLE
Largest BST Subtree in Java

### ISSUE THREAD

**Issue by Prerna-07** [Algo-Phantoms/Algo-Tree#1824]
**Is your feature request related to a problem? Please describe.**
Function to find the root of largest sub-tree which is a BST. Also, find the number of nodes in that sub-tree.

**Describe the solution you'd like**
A simple and concise approach which is implemented using class which will help in solving the problem.

**Do you want to work on it**
Yes, I am a GSSOC'21 participant I would like to solve it in Java.

**Comment by Prerna-07** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99

**Comment by Srishti013** [comment]
Please assign this to me in C++.
