### ISSUE TITLE
Stack To Queue Adapter in Java

### ISSUE THREAD

**Issue by Prerna-07** [Algo-Phantoms/Algo-Tree#1826]
**Is your feature request related to a problem? Please describe.**
The class should mimic the behaviour of a Queue and implement FIFO semantic.

**Describe the solution you'd like**

list of functions that are written in the class :
 1. add -> Accepts new data if there is space available in the underlying array or  print "Queue overflow" otherwise.
 2. remove -> Removes and returns value according to FIFO, if available or print  "Queue underflow" otherwise and return -1
 3. peek -> Returns value according to FIFO, if available or print "Queue underflow" otherwise and return -1.
 4. size -> Returns the number of elements available in the queue.

**Do you want to work on it**
Yes, I am a GSSOC'21 participant I would like to solve it in Java.

**Comment by Prerna-07** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99

**Comment by Prerna-07** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99

**Comment by Srishti013** [comment]
Please assign this to me in C++.

**Comment by Bhumika2409** [comment]
Please assign this to me in C language
