### ISSUE TITLE
Threaded Binary tree in Python

### ISSUE THREAD

**Issue by Maskgirl** [Algo-Phantoms/Algo-Tree#1839]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I would like to give the algorithm of the threaded binary tree 

**Describe the solution you'd like**
I have seen threaded binary tree algorithm is available only for C++ language that's why I want to explain it in python 

**Do you want to work on it**
Mention the one language you want to be assigned for this issue.
Yes I want to work on it in python language.Please assign me this issue as part of GSSOC '21

**Comment by Srishti013** [comment]
Please assign this to me in C++.

**Comment by tarun26091999** [comment]
issue is present at #232 you can ask there.
