### ISSUE TITLE
Unique Number in Java

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1840]
**Is your feature request related to a problem? Please describe.**
The program will check whether the number input by the user is unique or not.

**Describe the solution you'd like**
A Unique Number is the difference between a number formed of n consecutive digits and its reverse.

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the Number Theory category.

@rish-singhal please assign it to me. Thanks!

**Comment by Srishti013** [comment]
Please assign this to me in C++.

**Comment by plazzy99** [comment]
Not a valid issue
