### ISSUE TITLE
Knights Tour Problem 

### ISSUE THREAD

**Issue by Prerna-07** [Algo-Phantoms/Algo-Tree#1849]
**Is your feature request related to a problem? Please describe.**
Function to calculate and  print all configurations of the chess board representing the route of knight through the chess board.

**Describe the solution you'd like**
A clear and concise Solution using backtracking .

**Do you want to work on it**
Yes, I am a GSSOC'21 participant I would like to solve it in Java.

**Comment by Prerna-07** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99

**Comment by rohitsigar** [comment]
Please assign it to me. @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99, I am a GSSOC'21 participant I would like to solve it in C++

**Comment by Srishti013** [comment]
Please assign this to me in Python

**Comment by subhangi2731** [comment]
@tarun26091999 can u please assign me
