### ISSUE TITLE
Heap Sort in Java

### ISSUE THREAD

**Issue by ireneelizabethsabu** [Algo-Phantoms/Algo-Tree#185]
Hi,
I am a GSSOC'21 participant. I would like to contribute the heap sort algorithm in java.
Kindly assign this issue to me.

**Comment by ankitasantape** [comment]
Kindly assign this problem to me I would like to implement it under GSSOC 2021 using java

**Comment by Vansh-Gupta4** [comment]
i like to contribute to this project ...my code will be in java with proper comments and test cases

**Comment by Alleny244** [comment]
Hello
I am a GSSOC'21 participant
I would like to contribute in this issue
I can implement this  in java and with proper comment for better understanding.
I will also add 2-3 testcases for better understanding

**Comment by Suvraneel** [comment]
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me this issue under GSSOC '21.

**Comment by shreyanspoddar** [comment]
All the sorting algorithms are being worked on in the issue no #124 . You can ask there if any algorithm is missing.
