### ISSUE TITLE
Merge K Sorted Lists using Heap in Java

### ISSUE THREAD

**Issue by Prerna-07** [Algo-Phantoms/Algo-Tree#1850]
**Is your feature request related to a problem? Please describe.**
The function is expected to merge k sorted lists to create one sorted list.

**Describe the solution you'd like**
A clear and concise Solution implemented using Priority Queue 

**Do you want to work on it**
Yes, I am a GSSOC'21 participant I would like to solve it in Java.

**Comment by Prerna-07** [comment]
Please assign it to me . @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99

**Comment by rohitsigar** [comment]
Please assign it to me. @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99 , I am a GSSOC'21 participant I would like to solve it in C++

**Comment by tarun26091999** [comment]
issue present at #1834 you can ask there
