### ISSUE TITLE
Abbreviation of a person’s name.

### ISSUE THREAD

**Issue by Myself-Rohit-Dey** [Algo-Phantoms/Algo-Tree#1860]
**Is your feature request related to a problem? Please describe.**
I want to add a program to show the abbreviation of a name.

**Describe the solution you'd like**
Input: Avul Pakir Jainulabdeen Abdul Kalam
Output: A.P.J.A.K

**Do you want to work on it**
I would like to implement this in c++
Please assign me this issue as part of GSSOC '21.

**Comment by Myself-Rohit-Dey** [comment]
Please assign it to me. @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal. and also suggest me to which directory to put it in.

**Comment by Srishti013** [comment]
Please assign this to me in Python

**Comment by tarun26091999** [comment]
this is not any standard algorithm. It's just a string manipulation question.
