### ISSUE TITLE
Fermat Number in Java

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1887]
**Is your feature request related to a problem? Please describe.**
A fermat number can be defined by the formula - 2^2^k +1

**Describe the solution you'd like**
This program gives the user the first n fermat numbers.

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the Number Theory category.

**Comment by plazzy99** [comment]
Not a valid issue

**Comment by khusheekapoor** [comment]
> Not a valid issue

@plazzy99 why is it not a valid issue?
