### ISSUE TITLE
Add Sorting Algorithms in C

### ISSUE THREAD

**Issue by iamvs-2002** [Algo-Phantoms/Algo-Tree#190]
Kindly allow me to add various sorting algorithms such as:
Bucket Sort
Merge Sort
Quick Sort
Insertion Sort
Selection Sort
etc.
in C language.

**Comment by tarun26091999** [comment]
> Kindly allow me to add various sorting algorithms such as:
> Bucket Sort
> Merge Sort
> Quick Sort
> Insertion Sort
> Selection Sort
> etc.
> in C language.

our organization doesn't allow C language. Go through the guidelines once.

**Comment by iamvs-2002** [comment]
> > Kindly allow me to add various sorting algorithms such as:
> > Bucket Sort
> > Merge Sort
> > Quick Sort
> > Insertion Sort
> > Selection Sort
> > etc.
> > in C language.
> 
> our organization doesn't allow C language. Go through the guidelines once.

Ohh okay.
