### ISSUE TITLE
Happy Number in Java

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1900]
**Is your feature request related to a problem? Please describe.**
This program checks whether a given number is a happy number or not.

**Describe the solution you'd like**
A happy number is a number which eventually reaches 1 when replaced by the sum of the square of each digit.

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the Number Theory category.

**Comment by 20394ViraM** [comment]
Hi, You can assign it to me. I have already written this program on leet.

**Comment by plazzy99** [comment]
Not a valid issue
