### ISSUE TITLE
N Queens

### ISSUE THREAD

**Issue by siddharth-bhatnagar** [Algo-Phantoms/Algo-Tree#1907]
**Is your feature request related to a problem? Please describe.**
> An Algorithm that places N number of queens on a N*N chessboard such that no queen can kill another.

**Describe the solution you'd like**
> A function that prints all safe configurations of N-Queens.
> Time complexity: O(N!)

**Do you want to work on it**
Yes, I am a GSSOC'21 participant. I will implement the algorithm in Java.

Please assign this to me @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99

**Comment by U-c0de** [comment]
Please assign this to me in  python @Rohan27s @yasharth291 @rish-singhal

**Comment by tarun26091999** [comment]
#491
