### ISSUE TITLE
Deletion in a linked list

### ISSUE THREAD

**Issue by dhruvinfo28** [Algo-Phantoms/Algo-Tree#191]
Would like to contribute in the C++ codebase by adding an algorithm for deletion in a singly linked list under GSSOC2021.
Please assign me.

**Comment by Vansh-Gupta4** [comment]
i like to contribute to this project ...my code will be in java with proper comments and test cases

**Comment by srishti-13** [comment]
Hello.....I would like to contribute to this issue as a part of GSSoC 2021. Could you please assign this to me? I would implement this in C++ and will cover all the Cases.

**Comment by shruti012002** [comment]
Hello.....I would like to contribute to this issue as a part of GSSoC 2021. Could you please assign this to me? I would do this in C++ and fulfill all the necessary requirements.

**Comment by Radhika025** [comment]
I would like to work on this issue as a part of GSSoC 2021 and would like to contribute to this issue using C++.

**Comment by arnab031** [comment]
I would like to solve this issue as a part of GSSoC 2021 in python. I would be thankful to you if you please assign me this issue.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.
