### ISSUE TITLE
Evil Number in Java

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1911]
**Is your feature request related to a problem? Please describe.**
This program checks whether a given number is an evil number or not.

**Describe the solution you'd like**
An evil number is a non-negative number that has an even number of 1s in its binary expansion.

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the Number Theory category.

**Comment by Srishti013** [comment]
Please assign this to me in C++

**Comment by U-c0de** [comment]
Please assign this to me in python

**Comment by plazzy99** [comment]
Not a valid issue
