### ISSUE TITLE
Harshad or Niven number in Java

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1916]
**Is your feature request related to a problem? Please describe.**
This program checks whether a given number is a harshad/ niven number or not.

**Describe the solution you'd like**
Harshad/ Niven Number is an integer that is divisible by the sum of its digits.

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the Number Theory category.

**Comment by Srishti013** [comment]
Please assign this to me in C++.

**Comment by U-c0de** [comment]
Please assign this to me in python

**Comment by plazzy99** [comment]
Not a valid issue
