### ISSUE TITLE
Smith Number in Java

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1924]
**Is your feature request related to a problem? Please describe.**
This program checks whether a given number is a smith number or not.

**Describe the solution you'd like**
A smith number is a composite number, the sum of whose digits is the sum of the digits of its prime factors obtained as a result of prime factorization (excluding 1).

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the Number Theory category.

**Comment by Srishti013** [comment]
Please assign this to me in C++

**Comment by saniaarora15** [comment]
Please assign it to me in python. I am a gssoc participant.
