### ISSUE TITLE
DNF Sort (Dutch National Flag)

### ISSUE THREAD

**Issue by tanyagupta0201** [Algo-Phantoms/Algo-Tree#1926]
DNF sort is used to sort an array of 0, 1, and 2's in linear time that does not consume any extra space.

I would like to contribute its code in C++.
Kindly assign this problem to me.
@rudrakshi99 @tarun26091999 @plazzy99  @nakul-19 @raksha009 @anjul2000

**Comment by siddharth-bhatnagar** [comment]
Please assign this to me in Java @rudrakshi99 @tarun26091999 @plazzy99 @nakul-19 @raksha009 @anjul2000 @Rohan27s

**Comment by Srishti013** [comment]
Please assign this to me in Python

**Comment by tarun26091999** [comment]
present at #877 you can ask there
