### ISSUE TITLE
M-coloring problem

### ISSUE THREAD

**Issue by vanshikachokhani** [Algo-Phantoms/Algo-Tree#1927]
**Is your feature request related to a problem? Please describe.**
If we are given a undirected graph and an integer M. The task is to determine that the graph can be coloured with at most M colors such that no two adjacent vertices of the graph are colored with same color.

**Describe the solution you'd like**
I will use a backtarcking approach to solve the problem.

**Do you want to work on it**
I am a Gssoc 21 participant and I will give the solution in C++.

Please assign this to me. @nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99

**Comment by Bhumika2409** [comment]
Please assign this to me in java

**Comment by Srishti013** [comment]
Please assign this to me in Python

**Comment by vanshikachokhani** [comment]
@tarun26091999 Please assign this issue to me in C++.
