### ISSUE TITLE
Pig Latin Convertor in Java

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1929]
**Is your feature request related to a problem? Please describe.**
The program will convert all the words in a string to pig latin.

**Describe the solution you'd like**
In Pig Latin -
words starting with consonant - take the consonant cluster and move it to the end of the word, adding the suffix - 'ay'.
words starting with vowel - add the suffix 'hey' to the word

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the String category.

**Comment by Srishti013** [comment]
Please assign this to me in C++
