### ISSUE TITLE
Matrix multiplication in cpp

### ISSUE THREAD

**Issue by Sakshi1007** [Algo-Phantoms/Algo-Tree#1930]
**Is your feature request related to a problem? Please describe.**
It is problem of backtracking. 

**Describe the solution you'd like**
In this problem, instead of focusing on how to multiply two matrix. We find that how many steps will be required to calculate multiplication of the matrices. 

**Do you want to work on it**
Yes, i want to work on this problem in c language.

**Comment by Srishti013** [comment]
Please assign this to me in Python

**Comment by muskan26062000** [comment]
Please assign this to me in C++.I am a GSSOC'21 participant.

**Comment by purohitmansi** [comment]
Please do assign this to me.
