### ISSUE TITLE
Dudeney Number in Java

### ISSUE THREAD

**Issue by khusheekapoor** [Algo-Phantoms/Algo-Tree#1934]
**Is your feature request related to a problem? Please describe.**
This program will check whether the number input is a dudeney number or not.

**Describe the solution you'd like**
A Dudeney number is a positive integer that is a perfect cube such that the sum of its digits is equal to the cube root of the number.

**Do you want to work on it**
I would like to work on this issue using Java as a GSSoC'21 participant under the Number Theory category.

**Comment by Bhumika2409** [comment]
Please assign this to me in C++

**Comment by Srishti013** [comment]
Please assign this to me in Python

**Comment by plazzy99** [comment]
Not a valid issue
