### ISSUE TITLE
Pancake Sort 

### ISSUE THREAD

**Issue by Bhumika2409** [Algo-Phantoms/Algo-Tree#1935]
**Is your feature request related to a problem? Please describe.**
It's a good solution to solve the mathematical problems. It is an important sorting technique using flip operation 
analogous to flipping pancakes.
**Do you want to work on it**
Yes, I want to work on it in C++

**Comment by Bhumika2409** [comment]
@plazzy99 @rudrakshi99 @nakul-19 @raksha009 @rish-singhal @Rohan27s @yasharth291 please assign this issue to me

**Comment by Srishti013** [comment]
Please assign this to me in Python

**Comment by tarun26091999** [comment]
#1059
