### ISSUE TITLE
First fit best fit and worst  fit algorithm

### ISSUE THREAD

**Issue by aaadddiii** [Algo-Phantoms/Algo-Tree#1959]
**Is your feature request related to a problem? Please describe.**
First fit best fit and worst  fit algorithm
**Describe the solution you'd like**
I would like to implement this in java python and cpp

**Do you want to work on it**
I would like to implement this in C++,python and java
Please assign me this issue as part of GSSOC `21

**Comment by muskan26062000** [comment]
Please assign this to me in C++.I am a GSSOC'21 participant
