### ISSUE TITLE
Rotation of an array in anticlockwise direction 90 degrees.

### ISSUE THREAD

**Issue by Pranjal9999999** [Algo-Phantoms/Algo-Tree#196]

**Comment by Pranjal9999999** [comment]
I would like work on this issue as a participant under GSSOC'2021.

**Comment by krishna-NIT** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by chhavi18387** [comment]
Greetings!
I'm participating in Gssoc'21. I'd like to contribute to this problem by coding its C++ solution. Please assist it to me.
Thanks

**Comment by sakshi2707** [comment]
Hi,
I am a GSSOC'21 participant.


My code will be in JAVA with proper comments and test cases.
@nakul-19 @rudrakshi99 @plazzy99 please assign me this issue.

**Comment by SwarnimaShishodia** [comment]
Hi I am GSSOC participant, I would like to solve this problem and I can solve using Python and C++ both.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this

**Comment by tarun26091999** [comment]
I think you people are asking for 2D array.

**Comment by Pranjal9999999** [comment]
Yes, this issue has been raised in reference to 2d arrays. Please, assign me this issue as a GSSOC participant.
