### ISSUE TITLE
Adding knapsack DP for java and pythom

### ISSUE THREAD

**Issue by anjali1102** [Algo-Phantoms/Algo-Tree#1976]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
https://github.com/Algo-Phantoms/Algo-Tree/tree/main/Algorithm/DP the solution for java and python are missing.
I want to work on this.

**Describe the solution you'd like**

**Do you want to work on it**
Mention the one language you want to be assigned for this issue.

**Comment by anjali1102** [comment]
Assign me please

**Comment by muskan26062000** [comment]
@tarun26091999 please assign this issue to me in C++.

**Comment by rish-singhal** [comment]
Note you have to create one two different PRs for different languages

**Comment by Mugdha-Hazra** [comment]
I want to do it in c++ @rish-singhal

**Comment by anjali1102** [comment]
Hey @rish-singhal  Can you add level 3 if you feel so. As I opened this issue for java and python for medium difficulty DP problem

**Comment by rish-singhal** [comment]
1. Isn't knapsack dp a standard dp problem?

2. Also you have to submit 2 different PRs for each language
