### ISSUE TITLE
Adding welcome bot for  first timer issue raiser, first PR, first PR merged

### ISSUE THREAD

**Issue by anjali1102** [Algo-Phantoms/Algo-Tree#1977]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Whenever someone raises an issue and gives their PR, the bot will interact, greet them.

**Describe the solution you'd like**
<img width="801" alt="28288547-5f83aa8e-6af4-11e7-9692-eb41d42431e2" src="https://user-images.githubusercontent.com/56559378/119258161-2a363580-bbe6-11eb-911e-2cf220a13a45.png">
<img width="802" alt="28288851-679f582a-6af5-11e7-8dd8-b85b6c33e16b" src="https://user-images.githubusercontent.com/56559378/119258163-2b676280-bbe6-11eb-897b-bc9b939dff2e.png">
<img width="807" alt="28289605-1ab81a76-6af8-11e7-8f78-6a1b3948df36" src="https://user-images.githubusercontent.com/56559378/119258164-2d312600-bbe6-11eb-8bc9-ccb2b12d9969.png">

**Do you want to work on it**
Mention the one language you want to be assigned for this issue.
Yes, I want to work on this issue.
@tarun26091999  @rudrakshi99

**Comment by anjali1102** [comment]
Kindly assign me this issue

**Comment by anjali1102** [comment]
@LayaMitta I want to work on this, Can I go ahead

**Comment by rudrakshi99** [comment]
We have already added Github actions then no need for the bot.

**Comment by anjali1102** [comment]
Ok
