### ISSUE TITLE
Merge Sort Java + Quick Sort Java

### ISSUE THREAD

**Issue by sohini3062** [Algo-Phantoms/Algo-Tree#199]
I am a GSSOC '21 participant.

I wish to contribute these two sorting algorithm with comments and clear explanation as these are quite hard to understand at times from basic level.

**Comment by krishna-NIT** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by sakshi2707** [comment]
Hi,
I am a GSSOC'21 participant.

My code will be in C++ with proper comments and test cases.
@nakul-19 @rudrakshi99 @plazzy99 please assign me this issue.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this

**Comment by shreyanspoddar** [comment]
All the sorting algorithms are being worked on in the issue no #124 . You can ask there if any algorithm is missing.
