### ISSUE TITLE
CAPS lOCK(Basic Algo Question)

### ISSUE THREAD

**Issue by iaryangoyal** [Algo-Phantoms/Algo-Tree#1993]
wHAT DO WE NEED cAPS LOCK FOR?

Caps lock is a computer keyboard key. Pressing it sets an input mode in which typed letters are capital by default. If it is pressed by accident, it leads to accidents like the one we had in the first passage.

Let's consider that a word has been typed with the Caps lock key accidentally switched on, if:

either it only contains uppercase letters;
or all letters except for the first one are uppercase.
In this case we should automatically change the case of all letters. For example, the case of the letters that form words "hELLO", "HTTP", "z" should be changed.

Eg--
input---- cAPS
output--- Caps

**Comment by purohitmansi** [comment]
Do assign me.

**Comment by iaryangoyal** [comment]
@purohitmansi assigned

**Comment by iaryangoyal** [comment]
@purohitmansi
