### ISSUE TITLE
OOPS in CPP

### ISSUE THREAD

**Issue by Simi06** [Algo-Phantoms/Algo-Tree#1995]
I want to explain the working of all the OOPs concepts in CPP.
I'll provide a clear, well-explained, and optimized code for the same.
please assign this issue to me under GSSoC'21.

**Comment by Simi06** [comment]
@nakul-19 @raksha009 @rish-singhal @yasharth291
Please assign this to me.

**Comment by Simi06** [comment]
@rish-singhal @raksha009 @nakul-19 
 please review the issue.

**Comment by rudrakshi99** [comment]
We are only taking the algorithms.
