### ISSUE TITLE
pyhton algorithms with all documentations

### ISSUE THREAD

**Issue by robin025** [Algo-Phantoms/Algo-Tree#202]
Hi, @rudrakshi99 @nakul-19  @plazzy99 
I am a GSSOC'21 participant.
I would like to contribute to this project in python language with all major algorithms with all documentation.
I shall be very thankful to you if you please assign me this issue and soon will generate my PR

**Comment by ShrutiKhatri826** [comment]
I wish to contribute to this issue with proper comments, clear explanation and proper indentation resulting in a clean code using python language as a part of GSSOC'21 Participant.

Please assign me this issue, Hope to hear from you soon @rudrakshi99 @nakul-19 @plazzy99

**Comment by shreyanspoddar** [comment]
Not a valid issue can you be more specific.
