### ISSUE TITLE
Adding Auto Message about Code Guidelines on creating issue [ Bot ]

### ISSUE THREAD

**Issue by krishna-NIT** [Algo-Phantoms/Algo-Tree#2020]
**This Automation will help the project to get proper pr which follows the code guidelines**
Essential for this project

**Solution**
Using GitHub Action 1 .yml file will be pushed with all changed

**Comment by krishna-NIT** [comment]
@rish-singhal  Please Assign me and sorry for the delay but this will surely help this project

**Comment by rish-singhal** [comment]
@plazzy99 @rudrakshi99 @Rohan27s can your check this issue. Seems good to me.
