### ISSUE TITLE
Adding Labels automatically on creating issue [ Bot ]

### ISSUE THREAD

**Issue by krishna-NIT** [Algo-Phantoms/Algo-Tree#2021]
**This Automation will help the project to labels automatically on raised issue**
Essential for this project

**Solution**
Using GitHub Action 1 .yml file will be pushed with all changed

**Comment by krishna-NIT** [comment]
@rish-singhal  Please Assign me and sorry for the delay but this will surely help this project

**Comment by rish-singhal** [comment]
@plazzy99 @rudrakshi99 @Rohan27s can your check this issue. Seems good to me.

**Comment by krishna-NIT** [comment]
we cannot directly label the issues because the issue can be already solved or a similar issue is assigned to anyone else. so, I am closing the issue
