### ISSUE TITLE
Adding Automated labels on successfully merging the PR [ Bot ]

### ISSUE THREAD

**Issue by krishna-NIT** [Algo-Phantoms/Algo-Tree#2022]
**This Automation will help the project to labels automatically on raised PR when it gets merged successfully**
This will help the mentors a lot, Will save time and Issue regarding missing of label will also be avoided

**Solution**
Using GitHub Action 1 .yml file will be pushed with all changed

**Comment by krishna-NIT** [comment]
@rish-singhal  Please Assign me and sorry for the delay but this will surely help this project

**Comment by rish-singhal** [comment]
@tarun26091999 @rudrakshi99 @Rohan27s can your check this issue. Seems good to me.
