### ISSUE TITLE
Automated 2 file checker for raised PR [BOT]

### ISSUE THREAD

**Issue by krishna-NIT** [Algo-Phantoms/Algo-Tree#2023]
**This Automation will check for pr who has proper file changes [2] one is code and other is its readme**
Essential for this project, then it will be checked and will passed if made proper pr as per the project

**Solution**
Using GitHub Action 1 .yml file will be pushed with all changed

**Comment by krishna-NIT** [comment]
@rish-singhal  Please Assign me and sorry for the delay but this will surely help this project

**Comment by rish-singhal** [comment]
@plazzy99 @rudrakshi99 @Rohan27s can your check this issue. Seems good to me.

**Comment by krishna-NIT** [comment]
it will contradict when any bug issue will be there means a pr where readme doesn't need to be updated, only code file needs to be updated because its name has been added in the readme in past so, they will not be allowed to create pr so closing it
