### ISSUE TITLE
longest common prefix 

### ISSUE THREAD

**Issue by ssaumyaa7** [Algo-Phantoms/Algo-Tree#2042]
**Is your feature request related to a problem? Please describe.**
The Algorithm for longest common prefix in java is not there.

**Describe the solution you'd like**
Like to add the code in java for the same.

**Do you want to work on it**
I want to work in java language.

Please assign me this issue.
@rish-singhal

**Comment by rish-singhal** [comment]
Hi it's not okay to create a PR before being assigned the issue! Do keep this in mind next time :)

**Comment by ssaumyaa7** [comment]
Noted... Will not repeat this mistake

**Comment by U-c0de** [comment]
@rish-singhal @Rohan27s Assign me in Python
