### ISSUE TITLE
Algorithm to find if a graph is bipartite

### ISSUE THREAD

**Issue by Kedar-S** [Algo-Phantoms/Algo-Tree#205]
Java implementation for the algorithm to find if a graph is Bipartite with a full explanation of its concept and implementation details would be added.

I would like to do the Java implementation please.
[GSSoC]

**Comment by SAY-droid427** [comment]
I would like to do the C++ implementation to find out whether a graph is bipartite or not. please assign me this issue.

**Comment by Suvraneel** [comment]
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me these issues under GSSOC '21

**Comment by tarun26091999** [comment]
already present at #95
