### ISSUE TITLE
Add  .gitignore file 

### ISSUE THREAD

**Issue by Tanya933** [Algo-Phantoms/Algo-Tree#2075]
We need to add a .gitignore file in the repository in order to ignore files such as .DS_store files .
Please assign this issue to me .
@plazzy99  @rish-singhal @krishna-NIT @ @tarun26091999

**Comment by krishna-NIT** [comment]
@Tanya933 Late mat hona bas😂

**Comment by Tanya933** [comment]
Done with the PR.Please review
