### ISSUE TITLE
Add code for unbounded knapsack using dynamic programming

### ISSUE THREAD

**Issue by SAY-droid427** [Algo-Phantoms/Algo-Tree#211]
I would like to add the code for unbounded knapsack using dynamic programming in C++. Please assign me this issue so that I can work on it under GSSOC'21

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this

**Comment by Aarti002** [comment]
Hey there! i'm gssoc'21 participant can i work on this issue using python  with some explanatory comments to make the code more easier to understand , for a beginner as well.
please assign this to me.
Thank you!
