### ISSUE TITLE
Largest element to the left algorithm in C++

### ISSUE THREAD

**Issue by SAY-droid427** [Algo-Phantoms/Algo-Tree#212]
I would like to add the code for finding the largest element to the left in C++. Please assign me this issue.

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you .

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by OjusWiZard** [comment]
@SAY-droid427 Please explain the problem statement more briefly.
