### ISSUE TITLE
Adding more Sorting algorithms  

### ISSUE THREAD

**Issue by Anurag-bhatia** [Algo-Phantoms/Algo-Tree#215]
Sorting algorithms are very intresting and also vey useful , So i want to add more sorting algorithms like bubble sort, bucket sort, count sort, shell sort, radix sort.

I woukd like to add these algorithms in the code in C++  language . kindly assigned me as a part of GSSOC '21.

**Comment by Vansh-Gupta4** [comment]
Sorting algorithms are very intresting and also vey useful , So i want to add more sorting algorithms like bubble sort, bucket sort, count sort, shell sort, radix sort.

I woukd like to add these algorithms in the code in Java language . kindly assigned me as a part of GSSOC '21.

**Comment by shreyanspoddar** [comment]
All the sorting algorithms are being worked on in the issue no #124 . You can ask there if any algorithm is missing.
