### ISSUE TITLE
Find Union and Intersection of two sorted arrays

### ISSUE THREAD

**Issue by CSAURABH** [Algo-Phantoms/Algo-Tree#216]
Example:-
Input : arr1[] = {1, 3, 4, 5, 7}
        arr2[] = {2, 3, 5, 6} 
Output : Union : {1, 2, 3, 4, 5, 6, 7} 
         Intersection : {3, 5}
I would like to solve this problem using C++.

**Comment by CSAURABH** [comment]
@nakul-19 Please assign me this issue. I want to contribute, I am a Gssoc'21 participant.

**Comment by krishna-NIT** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by Naman-12911** [comment]
I am participant of GSSOC'21 .
I want contribute code for this issue.
I solves this question in past.
please assign me this issue

**Comment by Suvraneel** [comment]
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me these issues under GSSOC '21

**Comment by soumik2012** [comment]
@tarun26091999 
I am participant of GSSOC'21 .
I want contribute code for this issue in python .
I solves this question in past.
please assign me this issue
