### ISSUE TITLE
Minimum number of deletions to make a string palindrome

### ISSUE THREAD

**Issue by krishna408** [Algo-Phantoms/Algo-Tree#220]
**An algorithm to find the minimum no of deletion of characters from the string so that the resultant string becomes a palindrome using dynamic programming approach.** 
_Please assign it to me_
@anubhavitis 
@dheerajkotwani
 @tarun26091999 
@todi-2000 @geekquad

**Comment by machine-sg** [comment]
Hey I am GSSOC'21 participant and I wish to work on this. I want to code in in C++

**Comment by Vishal-Singh-1996** [comment]
I want to code in Java pls assign it to me 
@anubhavitis
@dheerajkotwani
@tarun26091999
@todi-2000 @geekquad

**Comment by Amit366** [comment]
Can I solve it using python? @tarun26091999
@anubhavitis

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by Aarti002** [comment]
hey @tarun26091999 can i work on this issue in python with proper explanatory comments .
please assign this issue to me
Thank you!

**Comment by Vishal-Singh-1996** [comment]
Vishal-Singh-1996:patch/Palindrome

**Comment by Vishal-Singh-1996** [comment]
Algorithm/Special_algo/Palindrome.java

**Comment by Vishal-Singh-1996** [comment]
check and merge @tarun26091999 pls

**Comment by tarun26091999** [comment]
@Vishal-Singh-1996 you haven't raised the PR yet.

**Comment by krishna408** [comment]
#329

**Comment by Vishal-Singh-1996** [comment]
> @Vishal-Singh-1996 you haven't raised the PR yet.

I Create Patch/palindrome #388 look in to it.

**Comment by Vishal-Singh-1996** [comment]
@rudrakshi99 
Pls look into it here I create a separate link and also link to the issue as to told
