### ISSUE TITLE
Sorting Algorithms in Java

### ISSUE THREAD

**Issue by nidhi-08** [Algo-Phantoms/Algo-Tree#221]
There are 5 sorting algorithms in CPP in the sorting folder. I want to add all the Java codes for them.
Also I want to add a few other sorting algorithms like Sleep Sort, Shell Sort, Radix Sort.

Please assign this to me as a part of GSSOC'21

**Comment by krishna-NIT** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this

**Comment by OjusWiZard** [comment]
Raise separate issues for each sorting algorithms. Some of them are already being implanted by the people.
