### ISSUE TITLE
Searching Algorithms in Java

### ISSUE THREAD

**Issue by nidhi-08** [Algo-Phantoms/Algo-Tree#222]
There are no searching algorithms under the Algorithm/Searching_Sorting folder. I would like to add a few searching algorithms in Java. 
Request you to assign it to me as a part of GSSOC'21

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by OjusWiZard** [comment]
Raise separate issues for each searching algorithms. Some of them are already being implanted by the people.
