### ISSUE TITLE
Adding more Sorting Algorithms

### ISSUE THREAD

**Issue by imsushant12** [Algo-Phantoms/Algo-Tree#224]
Hello, @rudrakshi99 @nakul-19 @plazzy99 , I am a GSSOC'21 participant.

I wish to contribute **some sorting algorithm** with comments and clear explanation-
1. Bubble Sort
2. Bubble Sort with improved time complexity 
3. Selection Sort
4. Iterative Merge Sort 
5. Shell Sort
6. Count Sort
7. Radix Sort

My code will be in **C++** with proper comments and test cases.

**Comment by Vansh-Gupta4** [comment]
Hello, @rudrakshi99 @nakul-19 @plazzy99 , I am a GSSOC'21 participant.

I wish to contribute some sorting algorithm with comments and clear explanation-

Bubble Sort
Bubble Sort with improved time complexity
Selection Sort
Iterative Merge Sort
Shell Sort
Count Sort
Radix Sort
My code will be in JAVA with proper comments and test cases.

**Comment by ShreyaGautamm** [comment]
Hello maintainers. I am a GSSOC'21 participant.
i wish to contribute Bubble Sort Algo in C++ with clear explanations. Please assign it to me.

**Comment by Suvraneel** [comment]
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me these issues under GSSOC '21.

**Comment by shreyanspoddar** [comment]
All the sorting algorithms are being worked on in the issue no #124 . You can ask there if any algorithm is missing.
