### ISSUE TITLE
Add DP problems

### ISSUE THREAD

**Issue by nidhi-08** [Algo-Phantoms/Algo-Tree#226]
Dynamic Programming has only CPP codes. I would like to add the Java codes for Kadane's Algorithm and Knapsack

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by Abhinaba006** [comment]
I am a GSSOC 21 participant, I will like to work on this project, please assign me this

**Comment by tarun26091999** [comment]
issue has to regarding a specific problem
