### ISSUE TITLE
Deletion of node in linked list

### ISSUE THREAD

**Issue by imsushant12** [Algo-Phantoms/Algo-Tree#227]
Hello, @rudrakshi99 @nakul-19 @plazzy99 , I am a GSSOC'21 participant.

I wish to contribute deletion of starting, end and specific position node from singly linked list , doubly linked list and circular linked list with proper comments and clear explanation-

Please assign me this issue ,my code will be in C++ with proper comments and test cases.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by yashikajotwani12** [comment]
I would love to code and explain it in cpp or python , please assign me this issue .

**Comment by rk05-lenavo** [comment]
Hi!!
I am interested in this project . I wish to contribute C++ code for this issuePlease assign this project to me under GSSOC '21

**Comment by ShrutiKhatri826** [comment]
I wish to contribute to this issue with proper comments, clear explanation and proper indentation resulting in a clean code. My code will be in C++. Please assign me this issue, Hope to hear from you soon @rudrakshi99 @nakul-19 @plazzy99

**Comment by Aarti002** [comment]
hello there! can i work on this issue under gssoc'21 ,using python with proper explanatory comments.
Thank you!

**Comment by madhvi02** [comment]
Hey ,
I really want to contribute to this issue.I  will provide with the commented code .@tarun26091999 Sir Please give me a chance to contribute into this .

Thought Process: we have to traverse over the link list by maintaining 2 nodes prevent and cure.When we reached the state where curr->data == the data of the deleted node I need make the connect prevents->next=curr->next and removing the current node from the memory .Also we have to handle some case like:
1.head node to be deleted
2.the last node
3.if head==NULL

**Comment by tarun26091999** [comment]
issue is open at #152
