### ISSUE TITLE
Stack Implementation using Linked List and Static Array

### ISSUE THREAD

**Issue by imsushant12** [Algo-Phantoms/Algo-Tree#231]
Hello, @rudrakshi99 @nakul-19 @plazzy99 , I am a GSSOC'21 participant.

I wish to contribute Implementation of **Stack using Linked List and Static Array** with proper comments and clear explanation-

Please assign me this issue ,my code will be in **C++** with proper comments and test cases.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this

**Comment by yashikajotwani12** [comment]
I would love to contribute this in cpp or python, please assign me this issue.

**Comment by OjusWiZard** [comment]
Stack using LL is already in the repo. So make a separate issue for Stack using array.
