### ISSUE TITLE
Longest Common Subsequence 

### ISSUE THREAD

**Issue by Yukti-1** [Algo-Phantoms/Algo-Tree#235]
I want to add the algorithm to 

- Find length of the longest common subsequence using Dynamic Programming. 
- Print the longest common subsequence

Language - C++ and Python

May I be assigned this issue?  ( Under GSSOC'21 ) 
@nakul-19 @anubhavitis @geekquad @plazzy99

**Comment by plazzy99** [comment]
Refer issue no. #166
