### ISSUE TITLE
DP and Graph related problems

### ISSUE THREAD

**Issue by samar08** [Algo-Phantoms/Algo-Tree#238]
Hi, I'm a GSSOC 2021 participant. Please assign me this issue. I will update proper code in java as well as python with proper comments and code structure.

**Comment by Vansh-Gupta4** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this

**Comment by yashikajotwani12** [comment]
I would love to code it in cpp or python , with proper code and explanation . please assign me this issue @plazzy99 .

**Comment by Abhinaba006** [comment]
I am a gssoc 21 participant, I will like to work on this issue

**Comment by OjusWiZard** [comment]
Create separate issues for separate problems
