### ISSUE TITLE
Kadane's Algorithm 

### ISSUE THREAD

**Issue by Nkap23** [Algo-Phantoms/Algo-Tree#244]
Kadane's Algorithm (also called Maximal Subarray sum algorithm) is one of the most basic Dynamic Programming Algorithms. It is used to find a subarray with a maximum sum. The normal algorithm would take O(n^2) time (where n is the size of an array), but when optimized with Dynamic Programming, the time complexity reduces to O(n).
So Kadane's Algorithm is an efficient way to calculate maximal subarray sum.

I request Project Admins/Mentors to assign the issue to me.
@tarun26091999

**Comment by vedant-jain03** [comment]
Hello I can do this issue using cpp and python please assign me this issu I will use commented code flow

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you . I will give some testcases with proper explanation too. I'll also add other problems which will be solved based on this concept.
Thank you .

**Comment by divya1509** [comment]
Hey, I am Divya, a GSSOC'21 participant and I wish to work on this issue in the JAVA language. I will provide a neat and well explanatory code for the issue with certain test cases. Please assign this issue to me.

**Comment by tarun26091999** [comment]
> Kadane's Algorithm (also called Maximal Subarray sum algorithm) is one of the most basic Dynamic Programming Algorithms. It is used to find a subarray with a maximum sum. The normal algorithm would take O(n^2) time (where n is the size of an array), but when optimized with Dynamic Programming, the time complexity reduces to O(n).
> So Kadane's Algorithm is an efficient way to calculate maximal subarray sum.
> 
> I request Project Admins/Mentors to assign the issue to me.
> @tarun26091999

do it in java.

**Comment by tarun26091999** [comment]
> Hello I can do this issue using cpp and python please assign me this issu I will use commented code flow

do it in python.

**Comment by tarun26091999** [comment]
@majestic-rahul @machine-sg the C++ code is already present in the repo.

**Comment by Nkap23** [comment]
> > Kadane's Algorithm (also called Maximal Subarray sum algorithm) is one of the most basic Dynamic Programming Algorithms. It is used to find a subarray with a maximum sum. The normal algorithm would take O(n^2) time (where n is the size of an array), but when optimized with Dynamic Programming, the time complexity reduces to O(n).
> > So Kadane's Algorithm is an efficient way to calculate maximal subarray sum.
> > I request Project Admins/Mentors to assign the issue to me.
> > @tarun26091999
> 
> do it in java.

Okay

**Comment by vedant-jain03** [comment]
@tarun26091999 thankyou for assigning me this issue. I wanted to know that in which language I should go ahead
