### ISSUE TITLE
Count set bits

### ISSUE THREAD

**Issue by Mahima0405** [Algo-Phantoms/Algo-Tree#246]
Add algorithms for counting the total number of setbits using 2 different approaches of bitmasking.
(in C++).  I would like to contribute to this problem as a part of GSSOC'21. Please assign me this question and I promise to give a clean, understandable, and readable code with comments and corresponding test cases.
I request the mentors to assign me this question:
@tarun26091999

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you . I will give some testcases with proper explanation too.
Thank you .

**Comment by pshivesh8** [comment]
Interested! I have recently worked on Bitmasking problems in C++.  I can provide good code with clear examples.
If you can please assign this issue to me. I would love to work on this issue.

**Comment by tarun26091999** [comment]
@machine-sg @Siddhant-K-code @pshivesh8 C++ code is already assigned.

**Comment by Siddhant-K-code** [comment]
> @Siddhant-K-code C++ code is already assigned.

??

**Comment by asthakri50** [comment]
Hey @tarun26091999 ,
 I am a GSSOC'21 participant and I prefer to code in Java.
I would like to add the code for this question in Java. Do I need to create another issue for that?
Looking forward to hear from you.
Thank you.

**Comment by tarun26091999** [comment]
submit the most optimized approach only.

**Comment by Manya1609** [comment]
Hey..I'm a GSSOC'21 Participant and would like to work on this issue. I would explain the concept and the code for it in C++.

**Comment by shahina-bano** [comment]
I will solve this problem using python, please assign me.

**Comment by raksha009** [comment]
Issue present at #44
