### ISSUE TITLE
Binary_search_Classic_question_(Aggressive Cows)

### ISSUE THREAD

**Issue by Mahima0405** [Algo-Phantoms/Algo-Tree#247]
Add a classic problem of Binary_search which enables the learners get an idea of how and where to apply binary search algorithm in reality. (in C++). I would like to contribute to this problem as a part of GSSOC'21. Please assign me this question and I promise to give a clean, understandable, and readable code with comments and corresponding test cases.
I request the mentors to assign me this question:
@tarun26091999

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you . I will give some testcases with proper explanation too. Also I'll add other questions as well which will be solved using this same approach.
Thank you .

**Comment by tarun26091999** [comment]
we do not accept the questions from coding platforms.
