### ISSUE TITLE
Sieve_Of_Eratosthenes

### ISSUE THREAD

**Issue by Mahima0405** [Algo-Phantoms/Algo-Tree#249]
This code has not yet been added to the folder and I would like to add this code which again forms the building blocks for basic knowledge in number theory. Being an optimized approach to finding prime numbers it has a few developmental steps which can be covered step by step and if not then direct code is also a good start to learn optimization.  I would like to contribute to this problem as a part of GSSOC'21. Please assign me this question and I promise to give a clean, understandable, and readable code with comments and corresponding test cases.

**Comment by yashikajotwani12** [comment]
I would  to give the implementation in C, C++ or python.
please assign me this issue.

**Comment by aditiaggarwal28** [comment]
I am a GSSOC'21 participant and requesting the admins to assign this issue to me. I will provide a clean code with proper comments and optimized code for calculating prime numbers using this method. I can solve this issue using both languages CPP and python.

**Comment by machine-sg** [comment]
Hi, I am GSSOC'21 participant. I wish to work on this using C++. Hope to hear you .Please assign me this.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean code
please assign me this issue under GSSoC 2021

**Comment by Priya730** [comment]
Hey! I would like to work on this issue in JAVA. Kindly assign it to me.

**Comment by shreyanspoddar** [comment]
This issue has been already assigned before refer #47
