### ISSUE TITLE
Types of LinkedLists - Implementation

### ISSUE THREAD

**Issue by Kedar-S** [Algo-Phantoms/Algo-Tree#250]
I will implement Singly LL, Doubly LL, Circular LL, Circular Doubly LL with all the basic operations: InsertAtFirst(), InsertAtLast(), deleteFirst(), deleteLast().

I can also maintain an index in all of these Linked Lists so that operations like insertAtIndex() and deleteAtIndex() could be used.

All implementations would be in Java.

[GSSoC]

**Comment by vedant-jain03** [comment]
Hello I can do this issue using cpp and python please assign me this issu I will use commented code flow

**Comment by imsushant12** [comment]
I wish to contribute to this issue with proper comments and clear explanation-

Please assign me this issue, my code will be in C++ with proper comments and test cases.

**Comment by Vishal-Singh-1996** [comment]
I want to implement In java these problem

**Comment by Mahima0405** [comment]
Hello, I also wish to work on this question and can provide a well commented and clean code in C++. Plesae assign me this question.

**Comment by ShrutiKhatri826** [comment]
I wish to contribute to this issue with proper comments, clear explanation resulting in a clean code. My code will be in C++ with proper comments and test cases. Please assign me this issue, Hope to hear from you soon!

**Comment by Suhanii1214** [comment]
Hello!!
I am a java developer and I would like to contribute to this issue using Java as a part of GSSOC'21 
Thankyou!!

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by OjusWiZard** [comment]
Make separate issues for them
