### ISSUE TITLE
Add LinkedList Reversal Java

### ISSUE THREAD

**Issue by sohini3062** [Algo-Phantoms/Algo-Tree#255]
GSSoC 2021 participant.
I will like to add Reversal of LinkedList in java and will use clear and concise code with explanations

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you . I will give some testcases with proper explanation too.
Thank you .

**Comment by Alleny244** [comment]
Hello
I am a GSSOC'21 participant
I would like to contribute in this issue
I can implement this code in java with proper comment for better understanding.
I will also add 2-3 testcases for better understanding

**Comment by Vishal-Singh-1996** [comment]
I would Like to do this in javA

**Comment by Vishal-Singh-1996** [comment]
pls assign it to me

**Comment by machine-sg** [comment]
Hi, I am GSSOC'21 participant. I wish to work on this using C++. Hope to hear you .Please assign me this.
