### ISSUE TITLE
Insertion sort in Linkedlist

### ISSUE THREAD

**Issue by Adrenalinerush07** [Algo-Phantoms/Algo-Tree#261]
Hello, @rudrakshi99 @nakul-19 @plazzy99.
I am a GSSoC'21 participant. (Discord username - KartikJaiswal#6870)

I wish to contribute to the implementation of Insertion sort of Linked List with proper comments and clear explanation.

Please assign me this issue, my code will be in C++ with proper comments and test cases.
I assure you I can handle this issue as I am extremely good at DSA and problem-solving in C++.

Hoping for a good outcome from your side.

**Comment by Vishal-Singh-1996** [comment]
I would like to create this problem in Java also

**Comment by Aarti002** [comment]
hello everyone myself Aarti one of the participant of GSSoC'21 .
I would love to do this issue in python or c++.
Please assign  this issue to me.
Thank u!!

**Comment by Vishal-Singh-1996** [comment]
@tarun26091999 pls look into it (Patch/insertion merge sort algo #408)

**Comment by Vishal-Singh-1996** [comment]
@tarun26091999 
Sir, pls look into it :-Patch/#261 #556

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by HitainKakkar** [comment]
I would like to add the code c++ with explaination.
My code is ready. kindly assinged it to me.

**Comment by Nishayadav-bit** [comment]
Hey , I'm a GSSOC'21 participant . I would like to work on this issue please assign me .

**Comment by einhawking** [comment]
I am a participant of GSSOC'21
I would like to contribute in this
