### ISSUE TITLE
gssoc'21 want to create check prime or not 

### ISSUE THREAD

**Issue by Vishal-Singh-1996** [Algo-Phantoms/Algo-Tree#266]
I would like to create this program in java or python also

**Comment by machine-sg** [comment]
Hi, I am GSSOC'21 participant. I wish to work on this using C++. Hope to hear you .Please assign me this.

**Comment by Vishal-Singh-1996** [comment]
@machine-sg go for it

**Comment by srishti-13** [comment]
Hey I would like to contribute to this issue as a part of gssoc 2021. Could you please assign this issue to me ? I will implement this in c++

**Comment by Vishal-Singh-1996** [comment]
@srishti-13 yeah go for it

**Comment by machine-sg** [comment]
Okay.
Thank you.

**Comment by kushal13112001** [comment]
Hi, I am GSSOC'21 participant. I wish to work on this using Python. Hope to hear you .Please assign me this.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean code
please assign me this issue under GSSoC 2021

**Comment by SavneetKaur01** [comment]
Under GSSoc 21, can you please assign me this issue. I want to work on it using Python language.

**Comment by Aditya7494** [comment]
I am a GSSOC'21 participent and i want to contribute on this issue.
Can you please assign it to me?

**Comment by ShrutiKhatri826** [comment]
Hi, I am GSSOC'21 participant. I wish to work on this using C++. Please assign me this issue. Hope to hear from you.

**Comment by MukulKolpe** [comment]
Hey, I am a GSSOC'21 participant. Can you please assign this issue to me? I can work on it with Java.

**Comment by Aarti002** [comment]
hello everyone myself Aarti one of the participant of GSSoC'21 .
I would love to do this issue in python or c++.
Please assign this issue to me.
Thank u!!

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by Upasana1216** [comment]
I am a GSSOC'21 participant and I would really like to contribute to this algorithm in C++ with added comments ,test cases and time and space complexity . Looking forward to the contribution.

**Comment by Manya1609** [comment]
Hey!..I'm a GSSOC'21 Participant and would like to work on this issue. I would like to explain the concept and the code in C++. 
Can anyone please assign me this issue??
