### ISSUE TITLE
[GSSOC'21] Kruskal's Algorithm

### ISSUE THREAD

**Issue by machine-sg** [Algo-Phantoms/Algo-Tree#269]
Hello, I am a GSSOC'21 participant and I want to add the code of this algorithm. My code will be in C++. I will also give some other examples which will be solved using this algorithm with proper explanation. Please assign me this. Hope to hear you.
Thank you .

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean code
please assign me this issue under GSSoC 2021

**Comment by Aarti002** [comment]
hello everyone myself Aarti one of the participant of GSSoC'21 .
I would love to do this issue in c++.
Please assign this issue to me.
Thank u!!

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by Upasana1216** [comment]
I am a GSSOC'21 participant and I would really like to contribute to this algorithm in C++ with added comments, test cases, and time and space complexity. Looking forward to the contribution.
