### ISSUE TITLE
Factorial using Recursion

### ISSUE THREAD

**Issue by manastole03** [Algo-Phantoms/Algo-Tree#276]
I am Manas GSSOC 2021 participant want to contribute Recursion algorithm for Factorial in Java programming language.
Assign this task to me :)

**Comment by kushal13112001** [comment]
Hey, I am a GSSOC'21 participant. I would like to contribute the code of this problem statement in PYTHON language. Please assign this issue to me.

**Comment by anjali7786** [comment]
Hi, I am a GSSoc;21 participant and I would like to work on this issue in C++ language. Please assign this issue to me

**Comment by tanyalava** [comment]
I am a  GSSOC'21 participant and I would really like to contribute to recursion algorithms  in C++ . Looking forward to the contribution.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java. Could you please assign it to me?

Thanks!!

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue as a GSSoC 2021 participant
I would be explaining Recursion Algorithm with the help of Divide and Conquer method using Merge Sort as an example
kindly assign me this issue
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by shreyanspoddar** [comment]
> I am Manas GSSOC 2021 participant want to contribute Recursion algorithm for Factorial in Java programming language.
> Assign this task to me :)

Go ahead and do it in Java

**Comment by shreyanspoddar** [comment]
> Hey, I am a GSSOC'21 participant. I would like to contribute the code of this problem statement in PYTHON language. Please assign this issue to me.

Go ahead and do it in Python

**Comment by shreyanspoddar** [comment]
> Hi, I am a GSSoc;21 participant and I would like to work on this issue in C++ language. Please assign this issue to me

Go ahead and do it in C++

**Comment by Aj7t** [comment]
hi, I am a Gssoc'21 participant I want to work on the "Fibonacci series using recursion " in python. 
 could you please assign me and also guide me through my first contribution.

**Comment by Manish5237** [comment]
Hi ,

I am GSSOC'21 participant.
Please assign me this. I will do this in C with proper comments and test cases.

@shreyanspoddar

**Comment by RinalGadhiya** [comment]
Hi I am gssoc participant I would like to solve this issue using Java
Could you please assign it to me? 
Thanks!

**Comment by Manya1609** [comment]
Hey..I'm a GSSOC'21 Participant and would like to work on this issue...I would like to explain and code it in C++.

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. I will be using Java. Thanks!

**Comment by Nishayadav-bit** [comment]
Hey , I'm a GSSOC'21 participant . I would like to work on this issue please assign me .

**Comment by tarun26091999** [comment]
@Manya1609 you have to raise a PR.

**Comment by Aj7t** [comment]
Thankyou for assigning @tarun26091999 
I have already raised a PR !!

**Comment by Manya1609** [comment]
> @Manya1609 you have to raise a PR.

Sir I have already raised a PR too with the name  "Manya1609 add factorials 1"
![Screenshot (804)_LI](https://user-images.githubusercontent.com/72715296/119297812-55b63000-bc79-11eb-95ea-5555e25c2d5d.jpg

**Comment by tarun26091999** [comment]
> Thankyou for assigning @tarun26091999
> I have already raised a PR !!

link it here

**Comment by Aj7t** [comment]
Plz do check this 👍 
https://github.com/Algo-Phantoms/Algo-Tree/pull/1982
