### ISSUE TITLE
[GSSOC'21]Subset Sum Problem(Dp)

### ISSUE THREAD

**Issue by suyashi912** [Algo-Phantoms/Algo-Tree#280]
I would like to work on the following problem in c++ 
Subset Sum Problem :  Given a set of non-negative integers, and a value of required sum, we need to determine if there is a subset of the given set with sum equal to given sum. 
I would also add comments explaining the code, test case and time and space complexities. 

Event :
GSSoC'21

Please assign me to the above task :)

**Comment by kushal13112001** [comment]
Hey, I am a GSSOC'21 participant. I would like to contribute the code of this problem statement in PYTHON language. Please assign this issue to me.

**Comment by manastole03** [comment]
Hey, I am Maas a GSSOC'21 participant. I would like to contribute the code of this problem statement in Java language.
 Please assign this issue to me :)

**Comment by Sanju-github002** [comment]
Hello ! I am Sanju a GSSOC'21 participant. I want to contribute in this problem with C++. please assing this problem to me.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean code
please assign me this issue under GSSoC 2021

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java. Could you please assign it to me?

Thanks!!

**Comment by tarun26091999** [comment]
issue being worked at #148
