### ISSUE TITLE
Elaboration and questions on strings in different languages.

### ISSUE THREAD

**Issue by nagasrihith608** [Algo-Phantoms/Algo-Tree#284]
I want to elaborate on the understanding of strings in various languages like c/c++ java and python, would like to explain the differences and uses and also give code with example questions.

Please assign this issue to me under GSSOC'21

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me

**Comment by nagasrihith608** [comment]
@rudrakshi99 hello, please assign this issue to me under GSSoC'21. I had opened this issue 5 days back and waiting for your reply. Thank you!
