### ISSUE TITLE
Linked List in python

### ISSUE THREAD

**Issue by sujoy-coder** [Algo-Phantoms/Algo-Tree#29]
I want to add linked list program in python. Please assign it to me.

**Comment by tina-alex-leslie** [comment]
I want to help with this. Please assign this to me.

**Comment by ChetasShree** [comment]
I am GSSoC'21 Participant. I would like to work on this issue. Please assign it to me. I will solve it in python

**Comment by raksha009** [comment]
> I want to add linked list program in python. Please assign it to me.

Heyy, this issue wasn't assigned to you. Pl make a pr only after issue has been assigned. 
Making an exception this time but plz keep this in mind next time onwards :)

**Comment by raksha009** [comment]
> I want to help with this. Please assign this to me.
Plz specify language.
