### ISSUE TITLE
For Implementation of Manacher’s Algorithm Algorithm in C++

### ISSUE THREAD

**Issue by Yash1256** [Algo-Phantoms/Algo-Tree#296]
- As a GSSOC 2021 participant, I would like to add the Manacher’s Algorithm in Strings Section of the Code, and it's code will be in C++.
- It is a highly efficient algorithm which significantly reduces the computation time for problems involving finding Longest Palindromic Substring in a Given String.

Kindly assign this issue to me, I assure you that I will provide a clear explanation and clean code for the same.

**Comment by tarun26091999** [comment]
adding a PR without issue being assigned is against our guidelines.
