### ISSUE TITLE
7 questions in LCS(Dynamic Programming)

### ISSUE THREAD

**Issue by pranjalshikhar** [Algo-Phantoms/Algo-Tree#30]
I can implement in C++

1. Longest Common Subsequence 
2. Print Longest Common Subsequence
3. Longest Common Substring
4. Shortest Common Subsequence
5. Print Shortest Common Subsequence
6. Minimum no. of ways of insertion and deletion to convert string A to string B.
7. Longest Palindromic Subsequence

**Comment by sunidhi1999-c** [comment]
I have been selected for GSSOC'21, and I am really interested in Algorithms , so I would like to contribute in this amazing repository.I can contribute for this ,I am 2 star codechef candidate and would be great to contribute to open source programs like this one. I can write these articles if given a chance.
Thanks.
Sunidhi,
3rd year,CSE at NMAMIT,Nitte,Karnatak

**Comment by ahmed-shameem** [comment]
Hi,
Please assign this task to me. I am a GSSoC'21 participant. I can solve the problem using c++.

**Comment by Muskan0** [comment]
Hi, please assign this task to me, I will solve it in Python.

**Comment by Chirag018** [comment]
Hi,Please assign this task to me . I'm a GSSoc Participant.
I can solve the problems using Java .

**Comment by rudrakshi99** [comment]
> I can implement in C++
> 
> 1. Longest Common Subsequence
> 2. Print Longest Common Subsequence
> 3. Longest Common Substring
> 4. Shortest Common Subsequence
> 5. Print Shortest Common Subsequence
> 6. Minimum no. of ways of insertion and deletion to convert string A to string B.
> 7. Longest Palindromic Subsequence

Please make separate issues for each algorithm.
