### ISSUE TITLE
Complete set of Graph Algorithms in c++

### ISSUE THREAD

**Issue by sru123p** [Algo-Phantoms/Algo-Tree#300]
Hello,
I am sruthi, GSSOC 2021 participant. When I got started with graphs I found it difficult to understand various problems in graphs. Now after so many days of practice I understood the intuition behind every algorithm. 
So I would like you contribute the problem set of graph algorithms(graph traversals, bfs, dfs,connect graphs, shortest paths, topological sorting, directed and weighted graphs, and many important problems on graphs) together at one place in C++ with clean code and proper explanation.
I request you to please assign this task to me

**Comment by srisatya1197** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by tarun26091999** [comment]
you cannot ask for more than 1 ques in a single issue.
