### ISSUE TITLE
Would work on stack, queue, linked lists

### ISSUE THREAD

**Issue by kratika19** [Algo-Phantoms/Algo-Tree#305]

**Comment by Zeo-shark** [comment]
I am GSSoC '21 Participant and I would love to work for this issue in java as well as Python. I have a good hold over java and python and I know intermediates of Data Structures and their implementation. I feel that I am fit for this issue.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by Na2001** [comment]
Hey,I am GSSoC '21 Participant and I can do this.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java. Could you please assign it to me?

Thanks!!
