### ISSUE TITLE
[GSSOC'21] Adding to the Questions section of Bit Manipulation under algorithms 

### ISSUE THREAD

**Issue by Ananya88** [Algo-Phantoms/Algo-Tree#311]
Hey !!
I am interested in this project as GSSOC '21 participant .
And I would add some of the solved questions/examples for bit masking like  clear range of bits, counting set bits , generate subsets using bit-masking.

Please assign me with this issue .Thanks.

**Comment by aanchalrakheja** [comment]
Hey!! I would like to know more about the problem and contribute to it.

**Comment by tarun26091999** [comment]
cannot ask for more than 1 question in a single issue.

**Comment by Ananya88** [comment]
> cannot ask for more than 1 question in a single issue.

I just explained what I'll do , didn't ask any questions .
