### ISSUE TITLE
Sort in O(N) time

### ISSUE THREAD

**Issue by Vish-github** [Algo-Phantoms/Algo-Tree#312]
Say we are given an array of integers in the range 0-9 or 0-100 .
i can write a C++ code to sort the array in linear time O(N) .
Please assign me this issue.  @tarun26091999  @rudrakshi99 @Siddhant-K-code  [ I'm a Gssoc21 Participant ]

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by rudrakshi99** [comment]
@Vish-github Which algorithm will you use?

**Comment by Vish-github** [comment]
i'll use the concept of hashing. 
count the occurences of each element and store in a seperate count array or use Hashmap (unordered_map) from STL.

**Comment by tarun26091999** [comment]
> i'll use the concept of hashing. @rudrakshi99
> count the occurences of each element and store in a seperate count array or use Hashmap (unordered_map) from STL.
> i could code two programs one with count array which uses concept of hashing and it would be easy for those who don't know STL , and one program with Hashmap.

you are using Counting sort, if I am not wrong. Its already done in #334 .

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue. Could you please assign it to me?

Thanks!!

**Comment by Aarti002** [comment]
hello @rudrakshi99 @tarun26091999 can i work on this issue i will be using insertion sorting algorithm in python 
Thank you!
