### ISSUE TITLE
Concept of POINTER !! 

### ISSUE THREAD

**Issue by rohank2502** [Algo-Phantoms/Algo-Tree#315]
I will like to add content regarding concept of POINTER !! I will make sure that the content will be begineer friendly. I will  add my own notes in my own words not copied from any other sources. I will also make sure that code will run perfectly and also make use of comments so that new students will understand the particular concepts easily !!

**Comment by rohank2502** [comment]
I will start working on it once i am assigned to it.

**Comment by anshika-anku** [comment]
I would like to work on the concept of the pointer. I am well aware of this topic and have a good command of it. I'll make sure to explain it as simply as possible in my own language. Kindly assign this task to me.
thank you!

**Comment by rohank2502** [comment]
> 
> 
> I would like to work on the concept of the pointer. I am well aware of this topic and have a good command of it. I'll make sure to explain it as simply as possible in my own language. Kindly assign this task to me.
> thank you!

I am the one who is asking for permission !
