### ISSUE TITLE
 Repeating and missing number

### ISSUE THREAD

**Issue by chitrasingla** [Algo-Phantoms/Algo-Tree#317]
Hey !!
I am interested in this project as GSSOC '21 participant.
And I would add the problem - find the repeating and missing number in C++.

@tarun26091999  Please assign me with this issue.
Thanks.

**Comment by Aarti002** [comment]
hello, i'm a gssoc'21 participant can contribute some interesting array problems of  different levels .
Thanks!

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by tarun26091999** [comment]
@pallavidhere23 do it in java

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. I will be using Java. Thanks!

**Comment by yashmita** [comment]
I would like to work on this issue in Python. Kindly assign it to me @tarun26091999  @plazzy99.

**Comment by tarun26091999** [comment]
all PRs merged.
