### ISSUE TITLE
[GSSOC'21] Adding more 2D array problems

### ISSUE THREAD

**Issue by chitrasingla** [Algo-Phantoms/Algo-Tree#318]
Hey !!
I am interested in this project as GSSOC '21 participant.
And I would add some of the solved questions/examples for 2D arrays like finding transpose of a matrix, rotate the matrix anticlockwise.

Please assign me with this issue.
Thanks.

**Comment by srisatya1197** [comment]
I want to contribute to adding more 2d array problems issue. Please assign me this task as a part of GSSoC'21

**Comment by rohank2502** [comment]
> 
> 
> I want to contribute to adding more 2d array problems issue. Please assign me this task as a part of GSSoC'21

This issue is opened by a GSSOC participant itself @chitrasingla  Read the issue please

**Comment by AasthaGoyalgit** [comment]
Hey!!

I am interested in this issue in java problems as a GSSOC'21 participant .
I'll be glad to work on this issue.

Thanks!!

**Comment by MaitriDA** [comment]
Hey.
I am GSSOC'21 participant and skilled in C++. I would like to work on this problems. I will try to add more problems so that anyone who practice this problems will enhance his/her 2D array concept. Please assign me this issue

**Comment by Aarti002** [comment]
hey , i'm gssoc'21 participant can i take this issue i'm gonna use python and will try to pick out some serious issue faced by a competitive programmer for beginners.
Thank u!

**Comment by hritikgupta92** [comment]
Hey, I am GSSOC'21 and skilled in C and C++.I will add more problems apart from transpose,rotate.I can add some more problems as well

**Comment by tarun26091999** [comment]
you need to be specific about the problem you want to solve. 1 issue serves 1 problem only.
