### ISSUE TITLE
Luhn's Algorithm 

### ISSUE THREAD

**Issue by Suvraneel** [Algo-Phantoms/Algo-Tree#320]
## 🚀 Feature

Luhn's Algorithm in CPP language

## Assignment
[C++]
Hello maintainers!  
As a participant/CA for GSSOC '21,  
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me these issues under GSSOC '21...

## Pitch
This simple algorithm validates credit cards.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me

**Comment by shreyanspoddar** [comment]
> ## 🚀 Feature
> Luhn's Algorithm in CPP language
> 
> ## Assignment
> [C++]
> Hello maintainers!
> As a participant/CA for GSSOC '21,
> I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
> Kindly assign me these issues under GSSOC '21...
> 
> ## Pitch
> This simple algorithm validates credit cards.

Go ahead and do it in C++

**Comment by shreyanspoddar** [comment]
> I want to work on this issue. Please assign to me

Please specify the language
