### ISSUE TITLE
construction of binary Tree from it's inorder and preorder traversals

### ISSUE THREAD

**Issue by aaadddiii** [Algo-Phantoms/Algo-Tree#321]
Hi,
I would like this in c++. It is a classic problem in data structures and is asked in many coding interviews
I am a participant of GSSoC'21 and would like to contribute in this repo.

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java. I would write clean and neat code and add comments at regular intervals. Please assign me this issue as a part of GSSoC 2021.

**Comment by Aarti002** [comment]
hey @aaadddiii can i take this issue as gssoc'21 participant i would like to write code in python  plzz assign this to me i would also put some comments to make my code more clearer  to understand, thank you!

**Comment by Ayushisood** [comment]
Hii @tarun26091999 
I would like to contribute to this task as i am good with c++ data structures.
Kindly assign the task to me.

**Comment by kanganabhargava** [comment]
I am GSSOC participant. I have a sound knowledge of Data Structures and Algorithms and Cpp. I want to contribute to this.

**Comment by ThumarHarsh** [comment]
Hi,
I would like this in c++. I am a participant of GSSoC'21 and would like to contribute in this repo.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java. Could you please assign it to me?

Thanks!!

**Comment by Aarti002** [comment]
hey, i have made pull request for this issue please review my code and let
me know if something is wrong.

Thank you

**Comment by Himani-D** [comment]
I am a GSSOC'21 participant and I would like to contribute in this using Java, C++/C.
Please assign me this.

**Comment by Coder-Srinivas** [comment]
Hey @tarun26091999 , I have added the code and made necessary changes and made a pull request. Please review it and let me know if anything is wrong☺.

**Comment by Ayushisood** [comment]
@tarun26091999  Can I do the  code in python as i have done in c++, but it is merged now.
