### ISSUE TITLE
[GSSOC'21] Adding dynamic Programming problems

### ISSUE THREAD

**Issue by shriya030** [Algo-Phantoms/Algo-Tree#322]
I see that there are no dynamic programming problems in the repo so I want to add problems to it. I am a GSSOC'21 participant and would like to work on this issue. Please assign me this issue.

**Comment by Riya764** [comment]
Hey, I am interested to solve this issue. Can you please assign it to me?

**Comment by jeelnathani** [comment]
hello, I would like to contribute on dynamic programming problems such as 0-1 knapsack problem. Can you assign it to me?

**Comment by kanganabhargava** [comment]
I also want to contribute.

**Comment by OjusWiZard** [comment]
Raise separate issues for separate problems of DP.
