### ISSUE TITLE
Iterative algorithm for preorder inorder and postorder traversal of binary tree

### ISSUE THREAD

**Issue by aaadddiii** [Algo-Phantoms/Algo-Tree#323]
Hi,
I would like this in c++. It is a classic problem in data structures and is asked in many coding interviews
I am a participant of GSSoC'21 and would like to contribute in this repo.

**Comment by anotherwebguy** [comment]
I would like to work on this issue under gssoc'21, plz assign this to me

**Comment by SwarnimaShishodia** [comment]
Hi I would like to solve this problem using C++

**Comment by hritikgupta92** [comment]
Hi, Can you assign this problem to me,I can contribute to it in c and c++.

**Comment by tarun26091999** [comment]
present at #144
