### ISSUE TITLE
Username_Validator

### ISSUE THREAD

**Issue by RuchiGitHu** [Algo-Phantoms/Algo-Tree#327]
This Issue is for validating username. During the sign-in or sign-up situation this issue take place to validate the username.
This will follow some policies as mentioned below.

- The username consists of  8 to 30 characters.
- The username can only contain alphanumeric characters and underscores (_).
- The first character of the username must be an alphabetic character.
  
This code will return a boolean value that whether the **username is valid or invalid**.

**Comment by RuchiGitHu** [comment]
> This Issue is for validating username. During the sign-in or sign-up situation this issue take place to validate the username.
> This will follow some policies as mentioned below.
> 
> * The username consists of  8 to 30 characters.
> * The username can only contain alphanumeric characters and underscores (_).
> * The first character of the username must be an alphabetic character.
> 
> This code will return a boolean value that whether the **username is valid or invalid**.

Hi @nakul-19 @rudrakshi99 @plazzy99, I want to work on this issue.
Please assign this to me. I will use java language to solve this issue....
Looking forward to contribute here under GSSOC 21.

**Comment by RuchiGitHu** [comment]
> This Issue is for validating username. During the sign-in or sign-up situation this issue take place to validate the username.
> This will follow some policies as mentioned below.
> 
> * The username consists of  8 to 30 characters.
> * The username can only contain alphanumeric characters and underscores (_).
> * The first character of the username must be an alphabetic character.
> 
> This code will return a boolean value that whether the **username is valid or invalid**.

Please /assign this issue to me.
Looking forward for your reply...

**Comment by RuchiGitHu** [comment]
> > This Issue is for validating username. During the sign-in or sign-up situation this issue take place to validate the username.
> > This will follow some policies as mentioned below.
> > 
> > * The username consists of  8 to 30 characters.
> > * The username can only contain alphanumeric characters and underscores (_).
> > * The first character of the username must be an alphabetic character.
> > 
> > This code will return a boolean value that whether the **username is valid or invalid**.
> 
> Please /assign this issue to me.
> Looking forward for your reply...

@rudrakshi99 @raksha009

**Comment by rudrakshi99** [comment]
We are not taking this type of issue so please look for any algorithm to contribute.
