### ISSUE TITLE
Array problems in java

### ISSUE THREAD

**Issue by Na2001** [Algo-Phantoms/Algo-Tree#328]
Hey!!
I'm a Gssoc participant. I can do solved problems on array.Can you assign me this.

**Comment by MukulKolpe** [comment]
Hey, I am interested to solve this issue. Can you please assign it to me?

**Comment by Riya764** [comment]
Hey, I am interested to solve this issue. Can you please assign it to me?

**Comment by yjaiswal05** [comment]
Hey, I am interested to solve this issue. Can you please assign it to me?

I can write following programs in java :

1. Write a Java program to sort a numeric array and a string array. 
2. Write a Java program to sum values of an array.
3. Write a Java program to calculate the average value of array elements. 
4. Write a Java program to reverse an array of integer values.
5. Write a Java program to convert an array to ArrayList.

**Comment by AbhignaSowgandhika02** [comment]
I would like to add array problems in java and python too, if possible. I will add clean and neat code. Please assign me for the same.

**Comment by OjusWiZard** [comment]
Raise separate issues for separate problems.
