### ISSUE TITLE
Python code for arrays

### ISSUE THREAD

**Issue by hitblunders** [Algo-Phantoms/Algo-Tree#33]
Can I work on this?

**Comment by ChetasShree** [comment]
I am GSSoC'21 Participant. I would like to work on this issue. Please assign it to me. I will solve it in python

**Comment by vedant-jain03** [comment]
I would love to fix this issue. I will provide a good description in every line so that code is easy to understand I can write code in
python
I can do this task very easy and I will write the correct flow and good code which have average Time and space complexity.
Please assign me this issue

**Comment by shreyanspoddar** [comment]
Issue is not specific
