### ISSUE TITLE
Binary search Tree (No. of leaf nodes and Sorting)

### ISSUE THREAD

**Issue by aish2002** [Algo-Phantoms/Algo-Tree#332]
I'm a GSSoC'21 Participant. I can implement the following operations in binary search tree in C++

1. Insertion of nodes
2. Sorting using BST
3.  Count the number of leaf nodes.

Kindly assign this to me

**Comment by rahulsrivastava1** [comment]
Hey, i am a gsoc'21 participant. I can solve this particular issue.
that is no.of leaf nodes and also sorting in BST
kindly assign me to this!

**Comment by Aarti002** [comment]
hello can i work on this issue using c++ i would create  bst from scratch step by step with proper explanation using comments
so, please can you assign this to me.
Thank you!

**Comment by tarun26091999** [comment]
only 1 implementation is allowed in 1 issue.
