### ISSUE TITLE
I can add Greedy Algorithm in the Algo-Tree

### ISSUE THREAD

**Issue by Ayushisood** [Algo-Phantoms/Algo-Tree#338]
Hey @tarun26091999 
I can add Greedy Algorithm as i am very much familiar with data structures.
Kindly assign this task to me so as to i can contribute to it as a GSSOC'21 participant

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by tarun26091999** [comment]
@Ayushisood @pallavidhere23 you people need to be specific about the problem you are raising the issue about. Greedy is a way of solving problems, not a specific problem in itself.

**Comment by Ayushisood** [comment]
> @Ayushisood @pallavidhere23 you people need to be specific about the problem you are raising the issue about. Greedy is a way of solving problems, not a specific problem in itself.

Dijkstra's algorithm greedy approach

**Comment by tarun26091999** [comment]
> > @Ayushisood @pallavidhere23 you people need to be specific about the problem you are raising the issue about. Greedy is a way of solving problems, not a specific problem in itself.
> 
> Dijkstra's algorithm greedy approach

raise a new issue with proper name.
