### ISSUE TITLE
Garbage Collector in java (Dynamic Memory management)

### ISSUE THREAD

**Issue by Alleny244** [Algo-Phantoms/Algo-Tree#340]
Java program to demonstrate the use of garbage collector. This is a important concept in dynamic memory allocation in java .
Being a part of the GSSOC'21, I would like to implement this in java .Please do assign this to me

**Comment by Amanduttbhagat** [comment]
Hello,
I am a GSSoC 2021 participant and would like to contribute to this issue
I will use proper definition + examples 
kindly assign me the issue

**Comment by OjusWiZard** [comment]
We are accepting only DSA based codes for now
