### ISSUE TITLE
Calculator using Swing in java

### ISSUE THREAD

**Issue by Alleny244** [Algo-Phantoms/Algo-Tree#341]
To implement a java program that works as a simple calculator.  Properly arranged  buttons for digits and does
the '+', ' - ','*',' %'  operations properly. There is  a text field to display the result. Any possible exceptions 
like divide by zero is handled Java Swing is used.

Being a part of the GSSOC'21, I would like to implement this in java .Please do assign this  to me

**Comment by Na2001** [comment]
Hey, i'am a participant of GSSOC can I do this please..

**Comment by OjusWiZard** [comment]
We are accepting only DSA related codes for now
