### ISSUE TITLE
first-fit, best-fit and worst-fit memory allocations (Dynamic Memory Allocation)

### ISSUE THREAD

**Issue by Alleny244** [Algo-Phantoms/Algo-Tree#345]
To Simulate first-fit, best-fit and worst-fit memory allocations in java.

Being a part of the GSSOC'21, I would like to implement this in java .Please do assign this to me

**Comment by srividhya14** [comment]
To simulate best-fit, first-fit and worst fit memory allocations in C++.
I am a GSSOC 21 participant. Requesting  to allow me to implement this

**Comment by OjusWiZard** [comment]
We are accepting only DSA related codes for now
