### ISSUE TITLE
 Want to add problems on arrays and strings.

### ISSUE THREAD

**Issue by kanganabhargava** [Algo-Phantoms/Algo-Tree#347]
I want to add more problems on arrays and strings.

**Comment by AbhignaSowgandhika02** [comment]
I would like to add clean and easy to understand python code on arrays and strings. Please assign me for the same.

**Comment by ritika656** [comment]
I WANT TO ADD MORE PROBLEMS ON ARRAYS AND STRINGS . PLEASE GIV ME THIS OPPORTUNITY AND ASSIGN THIS WORK TO ME . GSSOC PARTICIPANT WILL EXPLAIN EACH AND EVRYTHING WITH PROPER EXPLANANTION INCLUDED WITH COMMENTS.

**Comment by Aarti002** [comment]
hey @kanganabhargava i'm a gssoc'21 participant can i get this issue i can add on some important and interesting problems with its solution in python
Thank u!

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java. Could you please assign it to me?

Thanks!!

**Comment by OjusWiZard** [comment]
Create separate issues for separate problems.
