### ISSUE TITLE
(GSSOC'21) Operations on Binary Tree

### ISSUE THREAD

**Issue by japneetbhatia** [Algo-Phantoms/Algo-Tree#348]
I want to add some basic functions like:
1. Finding Size of Binary Tree
2. Finding Height of Binary Tree
3. Finding Minimum and Maximum element in Binary Tree
4. Find data in Binary Tree
Language : java

**Comment by japneetbhatia** [comment]
Please assign this issue to me for GSSOC'21

**Comment by Aarti002** [comment]
hey i'm a gssoc'21 participant can you assign this issue to me i'm good enough in tree data structure  and  i can also add on some important and interesting problems with solutions in binary tree  so, please assign this to me.
language to  be use c++.

**Comment by 08Gunjan** [comment]
<h2>Hey @japneetbhatia <h2>
<h3> I would like work on this Isssue using  <strong>JAVA</strong> language .</h3>
<h3>could you please assign me the Issue under the label <b>GSSOC21</b> and the level of difficulty<em> i.e(Easy, Medium, Hard) </em></h3>

**Comment by khushii05** [comment]
Hello!
I'm Khushi. I'm a GSSOC 21 participant.
I would like to add all operations on the binary tree from scratch.
Language - C

**Comment by tarun26091999** [comment]
multiple problems cannot be solved in single issue.
