### ISSUE TITLE
Special Algorithms

### ISSUE THREAD

**Issue by deep3072** [Algo-Phantoms/Algo-Tree#35]
Can I work on Sieve of Eratosthenes, KMP algorithm and Mo’s algorithms?

**Comment by sunidhi1999-c** [comment]
I have been selected for GSSOC'21, and I am really interested in Algorithms , so I would like to contribute in this amazing repository.I can contribute for this ,I am 2 star codechef candidate and would be great to contribute to open source programs like this one. I can write these articles if given a chance.
Thanks.
Sunidhi,
3rd year,CSE at NMAMIT,Nitte,Karnatak

**Comment by rudrakshi99** [comment]
> Can I work on Sieve of Eratosthenes, KMP algorithm and Mo’s algorithms?

Make separate issues for each algorithm.
