### ISSUE TITLE
 Fibonacci Search 

### ISSUE THREAD

**Issue by Alleny244** [Algo-Phantoms/Algo-Tree#354]
Adding Fibonacci Search under Search Section in java
Being a part of the GSSOC'21, I would like to implement this in java .Please do assign this to me

**Comment by Op-panda** [comment]
Being a part of GSSOC'21 ,I would like to work on this problem. I will be implementing this in CPP. I will be explaining the problem with comments.  please assign this to me.

**Comment by ritika656** [comment]
i want to solve this problem in easiest of the way kindly assign m this project i will implement it in c++. highly grateful to you.

**Comment by muthuannamalai12** [comment]
I would love to implement it in python as a part of Girl Script Summer of Code. Kindly assign me this issue @tarun26091999

**Comment by Alleny244** [comment]
@tarun26091999 I have implemented the Fibonacci Search  in java with proper test cases, algorithm ,complexities and opened a pull request
https://github.com/Algo-Phantoms/Algo-Tree/pull/383

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant. I want to work on this using C++. Please assign me this .

**Comment by Alleny244** [comment]
@tarun26091999 I have corrected the errors and made a pull request again
https://github.com/Algo-Phantoms/Algo-Tree/pull/383

**Comment by aadya7104** [comment]
Hello, I am Aadya Pawar. I am a GSSOC 21 participant. I am currently in 11th grade preparing for my entrances. I love coding and am fluent in java, c++ and python. Please assign this task to me in Java.

**Comment by Nidhi-2000** [comment]
hey !!! I am Nidhi participant of gssoc '21. I would like to work on this issue in python . Kindly assign it to me

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by Alleny244** [comment]
@tarun26091999 are the new changes made necessary
I have opened the pull request
https://github.com/Algo-Phantoms/Algo-Tree/pull/383

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by Op-panda** [comment]
@tarun26091999 sir please check this out #904 . I have created a pull request for this issue.

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. I will be using Java. Thanks!
