### ISSUE TITLE
Coin Change (Greedy Approach)

### ISSUE THREAD

**Issue by FireQueen-3010** [Algo-Phantoms/Algo-Tree#355]
Hey, I am Diksha, a GSSOC'21 participant.
I would like to implement the algorithm for **Coin Change**(greedy approach) in Java.

@tarun26091999 @plazzy99 @rudrakshi99 Please assign me this issue

**Comment by Op-panda** [comment]
Hello, I am Amit , being a Gssoc'21 participant .   I would like to implement this algorithm for COIN CHANGE (Greedy approach) in CPP . Please assign this problem to me.

**Comment by MaitriDA** [comment]
hey!!
I am skilled in C++ and have a good understanding of DSA. I would like to work on this issue under GSSOC'21.

**Comment by MaitriDA** [comment]
hey!!
I am skilled in C++ and have a good understanding of DSA. I would like to work on this issue under GSSOC'21.

**Comment by zenithexpo** [comment]
I would like to implement this in Python.
