### ISSUE TITLE
Matrix Transpose

### ISSUE THREAD

**Issue by Alleny244** [Algo-Phantoms/Algo-Tree#356]
Java program to display the transpose of a given matrix.
Being a part of the GSSOC'21, I would like to implement this in java .Please do assign this to me

**Comment by ritika656** [comment]
As a particiapnt of GSSOC iwould like to implement this project in c++ kindly assign me this .
tanspose of a given matrix.

**Comment by machine-sg** [comment]
Hi, I am a GSSOC'21 participant and I want to work on this using C++. I will explain my method with proper explanation. Please assign me this.
