### ISSUE TITLE
MultiThreading

### ISSUE THREAD

**Issue by Alleny244** [Algo-Phantoms/Algo-Tree#357]
Write a Java program to create two threads: One for displaying all odd number between 1
and 100 and second thread for displaying all even numbers between 1 and 100.

**Comment by 08Gunjan** [comment]
<h2>Hi @Alleny244<h2> 
<h2> I would like to work on this Issue.  </h2>
Could You please assign me this issue under label  <strong>GSSOC21</strong> and the level of difficulty <em>i.e (Easy, medium, hard)</em>

**Comment by OjusWiZard** [comment]
We are currently accepting only DSA related issues
