### ISSUE TITLE
Implementation of Queue using Stack

### ISSUE THREAD

**Issue by Meghag5** [Algo-Phantoms/Algo-Tree#36]
In this algorithm we will use two stack to implement queue.

**Comment by Meghag5** [comment]
Please assign it to me and add tags to this issue.

**Comment by Vish-07** [comment]
Hey!!! I have implemented queue using stack before, and would love to do this task under mentorship of GSSOC'21. Will you please assign this task to me?

**Comment by noviicee** [comment]
I wish to contribute to this issue by adding code for implementation of queue using stack in python. Can you assign it to me..??
I am also a participant of GSSOC'21.
Will be waiting for a response.

**Comment by Amulya310** [comment]
I would really like to work on this issue and contribute to this amazing repository. I have prior knowledge about queues as well as stack,so ,kindly consider assigning this to me under GSSoC '21.

**Comment by ahmed-shameem** [comment]
Hi,
Please assign this task to me. I am a GSSoC'21 participant. I can solve the problem in c++.

**Comment by rudrakshi99** [comment]
@Meghag5 please mentions the language in which you want to add the code apart from c++.

**Comment by rudrakshi99** [comment]
@ahmed-shameem code is already implemented in c++. check [this](https://github.com/Algo-Phantoms/Algo-Tree/blob/main/Code/C%2B%2B/queue_using_stacks.cpp)
