### ISSUE TITLE
(GSSOC'21) Merge Sort in Linked List in java

### ISSUE THREAD

**Issue by japneetbhatia** [Algo-Phantoms/Algo-Tree#365]
please assign this issue to me under GSSOC'21

**Comment by pallavidhere23** [comment]
am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue. Could you please assign it to me?

Thanks!!

**Comment by tarun26091999** [comment]
#262 is already there.
