### ISSUE TITLE
Matrix Multiplication

### ISSUE THREAD

**Issue by Alleny244** [Algo-Phantoms/Algo-Tree#367]
Write a Java program to multiply two given matrices.

I am a Gssoc21 participant. I like to implement this code using java.

kindly assign this problem to me so that I can contribute GSSOC21

**Comment by ritika656** [comment]
i would like to implement this code in c++. I will resolve this problem and use comments over there in order to make it more understandable . kindly assign me this work. contributor GSSOC PARTICIPANT .

**Comment by tarun26091999** [comment]
issue already present at #86
