### ISSUE TITLE
Calculator using Python

### ISSUE THREAD

**Issue by Dhanush2612** [Algo-Phantoms/Algo-Tree#371]
I am GSSOC 21 Participant. Can you assign me this issue?

**Comment by soha28** [comment]
I wanted to work on this issue as a GSSOC'21 participant. Can u please assign the issue ?

**Comment by Naman-12911** [comment]
Hello sir , I can solve this issue please assign me this issue.under GSSOC

**Comment by MaitriDA** [comment]
Hey!!
I am a GSSOC'21 participant. I would like to take this issue. I would break this problem with the help of function. Please assign me this issue.

**Comment by Jainish-shah** [comment]
I am GSSOC 21 Participant. I would love to create a calculator using functions. Please assign the issue...
