### ISSUE TITLE
(GSSOC'21)Remove nth node from the end of a link list

### ISSUE THREAD

**Issue by SamarpanCoder2002** [Algo-Phantoms/Algo-Tree#378]
I would like to add this(Remove nth node from the end of a link list by C++) in that repo...... **_I am also a gssoc'21 participant_**... If I can forward with that, Please assign me in that...Thank you

**Comment by Vansh-Gupta4** [comment]
I would like to add this(Remove nth node from the end of a link list) in that repo...... I am also a gssoc'21 participant.... If I can forward with that, Please assign me in that....I would code in java

**Comment by OjusWiZard** [comment]
#201

**Comment by OjusWiZard** [comment]
Duplicate of #201
