### ISSUE TITLE
(GSSOC21) Queue implementation using stack

### ISSUE THREAD

**Issue by ac-ayan** [Algo-Phantoms/Algo-Tree#379]
Would love to add the queue implementation using stack data structure.
User would not notice any sort of functional changes regarding entering elements to the queue nor deleting elements from the queue but there will be major difference in the implementation part.
Would be very grateful if assigned to the job !
Thanks

**Comment by Vansh-Gupta4** [comment]
Would love to add the queue implementation using stack data structure.
User would not notice any sort of functional changes regarding entering elements to the queue nor deleting elements from the queue but there will be major difference in the implementation part.
Would be very grateful if assigned to the job !
Thanks
I would be using Java

**Comment by poojitha2002** [comment]
I would like to work on this issue. Can you please assign this to me. I will be working with C++ or java.

**Comment by rutuja2229** [comment]
@ac-ayan  and @Vansh-Gupta4  I will like to work on this issue as GSSoC 2021 participant can u plz assign this to me.

**Comment by sanyadeveloper2000** [comment]
Hey, I would like to work on this issue. Can you pls assign it to me?

**Comment by OjusWiZard** [comment]
Code already exists in the repository
Algo-Tree/Code/C++/queue_using_stacks.cpp

**Comment by OjusWiZard** [comment]
Raise a separate issue for other languages
