### ISSUE TITLE
Hash in JS

### ISSUE THREAD

**Issue by TidbitsJS** [Algo-Phantoms/Algo-Tree#38]
### Hashing in JS
Goal is to create a hash table in JavaScript which will have following things -
1. Insert item
2. Find item
3. Display all items

### Motivation
Purpose is to help people get better at JavaScript and DS & Algorithms

### Event
Participating as a part of GSSOC

**Comment by TidbitsJS** [comment]
Assign this to me & I will create PR immediately

**Comment by rudrakshi99** [comment]
@TidbitsJS We don't accept PRs in JS. You can contribute in Java, C++, or python.

**Comment by TidbitsJS** [comment]
> @TidbitsJS We don't accept PRs in JS. You can contribute in Java, C++, or python.

Okay :)
