### ISSUE TITLE
[GSSOC'21] Finding intersection point in a Y shaped Linked List

### ISSUE THREAD

**Issue by machine-sg** [Algo-Phantoms/Algo-Tree#386]
Hi, I am a GSSOC'21 participant and I want to work on this using C++. I have 7 methods to discuss and I will explain each and every method with proper explanation. Please assign me this.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue. Could you please assign it to me?

Thanks!!

**Comment by tarun26091999** [comment]
conflicting with #136
