### ISSUE TITLE
All graph algorithms in C++ and Java.

### ISSUE THREAD

**Issue by tanyarajhans** [Algo-Phantoms/Algo-Tree#39]
**Task**: Can implement all graph algorithms like Floyd-Warshall, Dijkstra, Prim's MST in C++ and Java.

**Motivation**: I am efficient in Problem Solving using C++ and Java and have solved more than 800 problems on various online judges like GeeksforGeeks, LeetCode, HackerRank etc. You can check my profile here:

https://leetcode.com/tanyarajhans7/
https://auth.geeksforgeeks.org/user/tanyarajhans7/practice/
https://www.hackerrank.com/tanyarajhans7

**Event**: I am a participant in GSSoC'21.

I would love to work on this issue. I promise to deliver on time and up to your expectations if you assign this to me. Thank you!

**Comment by tanyarajhans** [comment]
Please assign this issue to me.

**Comment by abhijeet010304** [comment]
I want to complete this task please assign it to me as a part of GSSOC- 21.
I am an ACM-ICPC Regionalist 2019 , specialist @codeforces and 5 Start @codechef.

**Comment by samfubuki** [comment]
Will be able to implement all the graph algorithms in C++ . I have solved lots of problems at geeksforgeeks and hackerrank and even implemented these algorithms in questions like these at GeeksForGeeks. My Profiles
GeeksForGeeks - https://auth.geeksforgeeks.org/user/axelshaun127/profile
Hackerrank - https://www.hackerrank.com/axelshaun127

I would be able to implement the code of Graph algorithms in C++ if given the task

**Comment by Siddhartha1999** [comment]
I want to work on this issue....
Got some interesting perceptions about the solutions...

Please assign it to me

**Comment by rudrakshi99** [comment]
> **Task**: Can implement all graph algorithms like Floyd-Warshall, Dijkstra, Prim's MST in C++ and Java.
> 
> **Motivation**: I am efficient in Problem Solving using C++ and Java and have solved more than 800 problems on various online judges like GeeksforGeeks, LeetCode, HackerRank etc. You can check my profile here:
> 
> https://leetcode.com/tanyarajhans7/
> https://auth.geeksforgeeks.org/user/tanyarajhans7/practice/
> https://www.hackerrank.com/tanyarajhans7
> 
> **Event**: I am a participant in GSSoC'21.
> 
> I would love to work on this issue. I promise to deliver on time and up to your expectations if you assign this to me. Thank you!

Make separate issues for each algorithm.
