### ISSUE TITLE
Multiply matrix in java

### ISSUE THREAD

**Issue by prateek-jpg** [Algo-Phantoms/Algo-Tree#396]
A program to multiply two matrix in java.

I am a GSSOC'21 participant, and I would like to contribute the Java code for this problem. I will make sure that the code is commented properly and follows all the given guidelines. Please give me this opportunity. Thankyou!

@tarun26091999

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by tarun26091999** [comment]
already present at #86
