### ISSUE TITLE
Gcd code in java

### ISSUE THREAD

**Issue by shreyanspoddar** [Algo-Phantoms/Algo-Tree#4]
GCD code in java.
Please assign this issue to me

**Comment by avijit1999** [comment]
GCD code in java 
Please assigned this to me.
I will do it by using Euclidean  algorithn

**Comment by IShahnawazShaikh** [comment]
I would like to work on this issue please assign to me @rudrakshi99  
will Implement for different Time Complexity.

**Comment by avijit1999** [comment]
@rudrakshi99 mam , I made a pull request .
Accept it and marge it.

**Comment by mohdarif8299** [comment]
I would like to work on this issue.
Please Assign it to me. @rudrakshi99

**Comment by abhijeet010304** [comment]
I want to complete this task please assign it to me as a part of GSSOC- 21.

**Comment by IdealisticINTJ** [comment]
I would like to work on this. Please assign this to me, under GSSoC '21.

**Comment by sumitsantape30** [comment]
I would like to code it in JAVA, please assign me this issue. I am GSSOC21 participant
