### ISSUE TITLE
(GSSOC'21) Main Linked Lists Operations in  C++

### ISSUE THREAD

**Issue by Akp6528** [Algo-Phantoms/Algo-Tree#400]
Hey, I'm GSSOC'21 Participant
I would like to add Linked List problem solutions for common programs in C++ as a part of GSSOC'21.
@tarun26091999 .

ex.  Find nth node from the end of the list
      Count: returns the number of elements in the list
      Main Linked Lists Operations

**Comment by tarun26091999** [comment]
you need to be specific @Akp6528 . You can ask for common programs. You need to raise separate issue for every code.
