### ISSUE TITLE
array manipulation

### ISSUE THREAD

**Issue by Sloth-Panda** [Algo-Phantoms/Algo-Tree#401]
would like to implement in java please assign me under gssoc21

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by Sloth-Panda** [comment]
@krishna-NIT try to make it in  certain other languages I have already asked to for java Or create other new issues

**Comment by krishna-NIT** [comment]
> @krishna-NIT try to make it in certain other languages I have already asked to for java Or create other new issues

No issue friend, ya, you will get opportunity first, I just have commented so, that if any one needs help regarding this issue, then I can help them .. @Sloth-Panda

**Comment by OjusWiZard** [comment]
@Sloth-Panda Please explain the issue more briefly. What will the Algorithm do?
