### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by kevla-4121** [Algo-Phantoms/Algo-Tree#406]
Implement quick sort using c++

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by SarthakSrivastav** [comment]
Hello mentors, I have good knowledge of java I would like to write the code and algorithm for this problem in Java.
Please assign this to me.

**Comment by rudrakshi99** [comment]
> Implement quick sort using c++

already present.
