### ISSUE TITLE
Algo-Tree/Strings (GSSOC'21)

### ISSUE THREAD

**Issue by isha2199** [Algo-Phantoms/Algo-Tree#410]
'''
There is no question in the strings section.
I want to add some questions in C++
The most basic one:
1.Anagrams
2.Substring search
and the list goes on
'''
Hey @tarun26091999 @rudrakshi99 , I am a GSSOC'21 participant, want to contribute to this open-source. I want to add these two questions in Strings!!
Please assign it to me!!

**Comment by Anshika-Srivastava** [comment]
I would like to contribute major and popular questions on string to this repo.
Hence I request the mentors @tarun26091999 @rudrakshi99 to please assign it to me. I am a GSSOC'21 participant and will provide the cleanest and easiest solutions for difficult problems. 
Thank You!

**Comment by tarun26091999** [comment]
you have to raise separate issues for separate questions.
