### ISSUE TITLE
Kadane's algorithm in Python (GSSOC'21)

### ISSUE THREAD

**Issue by btanisha** [Algo-Phantoms/Algo-Tree#411]
I noticed that the array folder has Kadane's algorithm only in C++. I would like to contribute by writing a well-explained and clean code for the same. Please assign this issue to me under GSSOC 2021.

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by tarun26091999** [comment]
present at #178
