### ISSUE TITLE
Count of set bits of a number

### ISSUE THREAD

**Issue by Atif-reyaz-khan** [Algo-Phantoms/Algo-Tree#421]
I noticed that the bit manipulation  folder doesn't have count of set bits problem Algorithms. I would like to contribute by writing a well-explained and clean code for this problem in C++. Please assign this issue to me under gssoc'21.

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by HitainKakkar** [comment]
I'm the participant in GSSOC'21. Kindly assing me this issue. I have the code ready!!

**Comment by Atif-reyaz-khan** [comment]
I created pull request already

**Comment by shahina-bano** [comment]
Please assign me this issue, I will code this in JAVA.

**Comment by raksha009** [comment]
Always specify language while commenting to get an issue assigned :)

**Comment by Shraddha13Jain** [comment]
/assign
please assign me this issue. i will code it in c++.

**Comment by raksha009** [comment]
> /assign
> please assign me this issue. i will code it in c++.

The issue is already assigned in cpp. Assignment only for python language is left. Plz view the tags and assigned languages.

**Comment by Shraddha13Jain** [comment]
ok I will code it in python .please assign this to me @raksha009 .

> > /assign
> > please assign me this issue. i will code it in c++.
> 
> The issue is already assigned in cpp. Assignment only for python language is left. Plz view the tags and assigned languages.

**Comment by Shraddha13Jain** [comment]
@raksha009 I have made pull request.. please review my code in python , if found correct please merge it.
PR number -1120

**Comment by tarun26091999** [comment]
issue present at #246
