### ISSUE TITLE
[Demmo,ignore]Arrays : Two Sum

### ISSUE THREAD

**Issue by NidhiChaurasia** [Algo-Phantoms/Algo-Tree#422]
**explanation**
Given an array,print of number that is equal to target.
**example**
hey,@rudrakshi99,I want to add this imp ques in the Algo -Tree/Code/C++

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by tarun26091999** [comment]
present at #203
