### ISSUE TITLE
Arrays: Two Sum

### ISSUE THREAD

**Issue by Priya761** [Algo-Phantoms/Algo-Tree#423]

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by Mugdha-Hazra** [comment]
Hello @tarun26091999 @dheerajkotwani @esheetaparulekar @anubhavitis @jeelnathani, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by tarun26091999** [comment]
present at #203
