### ISSUE TITLE
README.md file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [Algo-Phantoms/Algo-Tree#424]
The README.md file can be enhanced by adding a list of all the open source programs in which this project is a part of. Also a beautiful table of contributors can be added and there are minor grammatical errors that needs correction.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by OjusWiZard** [comment]
We are currently accepting only DSA related issues.
