### ISSUE TITLE
Longest Common Substring using Dynamic Programming

### ISSUE THREAD

**Issue by nandinit02** [Algo-Phantoms/Algo-Tree#425]
I would like to write a code for the Longest Common Substring  Problem. In this problem we have to determine the length of longest common substring between two given strings. I will implement it using Dynamic Programming in C++ with proper comments and explanation of the code.
I am a participant of **GSSOC'21**.
I request the mentors to assign me this question.
@tarun26091999 @anubhavitis @dheerajkotwani @todi-2000 @geekquad @plazzy99

**Comment by tarun26091999** [comment]
issue already present at #21

**Comment by tarun26091999** [comment]
@VibhuRajput specify the language.
