### ISSUE TITLE
Adding more questions in readme.md of Algo-Tree/Tree/  

### ISSUE THREAD

**Issue by hritikgupta92** [Algo-Phantoms/Algo-Tree#428]
Currently,Binary tree doesn't include any question and BST only got 1 question but there are many questions that can added here

**Comment by hritikgupta92** [comment]
@rudrakshi99 @tarun26091999  Can you assign this issue to me?

**Comment by tarun26091999** [comment]
you need to specific about the question you want to solve. Raise the issue which includes ques name in it.
