### ISSUE TITLE
Number of K-Length Sublists with Average at Least Target [Python] 

### ISSUE THREAD

**Issue by kushal13112001** [Algo-Phantoms/Algo-Tree#429]
Given a list of integers nums, and integers k and target, return the number of sublists whose length is k and its
average value ≥ target.

**Constraints**

n ≤ 100,000 where n is the length of nums

**Comment by kushal13112001** [comment]
Hey @anubhavitis @dheerajkotwani @tarun26091999 @todi-2000  I would like to take up this issue and solve it with a brief description and with proper code and test cases. Please assign me this issue

**Comment by tarun26091999** [comment]
@plazzy99 look into this.

**Comment by kushal13112001** [comment]
sir @plazzy99 @tarun26091999  should i proceed ?

**Comment by kushal13112001** [comment]
Hey @anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 I would like to take up this issue and solve it with a brief description and with proper code and test cases. Please assign me this issue

**Comment by OjusWiZard** [comment]
We are currently accepting only DSA related code. But not problems, where DSA can be applied
