### ISSUE TITLE
Spiral traversal of a matrix.

### ISSUE THREAD

**Issue by pshivesh8** [Algo-Phantoms/Algo-Tree#430]
What I want to contribute:
1.Spiral traversal of a matrix.
2.My code will be in C++.
3. The code will consist of a complete explanation of my approach and will be commented on for better understanding.
4. Also it will include some test cases.

**Comment by Chahat226** [comment]
Hi, I am Chahat, a GSSOC'21 Participant. I am highly experienced in competitive programming in C++. I would like to contribute the 2 different types of Spiral Traversal matrix algorithms in C++ to this project.
Please assign this task to me :)
Thank you.

**Comment by japneetbhatia** [comment]
Hey, I'm GSSOC'21 participant. I want to work on this issue in java. please assign this to me

**Comment by tarun26091999** [comment]
present at #83
