### ISSUE TITLE
Counting Sort in C++

### ISSUE THREAD

**Issue by VibhuRajput** [Algo-Phantoms/Algo-Tree#431]
gssoc'21 participant, I am opening an issue and writing a detailed code for counting sort in c++.
Please assign me for this.

**Comment by avinashbest** [comment]
- I would like to work on it

**Comment by avinashbest** [comment]
- Under GSSoC 2021

**Comment by OjusWiZard** [comment]
Code already exists here Code/C++/couting_sort.cpp
