### ISSUE TITLE
[GSSOC'21] Power(x,n) in O(logn).

### ISSUE THREAD

**Issue by Prakersh123** [Algo-Phantoms/Algo-Tree#432]
Hello, I am Prakersh Arya a GSSOC'21 Participant. I am highly interested in competitive programming and i am having experience in C++ programming language.
I want to include the algorithm of calculating power(x,n) in O(logn) time complexity.

Please assign this task to me :)
Thank-you.
@rudrakshi99@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by tarun26091999** [comment]
it is already merged in PR no #293
