### ISSUE TITLE
[GSSOC'21] Binary Search

### ISSUE THREAD

**Issue by sayantikag98** [Algo-Phantoms/Algo-Tree#433]
Hi, I am Sayantika Ghosh participating in GSSOC this year. I want to implement binary search recursively and iteratively in C++. Also, I want to implement the lower and upper bound of a given number using binary search in C++. 

Please kindly assign this task to me.

Thank you.

**Comment by yashikajotwani12** [comment]
I would like to code it in python, please assign me this issue , would explain the code and implementation.

**Comment by Rupa-421** [comment]
Hi!
I'm a gssoc 21 participant.I want to contribute on linear search and binary search implementation in both java and python language.Aiming to write a CLEAN CODE and PERFECT  README  @sayantikag98  @yashikajotwani12  @plazzy99 @Siddhant-K-code @dheerajkotwani @anubhavitis   you please assign this to me?

**Comment by khushii05** [comment]
Hello !
I'm Khushi . I am participating in GSSOC this year. I would love to implement binary search recursively and iteratively in C.
@yashikajotwani12 @dheerajkotwani @anubhavitis @sayantikag98  Pl assign this to me

**Comment by tarun26091999** [comment]
present at #106
