### ISSUE TITLE
Binary Search in C++ 

### ISSUE THREAD

**Issue by Prajwal-ctrl** [Algo-Phantoms/Algo-Tree#434]
I am GSSOC'21 participant, I would like to add a detailed code for Binary Search in c++. with proper comments 
Please assign me for this.

**Comment by adiig7** [comment]
I want to work on this.

**Comment by Atul-Kashyap** [comment]
Hey, I am Atul Kashyap, a GSSOC'21 participant. 
I want to contribute the code for the implementation of the Binary Search in the Java language.
Please assign this task to me.
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by muthuannamalai12** [comment]
I would love to work on it in python. Kindly assign it to me

**Comment by tarun26091999** [comment]
issue already present at #106
