### ISSUE TITLE
[GSSOC'21] Merge Sort in C++

### ISSUE THREAD

**Issue by malavikarajeshvikraman** [Algo-Phantoms/Algo-Tree#436]
Hi I am Malavika R Vikraman , participating in  GSSOC'21 .
I would like to contribute by adding Merge Sort in C++ to this project.

Kindly assign this issue to me!
@anubhavitis  @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by yashikajotwani12** [comment]
I would love to implement it in python, please assign me this @plazzy99 .

**Comment by Disha-swp** [comment]
I would love to implement it in c, as a part of GSSOC'21. Please assign it to me @plazzy99

**Comment by tarun26091999** [comment]
merge sort is already present in our folder.
