### ISSUE TITLE
[GSSOC'21] Linear Search and Binary Search  in Python 

### ISSUE THREAD

**Issue by malavikarajeshvikraman** [Algo-Phantoms/Algo-Tree#439]
Hi I am Malavika R Vikraman , participating in GSSOC'21 .
I would like to contribute by adding Linear Search and Binary Search  in Python  to this project.

Kindly assign this issue to me!
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by Rupa-421** [comment]
Hi!
I'm a gssoc 21 participant.I want to contribute on linear search and binary search implementation in  python language.Aiming to write a CLEAN CODE and PERFECT README @plazzy99 Can you please assign this to me?

**Comment by hrushikesh-git** [comment]
hii @anubhavitis  please assign this issue to me I am gssoc'21 participant

**Comment by tarun26091999** [comment]
binary search present at #106. raise separate issue for linear search.

**Comment by malavikarajeshvikraman** [comment]
@tarun26091999  I have created a issue #602  . Please do Kindly Assign it to me
