### ISSUE TITLE
[GSSOC'21] Brian Kernighan’s Algorithm to count set bits in an integer

### ISSUE THREAD

**Issue by Prakersh123** [Algo-Phantoms/Algo-Tree#441]
Hello, I am Prakersh Arya a GSSOC'21 Participant. I am highly interested in competitive programming and i am having experience in C++ programming language.
I want to include the algorithm of counting total number of set bits in a given integer using Brian Kernighan's algorithm in bit manipulation section.

Please assign this task to me :)
Thank-you.
@rudrakshi99@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by tarun26091999** [comment]
issue already present at #421 . you can ask for other language there.
