### ISSUE TITLE
[GSSoC'21] Moore's Voting Algorithm

### ISSUE THREAD

**Issue by Prakersh123** [Algo-Phantoms/Algo-Tree#443]
Hello, I am Prakersh Arya a GSSOC'21 Participant. I am highly interested in competitive programming and i am having experience in C++ programming language.
I want to write the Moore's Voting Algorithm for finding majority element.

Please assign this task to me :)
Thank-you.
@rudrakshi99@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by tarun26091999** [comment]
already present at #392
