### ISSUE TITLE
[GSSoC] Add Sorting  in Python

### ISSUE THREAD

**Issue by AmanUpadhyay8** [Algo-Phantoms/Algo-Tree#444]
[GSSoC 2021] I would like to add sorting programs in Python like Linear sort, Bubble sort etc. Please assign this to me.
 
@tarun26091999  @shreyanspoddar @nakul-19 @OjusWiZard  @raksha009 @rudrakshi99  please mentors assign this to me.

**Comment by Rupa-421** [comment]
Hi!
I'm gssoc 2021 participant .I would like to contribute sorting Algorithms like insertion sort,shell sort, bubble sort...
So please assign this to me.

**Comment by tarun26091999** [comment]
you can add one algorithm in one issue.
