### ISSUE TITLE
Kosaraju’s algorithm

### ISSUE THREAD

**Issue by ssaksham** [Algo-Phantoms/Algo-Tree#445]
Hey, I am Saksham Sharma, a GSSOC'21 participant. I am a Competitive Programmer and C++ enthusiastic.
I want to write **Kosaraju's algorithm** to find the strongly connected components in a graph in C++.

Please assign this task to me.

@anubhavitis @dheerajkotwani  @tarun26091999  @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by Sn0wGod** [comment]
Hey, I am **Yogesh Yogendra**, a **GSSOC'21 participant** . I am a Competitive Programmer and a Full Stack Developer.
I want to write this Kosaraju's algorithm .

Please assign this task to me.

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by shiv-30** [comment]
Hello, I'm Shivam Kumar. I am a GSSOC'21 participant and I want to implement this issue in JAVA with proper comment, indentation and time-complexity. Please assign this issue to me. @rudrakshi99

**Comment by shreyadubey0902** [comment]
Hello, I'm Kishan Kumar Seth, participant at GGSOC'21.
I would like to solve this problem.
Please assign me this issue.

**Comment by tarun26091999** [comment]
@shreyadubey0902 specify the language.

**Comment by shreyadubey0902** [comment]
> @shreyadubey0902 specify the language.

Java....
Can you please assign this to me

**Comment by Masters-Akt** [comment]
I would like to implement it in python. Please assign this to me.

**Comment by Nishayadav-bit** [comment]
Hey , I'm a GSSOC'21 participant . I would like to work on this issue please assign me .
