### ISSUE TITLE
[GSSOC'21] Check if the given graph is Bipartite or not.

### ISSUE THREAD

**Issue by ssaksham** [Algo-Phantoms/Algo-Tree#446]
Hey, I am Saksham Sharma, a GSSOC'21 participant. I am a Competitive Programmer and C++ enthusiastic.
I want to write an algorithm to check if the given graph is Bipartite or not in the C++ language
Please assign this task to me.

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by tarun26091999** [comment]
already present at #95
