### ISSUE TITLE
[GSSOC'21] Prim's algorithm

### ISSUE THREAD

**Issue by ssaksham** [Algo-Phantoms/Algo-Tree#448]
Hey, I am Saksham Sharma, a GSSOC'21 participant. I am a Competitive Programmer and C++ enthusiastic.
I want to write Prim's algorithm for finding a minimum spanning tree from a graph in the C++ language.

Please assign this task to me.

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by tarun26091999** [comment]
already open at #351
