### ISSUE TITLE
LinkedList Deletion Operation

### ISSUE THREAD

**Issue by WaderManasi** [Algo-Phantoms/Algo-Tree#45]
### Deletion Operations in LinkedList
- Deletion of first node in linkedlist
- Deletion of last node in linkedlist
- Deletion of intermediate node in linkedlist
### Event : 
Gssoc'21

Can you assign the above task to be written in CPP and Java?

**Comment by Subhangini** [comment]
Please assign this issue to me .I will write the code in C++.

**Comment by iamartyaa** [comment]
Ma'am
I would like to work on this issue . I have read the guidelines for making a contribution and will abide by them . 
I am actively contributing to GeeksforGeeks & I am proficient in C++ . Please assign this issue to me .

I have been selected for GSSOC'21, and I am really interested in Data Structures & Algorithms , so I would like to contribute in this amazing repository.
Regards
Amartya Yadav

**Comment by RhuthuHegde** [comment]
Can I work on this issue, under gssoc'21?

**Comment by ahmed-shameem** [comment]
Hi,
Please assign this task to me. I am a GSSoC'21 participant. I can solve the problem using c++.

**Comment by vedant-jain03** [comment]
Hello sir/mam,
I have gone through your problem statement.
And as a participant of GSSOC21 and I am also good at Data Structures and Algorithm I have also have pull request in this existing project and I love this project.
This same question I have done in Leetcode as well and I know the main Algorithm behind this.
Looking forward to your reply.!!!:)

**Comment by Manzee1609** [comment]
I would like to work on this issue, under gssoc'21.
I have implemented the same thing as a part of my college assignment, so I am very well aware with the logic and code.

**Comment by yashikajotwani12** [comment]
Please Assign me this issue I can code it in python. I am a gssoc'21 participant.

**Comment by Vansh-Gupta4** [comment]
Hello sir/mam,
I have gone through your problem statement.
And as a participant of GSSOC21 and I am also good at Data Structures and Algorithm I have also have pull request in this existing project and I love this project.
This same question I have done in Leetcode as well and I know the main Algorithm behind this.
Looking forward to your reply.!!!:)

**Comment by neha030** [comment]
I am GSSOC'21 participant , I want to work on the in C++ code.
I have good understanding about C and C++ language..so I request , to please assign me the work.
The code will be properly indented with proper comments and description.
I will provide the code in all the deletion cases with best time complexity.

**Comment by tarun26091999** [comment]
duplicate issue.
