### ISSUE TITLE
[GSSOC'21]Sieve of Eratosthenes

### ISSUE THREAD

**Issue by Tanya933** [Algo-Phantoms/Algo-Tree#461]
@rudrakshi99 @nakul-19 @plazzy99
I am a GSSoC'21 participant and would like to work on this issue in C++ ,following all the contribution and code base guidelines.
I will put my 100% effort and will give the best outcome solving this issue.Please assign this issue to me.
Thank you!

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99
for algo tree

**Comment by shreyanspoddar** [comment]
This issue has been already assigned before refer #47
