### ISSUE TITLE
Best Time to Buy and Sell Stock 

### ISSUE THREAD

**Issue by nandini2110** [Algo-Phantoms/Algo-Tree#462]
I am Nandini Dasgupta a GSSOC'21 Participant. I am passionate about Java programming and would like to add this problem which uses Array and Greedy concepts.

The problem statement:  An array prices is given where prices[i] is the price of a given stock on the ith day. Find the maximum profit you can achieve. You may complete as many transactions as you like (i.e., buy one and sell one share of the stock multiple times).

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad

**Comment by vedant-jain03** [comment]
I can do this issue in C++,C and python please aasign me this issue. Thankyou

**Comment by eksdee-sama** [comment]
I can do this issue in C++ please assign me this issue.

**Comment by tarun26091999** [comment]
@vedant-jain03 do it in python

**Comment by Amanduttbhagat** [comment]
Hello,
I can contribute to this issue in java
kindly assign me the issue
@tarun26091999

**Comment by eksdee-sama** [comment]
@tarun26091999 i did it in C++ and pull req#787

**Comment by eksdee-sama** [comment]
@tarun26091999  please check PR #787

**Comment by khushboojoshi3** [comment]
Hey, I'm a GSSOC'21 participant. I would like to work on this issue in C++, please assign it to me.

**Comment by Deepaliiii** [comment]
I would like to work on this issue in c++, please assign it to me.
