### ISSUE TITLE
[GSSOC'21] Searching algorithms : Leaner and Binary Search implementing in java.

### ISSUE THREAD

**Issue by SUCHITRAGIRI** [Algo-Phantoms/Algo-Tree#469]
Hey, I am Suchitra Giri participating in GSSOC'21.
I want to add codes of Searching Algorithms - Leaner and Binary Search in java language.

I would be very grateful to contribute to this issue if you @todi-2000 @anubhavitis @dheerajkotwani @avijit1999  assign this task to me!

**Comment by Rupa-421** [comment]
Hi!
I'm a gssoc 21 participant.I want to contribute on  linear search and binary search implementation in both java and python language.Aiming to write a **CLEAN CODE** and **PERFECT README** .Can you please assign this to me?

**Comment by hrushikesh-git** [comment]
Hii @SUCHITRAGIRI I would like to implement this searching algorithm and begin my contribution in GSSOC'21, please assign this task to me

**Comment by tarun26091999** [comment]
binary search present at #106. raise separate issue for linear search.
