### ISSUE TITLE
convert binary number in a linked list-to Integer in Java

### ISSUE THREAD

**Issue by sohini3062** [Algo-Phantoms/Algo-Tree#470]
[GSSoc 2021] participant

**Comment by nishantsahu961** [comment]
hey I would like to add the code for converting binary number in a linked list to Integer in java as a GSSOC participant , please guide me

**Comment by OjusWiZard** [comment]
Please try to add a more DSA specific problem. This is an application of a Data Structure, but not any concept of its own.
