### ISSUE TITLE
Check whether the linked list is cyclic or not.

### ISSUE THREAD

**Issue by Astroakanksha24** [Algo-Phantoms/Algo-Tree#474]
I am a GSSOC 21 participant, please assign this to me I can do it in all ways possible.

**Comment by Roshni1809** [comment]
Hi , I am Roshni, participant of GSSOC'21.
I would love to solve this problem using CPP.Will explain each step with comments.
Please assign me  this issue.
Hope to hear from you.

**Comment by tarun26091999** [comment]
issue is already present in #189
