### ISSUE TITLE
Remove Nth Node From End of Linked List  in (C++)

### ISSUE THREAD

**Issue by Akp6528** [Algo-Phantoms/Algo-Tree#486]
Hey, I'm GSSOC'21 Participant and want to work on this issue in C++ 
any mentor assign me this.

**Comment by Disha-swp** [comment]
hello, I'm a gssoc'21 participant, and i would like to contribute. 
please assign it to me.

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by OjusWiZard** [comment]
Very similar to #201
