### ISSUE TITLE
QUICK SORT IN PYTHON

### ISSUE THREAD

**Issue by vedant-jain03** [Algo-Phantoms/Algo-Tree#487]

**Comment by vedant-jain03** [comment]
Hello , I want to contribute to this issue using python.

**Comment by shahina-bano** [comment]
Please assign this issue, I will solve it using CPP.

**Comment by yashmita** [comment]
I can solve this problem using Java. Kindly assign me this issue.

**Comment by raksha009** [comment]
Issue for all sorting algorithms present at #124
