### ISSUE TITLE
Longest Repeating Subsequence using Dp 

### ISSUE THREAD

**Issue by sayantan1413** [Algo-Phantoms/Algo-Tree#495]
I will implement the Longest repeating subsequence using Dp in C++ programming language.

**Comment by shiv-30** [comment]
I will implement the Longest repeating subsequence using DP in JAVA with proper comment, indentation and time complexity.
Please assign this issue to me @rudrakshi99 .

**Comment by shiv-30** [comment]
I am a GSSOC'21 participant.

**Comment by Jagruthi13** [comment]
Hey @rudrakshi99
I am a GSSoC'21 participant. I would like to do this problem in Python.
Can you assign me this issue

**Comment by priyamourya** [comment]
I am GSSOC'21 participant and l would like to work on this problem and would make sure to implement a neat and clean code ,and make it easy to understand using comments.
