### ISSUE TITLE
Tree( Inorder Preorder Postorder) Recursively

### ISSUE THREAD

**Issue by 08Gunjan** [Algo-Phantoms/Algo-Tree#498]
I would like to contribute in your Project by working  on <b>Tree (Inorder  Preorder  Postorder)  (Binary Tree )</b> Problems  using Recursive Approach in <b> JAVA </b>.

- My Approach is Optimize yet Easy to understand .
- Single Line Comments makes it easy to read.
- Required Test Case are added at the end.
- Can make it More Explanatory using the Image 
  
<h4>Please assign me this issue under the label <b>GSSOC21</b> , Looking Forward To your Response @tarun26091999  @rudrakshi99  </h4>

**Comment by Rupa-421** [comment]
Hi!
I'm a gssoc participant.I like to contribute in python language

**Comment by tarun26091999** [comment]
present at #144
