### ISSUE TITLE
(N-ary) Tree( Inorder Preorder Postorder) Recursively

### ISSUE THREAD

**Issue by 08Gunjan** [Algo-Phantoms/Algo-Tree#500]
I would like to contribute in your Project by working  on <b>Tree (Inorder  Preorder  Postorder)  (N-ary Tree )</b> Problems  using Recursive Approach in <b> JAVA </b>.

- My Approach is Optimize yet Easy to understand .
- Single Line Comments makes it easy to read.
- Required Test Case are added at the end.
- Can make it More Explanatory using the Image 
  
<h4>Please assign me this issue under the label <b>GSSOC21</b> , Looking Forward To your Response @tarun26091999  @rudrakshi99  @nakul-19  @raksha009  @ </h4>

**Comment by tarun26091999** [comment]
raise separate issue for all traversal.

**Comment by 08Gunjan** [comment]
Does this **"all"** include Traversals for both Binary Tree and N-ary tree  **(JAVA)** ? 
  
 **Traversals**
- Inorder Traversal        (Recursively)
- Preorder Traversal      (Recursively)
- Postorder Traversal     (Recursively)
- Level Order Traversal   (Iteratively)

@tarun26091999    Could you Please Confirm it  And also Do mention If I have missed something !!  So that I can raise the new Issue. 
 <h4>Thanks for your attention. I'm looking forward to your reply</h4>
