### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by sonal251001** [Algo-Phantoms/Algo-Tree#501]
Hi, Project Maintainers. I would like to include this important algorithm in the arrays section of the code. The folder in which I'll add code is Algo-Tree/code/java. I would like you to assign this issue to me. Thank you.

**Comment by JASHANJOT7KAUR** [comment]
I would like to work on this issue in c++,kindly assign it to me.
Thank you

**Comment by tarun26091999** [comment]
#178 is same
