### ISSUE TITLE
Best Time to Buy and Sell Stock.

### ISSUE THREAD

**Issue by sonal251001** [Algo-Phantoms/Algo-Tree#503]
Hi, Project Maintainers. I would like to include this important algorithm in the arrays section of the code. The folder in which I'll add code is Algo-Tree/code/java. I would like you to assign this issue to me. Thank you.

**Comment by madhvi02** [comment]
Sir @tarun26091999
Please assign this problem to me. I would like to solve this in c++.
I will surely provide the code with proper documentation and comments.

**Comment by tarun26091999** [comment]
already present at #462
