### ISSUE TITLE
Search in Sorted Rotated Array

### ISSUE THREAD

**Issue by sukritidawar** [Algo-Phantoms/Algo-Tree#51]
Given an integer array, and an element x, find the index of the element in O(log n) time.
Integer array is sorted in ascending order, but it is rotated at some pivot.
Example: 
Input: arr[] = {5, 6, 7, 8, 9, 10, 1, 2, 3}, x = 3
Output: 8

**Comment by sukritidawar** [comment]
I want to work on this issue in C++

**Comment by rohitsigar** [comment]
please assign this task to me,   I have experience of writing blogs on DSA and competitive programming.
I am selected as a Mentee at GirlScript Summer of Code and this project really excites me so I would love to contribute to such an amazing repo.
@rudrakshi99 
@nakul-19 
@plazzy99

**Comment by yogitasaini** [comment]
Please assign this issue  to me in java

**Comment by nakul-19** [comment]
@rohitsigar please mention the language you would use.

**Comment by ahmed-shameem** [comment]
Hi,
Please assign this task to me. I am a GSSoC'21 participant. I can solve the problem using c++.

**Comment by rohitsigar** [comment]
@nakul-19 sir I will do it in c++ as well as in java with valuable comments.

**Comment by yogitasaini** [comment]
please, this task to me in java under GSSOC'21

**Comment by sg-iitg** [comment]
I am a GSSOC'21 participant. I would like the contribute the python code for this problem statement. Please assign this issue to me. Thankyou!

**Comment by Adrenalinerush07** [comment]
I am a GSSoC'21 participant.
I assure you I can handle this issue as I am extremely good at DSA, problem-solving, and C++.

It would be really great if you assign this issue to me.
Hoping for a good outcome from your side.

**Comment by yashika03** [comment]
I am a GSSOC'21 participant and would like to contribute C++ code to this issue. Please assign me this issue.

**Comment by khushi123456789** [comment]
I am  GSSOC'2021 participant. I am good at C++,C.Please assign this issue to me.
 Thankyou!

**Comment by MukulKolpe** [comment]
Hey, I am GSSOC'21 participant. Can you please assign these issue to me? My preferred language is Java.

**Comment by kirtijha014** [comment]
Hello maintainers!
As a participant  for GSSOC '21,
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C or C++, or Java
Kindly assign me these issues under GSSOC '21

**Comment by kushal13112001** [comment]
I am a GSSOC'21 participant and would like to contribute python code to this issue. Please assign me this issue.I will provide the best and understandable code

**Comment by rohitsigar** [comment]
@nakul-19 @plazzy99 I have completed this task and wrote code in c++ and java and done PR in their respective folders so please check my PR [#361 ](https://github.com/Algo-Phantoms/Algo-Tree/pull/361)

**Comment by sukritidawar** [comment]
> @nakul-19 @plazzy99 I have completed this task and wrote code in c++ and java and done PR in their respective folders so please check my PR [#361 ](https://github.com/Algo-Phantoms/Algo-Tree/pull/361)

Hi, I think you were assigned for java only
