### ISSUE TITLE
Merge sort

### ISSUE THREAD

**Issue by Sloth-Panda** [Algo-Phantoms/Algo-Tree#510]
Would like to implement it in java @rudrakshi99 please assign me

**Comment by khushii05** [comment]
I would implement this in C @rudrakshi99 pl do assign .

**Comment by rudrakshi99** [comment]
> Would like to implement it in java @rudrakshi99 please assign me

please mention the language.

**Comment by Ritu7683** [comment]
I would like to implement it in C++. Kindly assign this to me

**Comment by rudrakshi99** [comment]
Already present.
