### ISSUE TITLE
Infix to Postfix Notation Using Stacks

### ISSUE THREAD

**Issue by nabin-nath** [Algo-Phantoms/Algo-Tree#511]

**Comment by divya1509** [comment]
Hey, I am Divya, a participant of GSSOC'21. I would like to work on this issue in JAVA. I would make sure that the code is well explained. Please assign me this issue.
Thanks.

**Comment by raksha009** [comment]
> _No description provided._

Plz always specify laguage in description box. Assigning you cpp as you mentioned it in title,

**Comment by jankivaghasiya** [comment]
Hello, I'm Janki, a participant of GSSoC'21. I would like to contribute to this issue in C++. Kindly, assign me this.

**Comment by raksha009** [comment]
> Hello, I'm Janki, a participant of GSSoC'21. I would like to contribute to this issue in C++. Kindly, assign me this.

Heyy, the issue is already assigned in Java and cpp. Only assignment for python language is left.

**Comment by jankivaghasiya** [comment]
> > Hello, I'm Janki, a participant of GSSoC'21. I would like to contribute to this issue in C++. Kindly, assign me this.
> 
> Heyy, the issue is already assigned in Java and cpp. Only assignment for python language is left.

Hello, @raksha009 mam. Can I try in Python, please? I am familiar with it as well.

**Comment by jankivaghasiya** [comment]
@raksha009 mam, should I add my code under stack directory or code/python directory?

**Comment by raksha009** [comment]
> @raksha009 mam, should I add my code under stack directory or code/python directory?

It has to go under stack one. Pl go through the pinned issues for a better clarity. :)

**Comment by jankivaghasiya** [comment]
@raksha009 mam, I've submitted the code as per the guidelines. Kindly review it and tell me the necessary changes if any.

**Comment by Nishayadav-bit** [comment]
Hey , I'm a GSSOC'21 participant . I would like to work on this issue please assign me .

**Comment by tarun26091999** [comment]
> Hey , I'm a GSSOC'21 participant . I would like to work on this issue please assign me .

specify the language, C++ and java available.
