### ISSUE TITLE
Evaluating Postfix expression using stacks[C++]

### ISSUE THREAD

**Issue by Mohim-Singla** [Algo-Phantoms/Algo-Tree#523]
In this Program I would like to evaluate the postfix expression using STACK data structure.
I'll start working on this as soon as it gets assigned to me.

Hey @rudrakshi99 please assign the above mentioned issue to me.

**Comment by rudrakshi99** [comment]
@Mohim-Singla Sorry I am unassigning you because this issue was already assigned to someone else but the tags were not mentioned there. You will work on another issue.

**Comment by Mohim-Singla** [comment]
@rudrakshi99  Alright! I just completed implementing this program tho!!!
