### ISSUE TITLE
Majority Element in an array 

### ISSUE THREAD

**Issue by vikashkumar2020** [Algo-Phantoms/Algo-Tree#524]
I am a participant and I want to implement the majority element algorithm in C++ with O(n) time complexity and O(1) space complexity.

A **majority element** in an array A of size N is an element that appears more than N/2 times in the array using searching concept

**Comment by ritikpanchal768** [comment]
hi, I want to work on this issue. 
kindly assign to me.

**Comment by ritikpanchal768** [comment]
I will do it using c++

**Comment by divya1509** [comment]
Hey, I am Divya, a participant of GSSOC'21. I can contribute a JAVA code for the same. I will make sure that my code is easily understandable and explanatory. Please assign me this issue.
Thanks.

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by tarun26091999** [comment]
you are talking about Moore's voting algo, it is already present at #392
