### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by vikashkumar2020** [Algo-Phantoms/Algo-Tree#525]
I want to implement the **Tower of Hanoi** algorithm in C++ with O(2^N) time complexity and O(N) space complexity.

 **Tower of Hanoi**
The tower of Hanoi is a famous puzzle in which have three rods and N disk plates.

**Comment by Chirag018** [comment]
Hi,I'm a GSSoC participant.
I wish to add the implementation of Tower of Hanoi in Java with time and space complexity.

**Comment by IdealisticINTJ** [comment]
I would like to implement this in Python, as a GSSoC '21 Participant. Kindly assign this to me.
