### ISSUE TITLE
N-queens problem with printing of each successful combination using Java

### ISSUE THREAD

**Issue by PratikGarai** [Algo-Phantoms/Algo-Tree#526]
As a part of GSSOC 2021, I would like to include the n-queens problem using recursion in java. I have already prepared the code and here are 2 outputs for verification. 

![image](https://user-images.githubusercontent.com/58355527/110727059-8e309b00-8240-11eb-959e-5d9b1ddefad1.png)
![image](https://user-images.githubusercontent.com/58355527/110727242-de0f6200-8240-11eb-8de9-4e55c8b69488.png)
Here, '0' represents an empty cell in the board and '1' represents a queen.

The code takes 2 command line arguments, 
1. The size of board
2. Whether to print the patterns generated (>0 for print , <=0 for not printing)

**Comment by Jagruthi13** [comment]
Hey @rudrakshi99
I am a GSSoC'21 participant. I would like to do this problem in cpp.
Can you assign me this issue

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by tarun26091999** [comment]
issue present at #381
