### ISSUE TITLE
[GSSOC'21] Rotation of matrix clockwise

### ISSUE THREAD

**Issue by chitrasingla** [Algo-Phantoms/Algo-Tree#527]
Hey,
I am a GSSOC'21 participant, I would like to add a problem - rotation of 2D matrix clockwise in C++
@tarun26091999 Can you please assign this issue to me.

Thank you

**Comment by Chirag018** [comment]
Hi,I'm a GSSoC participant.
I would like to implement the Rotation of Matrix Clockwise problem in Java .

**Comment by Jagruthi13** [comment]
Hey @rudrakshi99
I am a GSSoC'21 participant. I would like to do this problem in python.
Can you assign me this issue

**Comment by tarun26091999** [comment]
already present at #128
