### ISSUE TITLE
Longest Increasing Subsequence

### ISSUE THREAD

**Issue by chitrasingla** [Algo-Phantoms/Algo-Tree#528]
Hey,
I am a GSSOC'21 participant, I would like to add a problem - longest increasing subsequence in an array in DP section in C++
@tarun26091999 Can you please assign this issue to me.

Thank you

**Comment by Chirag018** [comment]
Hi,I'm a GSSoC participant.
I wish to add the implementation of Longest Increasing Subsequence in Java.

**Comment by Jagruthi13** [comment]
Hey @rudrakshi99 @nakul-19 
I am a GSSoC'21 participant. I would like to do this problem in python.
Can you assign me this issue

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.


@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99
