### ISSUE TITLE
Add Bubble Sort Algorithm in C++

### ISSUE THREAD

**Issue by pawki07** [Algo-Phantoms/Algo-Tree#54]
Hello,
I would like to add bubble sort algorithm in the sorting section. Please assign it to me. I would do my bets.

**Comment by tina-alex-leslie** [comment]
Hello,
I would like to add bubble sort algorithm in the sorting section. Please assign it to me.

**Comment by Subhangini** [comment]
Please assign this issue to me .I would like to work on it.

**Comment by iamartyaa** [comment]
Sir
I would like to work on this issue . I have read the guidelines for making a contribution and will abide by them . I am actively contributing to GeeksforGeeks & Codeforces community and so I can explain the intuition & idea of the algorithm efficiently.
Please assign the issue to me .

I have been selected for GSSOC'21, and I am really interested in Algorithms , so I would like to contribute in this amazing repository.
Regards
Amartya Yadav

**Comment by sukhpreet-singh1** [comment]
i would like to solve this issue please assign me this issue

**Comment by pawki07** [comment]
I have made a pull request here #71 . Pleas have a look @nakul-19

**Comment by IdealisticINTJ** [comment]
I would like to work on this. I would like to contribute to this, under GSSoC '21.

**Comment by Amulya310** [comment]
I am quite interested in learning , implementing and bettering algorithms .So please consider assigning this issue to me under GSSOC'21 .

**Comment by AkanshaUniyal** [comment]
Respected sir, 
I would be privileged to write this algorithm in JAVA @nakul-19 . Please assign me this under GSSOC'21

**Comment by nakul-19** [comment]
@tina-alex-leslie  @Subhangini @iamartyaa @sukhpreet-singh1 @IdealisticINTJ @Amulya310  please always mention the language you would use to work on the issue.

**Comment by sukhpreet-singh1** [comment]
I can do in C++,python,c,Java,javascript,c#

**Comment by iamartyaa** [comment]
@nakul-19  
Sir I will be using C++ , Python & Java to work on this issue .

**Comment by nakul-19** [comment]
@sukhpreet-singh1 please provide the code in Python and @iamartyaa in Java.

**Comment by yogitasaini** [comment]
I could Ito solve this issue in java .Please assign it to me under gssoc'21

**Comment by Manya1609** [comment]
Hey!..I'm a GSSOC'21 Participant and would like to work on this issue. I would like to explain the concept and the code in C++. 
Can anyone please assign me this issue??

**Comment by OjusWiZard** [comment]
Assignees became inactive. So closing this issue because others have raised new issues for this
