### ISSUE TITLE
Insertion_at_start of array in java

### ISSUE THREAD

**Issue by prateek-jpg** [Algo-Phantoms/Algo-Tree#543]
A program to add elements at the beginning  of an array in java.

I am a GSSOC'21 participant, and I would like to contribute the Java code for this problem. I will make sure that the code is commented properly and follows all the given guidelines. Please give me this opportunity. Thankyou!
@tarun26091999  @rudrakshi99

**Comment by tarun26091999** [comment]
issue present at #146
