### ISSUE TITLE
Finding prime number till N by Sieve of Eratosthenes ( Method 2) ( C++)

### ISSUE THREAD

**Issue by rohank2502** [Algo-Phantoms/Algo-Tree#546]
In this algorithm i will try to find the number of prime number present till n and give a count with each number !! Will start working on it as soon as i get assigned

**Comment by rudrakshi99** [comment]
@rohank2502 Close your previous issues - #478 #479. So that I can assign you these.

**Comment by rohank2502** [comment]
Ok i have added one Pr will add second pr In a hour Then I will close both
issues

**Comment by OjusWiZard** [comment]
Duplicate of #502
