### ISSUE TITLE
Implementation of Linked List [Java]

### ISSUE THREAD

**Issue by Chirag018** [Algo-Phantoms/Algo-Tree#549]
Hi,I'm a GSSoC participant.
I wish to add the implementation of Linked List in Java .

**Comment by Rupa-421** [comment]
Hi!
I'm a gssoc 21 participant.I want to contribute on singly ,doubly, circular singly, circular doubly linked list in java.Aiming to write a CLEAN CODE and PERFECT README .@tarun26091999 @Chirag018 @todi-2000 @diyajaiswal11 @anubhavitis @dheerajkotwani @geekquad can you please assign this to me?

**Comment by tarun26091999** [comment]
issue present at #152
