### ISSUE TITLE
Add bucket sort and counting sort 

### ISSUE THREAD

**Issue by pawki07** [Algo-Phantoms/Algo-Tree#55]
Hello,
I would like to add bucket sort and counting sort in C++. Please assign this issue to me. I would do my best!

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue?i would love to solve this issue

**Comment by sonaliBedade** [comment]
I am interested in solving this issue. Would you please assign it to me so that I can start working on it?

**Comment by Amit366** [comment]
@tarun26091999 @anubhavitis can I work on this issue using Java??

**Comment by rk05-lenavo** [comment]
I'm  the participants in GSSOC'21. I would like to work on this issue by using python. Please assign me this issue @rudrakshi99
