### ISSUE TITLE
Loop detection in linked list

### ISSUE THREAD

**Issue by shrishti-c** [Algo-Phantoms/Algo-Tree#550]
I can implement loop-detection using different algorithm and also how to remove them. Please assign this to me.

**Comment by archi362** [comment]
Hi I am Archi. I would like to contribute to this as a part of GSSOC'21. Please assign me this as I have prior knowledge of LinkedList

**Comment by esheetaparulekar** [comment]
Please assign this issue to me for Java.

**Comment by tarun26091999** [comment]
present at #189
