### ISSUE TITLE
Implementing insertion sort in C++

### ISSUE THREAD

**Issue by nidh-ish** [Algo-Phantoms/Algo-Tree#553]
I want to implement insertion sort in c++.

Please assign this to me under GSSOC'21.

**Comment by archi362** [comment]
Hi I am Archi. I would like to contribute to this as a part of GSSOC'21. Please assign me this as I have prior knowledge of C++.

**Comment by nidh-ish** [comment]
@plazzy99 Can you assign this issue to me?
