### ISSUE TITLE
Staircase Search

### ISSUE THREAD

**Issue by ritikpanchal768** [Algo-Phantoms/Algo-Tree#558]
Problem:- we have a 2-d array having its rows and columns sorted .you want to search a given element in it with a time complexity of O(n).

I want to work on this problem. Kindly assign it to me.

**Comment by sumitsantape30** [comment]
I would like to resolve this issue, will be implementing using Java, Please assign me this.
I'm GSSoC21 participant.

**Comment by OjusWiZard** [comment]
Duplicate of #385
