### ISSUE TITLE
Counting First occurrence , last occurrence , and all occurrence of an element using Recursion

### ISSUE THREAD

**Issue by ritikpanchal768** [Algo-Phantoms/Algo-Tree#562]
Hiii i would like to work on this issue using C++. Kindly assign this to me

**Comment by Ritu7683** [comment]
Hii I would like to work on this issue using C++. Kindly assign this issue to me.

**Comment by OjusWiZard** [comment]
@ritikpanchal768 Please explain the issue more briefly.
For now, closing the issue. Will reopen after your response

**Comment by Tanyx-01** [comment]
test
