### ISSUE TITLE
STRINGS : Checking If Two Strings Are Anagram Or Not. 

### ISSUE THREAD

**Issue by Mugdha-Hazra** [Algo-Phantoms/Algo-Tree#565]
### **Explanation:**

  **An anagram is two sets of strings formed from the same set of alphabets.**

 Given two strings by the user, we have to check whether the two strings are anagram or not i.e they are formed from the same set of alphabets or not.
 
> EXAMPLE:
    **INPUT**
      **String 1:** DECIMAL      
      **String 2:** MEDICAL
            **OUTPUT**
          YES, THE STRINGS ARE ANAGRAM!!

Hello @tarun26091999 sir, I wanted to add this important question in the `Algo-Tree/string/` and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in CPP.

**Comment by Gautam204** [comment]
Hello @tarun26091999 sir, I think this is an important questions and this should definitely be added in the Algo-Tree/string/ and I will start working on it as soon as I get assigned!! as I am a part of **GSSoC'21**, so I would like to implement this in **Java and Python** languages .

**Comment by mohdarif8299** [comment]
@tarun26091999 Sir please allow me to work on this issue, I am good with Data Structures using Java.

**Comment by tarun26091999** [comment]
issue present at #395
