### ISSUE TITLE
reverse a singly linked list

### ISSUE THREAD

**Issue by jeelnathani** [Algo-Phantoms/Algo-Tree#566]
hello, I am GSSOC'21 participant. I would like to contribute in this Algo-tree project by writing a program in python which can reverse a singly linked list
for example:
input: 1->2->3->4->5->Null
output: 5->4->3->2->1->Null

input: 7->Null
output: 7->Null

hope you assign me this issue :)

**Comment by esheetaparulekar** [comment]
I can contribute to this issue in Java.

**Comment by Mugdha-Hazra** [comment]
Hello @tarun26091999 @dheerajkotwani  @esheetaparulekar @anubhavitis @jeelnathani, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by IdealisticINTJ** [comment]
I would like to implement this in Python. Please assign this to me.

**Comment by priyamourya** [comment]
I am GSSOC'21 participant and l would like to work on this problem and would make sure to implement a neat and clean code ,and make it easy to understand using comments.

**Comment by tarun26091999** [comment]
present at #193
