### ISSUE TITLE
Removing duplicate character, reversing string.(Python)

### ISSUE THREAD

**Issue by Deeksha-Rawat** [Algo-Phantoms/Algo-Tree#567]

**Comment by Deeksha-Rawat** [comment]
I will solve problems like 
removing duplicate character from the string.
reversing in string
separate vowel and consonants form a string
finding wheater a string is palindrome or not.

**Comment by IdealisticINTJ** [comment]
I would like to solve this in Python. Kindly assign this to me.

**Comment by tarun26091999** [comment]
cannot solve more than 1 problem in a single issue.
