### ISSUE TITLE
Non-recursive factorial in CPP

### ISSUE THREAD

**Issue by nidh-ish** [Algo-Phantoms/Algo-Tree#570]
Finding the factorial of a number in CPP non-recursively.

Please assign this to me under GSSOC'21.

**Comment by IdealisticINTJ** [comment]
I would like to contribute to this. Please assign this to me under GSSoC'21.

**Comment by nandini040** [comment]
This issue has already been created.

**Comment by nidh-ish** [comment]
Okay. Sorry for the inconvenience.
