### ISSUE TITLE
Vector Programs 

### ISSUE THREAD

**Issue by Gautam204** [Algo-Phantoms/Algo-Tree#571]
### Explanation:

A vector is a sequence container class that implements dynamic array.

I want to create a repo to include the basics of vectors and different functions used in the vectors like sorting, erasing etc. 

Hello @tarun26091999 @plazzy99 @rudrakshi99 @nakul-19  @OjusWiZard @shreyanspoddar @raksha009 @Anjul2000, I wanted to add this important question in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of **GSSoC'21**, so I would like to implement this in **CPP**.

**Comment by tarun26091999** [comment]
you need to raise separate issue for separate questions.
