### ISSUE TITLE
Deletion of Alternate nodes in a linked list

### ISSUE THREAD

**Issue by Mohim-Singla** [Algo-Phantoms/Algo-Tree#572]
[C++] This program will delete alternate nodes in the linked list.

For example : The linked list provided by the user is: 1->2->3->4->5->6->7->8->9
Output would be :  1->3->5->7->9

Please assign me this issue.

**Comment by Gautam204** [comment]
I would like to perform this program using **Java and Python**. 
Please assign me this issue.

**Comment by Vishal-Singh-1996** [comment]
@rudrakshi99 @Mohim-Singla @dheerajkotwani 
Pls assign me this issue.
I would like to solve these problem in java.

**Comment by MaitriDA** [comment]
@rudrakshi99 @Mohim-Singla Please assign me this issue. I will write the code in C++.

**Comment by Mohim-Singla** [comment]
@rudrakshi99 I have created the pull request for this program how do i link it with this issue?

**Comment by abhishek7389** [comment]
I want to do this, so please give me a chance.

**Comment by prityusha** [comment]
(CPP)Hey, @rudrakshi99  @Mohim-Singla @dheerajkotwani please assign this issue to me i can solve it on CPP.

**Comment by Mohim-Singla** [comment]
@prityusha I have already implemented this program and waiting for the second review till it get merged.

**Comment by Nishayadav-bit** [comment]
Hey , I'm a GSSOC'21 participant . I would like to work on this issue please assign me .

**Comment by nikhv** [comment]
@rudrakshi99 @tarun26091999 I'm a GSSOC'21 participant , I would implement it in C++ ,please assign this to me.
