### ISSUE TITLE
Traversing through a tree

### ISSUE THREAD

**Issue by rray14** [Algo-Phantoms/Algo-Tree#573]
Unlike other data structures, trees have many ways to traverse them which are inorder, postorder, and preorder
I'll be implementing them using c++
My name is Ardra Mohan and I'm a participant of GSSOC'21  
I'm highly looking forward to working on this, please assign this issue to me 
Thanks!!

**Comment by divya1509** [comment]
Hey, I am Divya Chopra, a participant of GSSOC'21. I would like to work on this issue in the JAVA language. I will provide a neat and explanatory code for this. Please assign me this issue.

**Comment by Rupa-421** [comment]
Hi!
I'm a gssoc 21 participant.I want to contribute on tree traversal in java or python language comfortably.Aiming to write a CLEAN CODE and PERFECT README .Can you please assign this to me?

**Comment by tarun26091999** [comment]
present at #144
