### ISSUE TITLE
Hashing (Insertion, Deletion and Search) in C++

### ISSUE THREAD

**Issue by malavikarajeshvikraman** [Algo-Phantoms/Algo-Tree#575]
Hi ! I am Malavika , participating in GSSOC'21 .
I would like to contribute by adding Hashing algorithm in C++ . 
So Kindly please do assign me this task.

**Comment by OjusWiZard** [comment]
@malavikarajeshvikraman Please explain the algorithm more briefly.
Closing the issue for now. Will reopen after your response.

**Comment by malavikarajeshvikraman** [comment]
Hi So I was planning to execute hashing using linear probing.
