### ISSUE TITLE
Generic Selection Sort [GSSOC21]

### ISSUE THREAD

**Issue by madhurima99** [Algo-Phantoms/Algo-Tree#581]
I would like to add a **Generic Selection Sort** algorithm to sort any kind of **ArrayList of objects** depending on any attribute of the object. 

@plazzy99  @rudrakshi99  @nakul-19 @tarun26091999  @OjusWiZard @shreyanspoddar @raksha009 @anjul2000 
I'm participating in GSSOC21. It would be great if you assign this issue to me.
Thank you.

**Comment by OjusWiZard** [comment]
Specify the language.
Will reopen the issue after your response.

**Comment by madhurima99** [comment]
@OjusWiZard I'll be using Java to solve the problem. Can you reopen and assign this issue to me?
