### ISSUE TITLE
Add Queue implementation using linked list in c++

### ISSUE THREAD

**Issue by Subhangini** [Algo-Phantoms/Algo-Tree#59]

**Comment by nandini040** [comment]
I would like to work on this issue . Please assign it to me.

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue?

**Comment by Amulya310** [comment]
I would really like to work on this issue and contribute to this amazing repository. I have prior knowledge about queues as well as linked list ,so ,kindly consider assigning  this to me under GSSoC '21.

**Comment by Avnish5** [comment]
Kindly assign this task to me.
I had very strong understanding of DSA.

**Comment by nandini040** [comment]
Can we  create PR before 8 march (for gssoc  )

**Comment by Subhangini** [comment]
working on this , will complete it soon

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by Subhangini** [comment]
> I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

@pallavidhere23  I am working on this issue you can go for some other one:)

**Comment by AasthaGoyalgit** [comment]
Hey!!

I am interested in this issue in java problems as a GSSOC'21 participant .
I'll be glad to work on this issue.

Thanks!!

**Comment by Subhangini** [comment]
@rudrakshi99  please label the issue under gssoc'21 so that our contributions get counted for it
