### ISSUE TITLE
finding permutation occurance of string s1 in string s2 

### ISSUE THREAD

**Issue by anshulsharma123** [Algo-Phantoms/Algo-Tree#593]
Hello admins 
                    I am gssoc21 participant and i want to add a special problem in this project the problem is a follows:
  Problem statement:
   We are given the two strings s1 and string s2 and we have to add all the permutation of string s1 in string s2 in  optimal way 
  Benefits of this problem :
 1) By this problem we can understand the concept of permutation 
 2)  By this problem we can understand that how can we tackle the question of permutation 
 3) Use of datastructure

**Comment by OjusWiZard** [comment]
Specify the language.
Will reopen the issue after your response.

**Comment by anshulsharma123** [comment]
I will write the code in c++ language
