### ISSUE TITLE
[GSSOC'21] Locker Doors Problem

### ISSUE THREAD

**Issue by Apurv011** [Algo-Phantoms/Algo-Tree#595]
Hello, I am Apurv Kulkarni, a GSSOC'21 Participant. I would like to implement the Locker Doors Problem in JAVA.

The Locker Door Problem is
There are n lockers in a hallway, numbered sequentially from 1 to n. Initially, all the locker doors are closed.  You make n passes by the lockers. On the ith pass (for i = 1, 2, . . . , n,) you toggle the door of every ith locker. You have to find the lockers doors that will be open at the end and the total number of open Locker Doors at the end. 

Kindly assign this to me.
Thank you

@rudrakshi99  @tarun26091999  @plazzy99

**Comment by simarjeet30** [comment]
Hello @rudrakshi99 , I am Simarjeet Kaur, a GSSOC'21 Participant. I would like to implement the Locker Doors Problem in C/C++/PYTHON.

The Locker Door Problem is
There are n lockers in a hallway, numbered sequentially from 1 to n. Initially, all the locker doors are closed. You make n passes by the lockers. On the ith pass (for i = 1, 2, . . . , n,) you toggle the door of every ith locker. You have to find the lockers doors that will be open at the end and the total number of open Locker Doors at the end.

**Comment by OnewayShruti** [comment]
I am a GSSOC'21 participant(Discord Username -Oneway_Shruti(P)#9537)
I wish to contribute to Locker Doors Problem I can write the code in C++ with a time complexity of O(n) and also in python, along with well explained comments.
Do consider assigning me on this.

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by Upasana1216** [comment]
I want to contribute to this in c++. Please assign this to me

**Comment by OjusWiZard** [comment]
Please specify which DSA concept will it use.
Will reopen the issue after your response.

**Comment by Apurv011** [comment]
This is a simple mathematical problem that uses concepts from number theory. 
As mentioned in the problem, all locker doors are numbered from 1 to n. A locker door labelled with a number that is less than or equal to the number of passes and has odd number of factors will be toggled odd number of times and that door will be open at the end.
Also, only perfect squares have odd number of factors. Hence, the locker doors numbered with perfect squares and less than or equal to the number of passes will be open at the end.
So, this problem comes under the category of Number Theory.
