### ISSUE TITLE
Graph Algorithms

### ISSUE THREAD

**Issue by Siddhant-K-code** [Algo-Phantoms/Algo-Tree#6]
- [ ] BFS
    - [ ] C++
    - [ ] Java 
    - [ ] Python
- [ ] DFS
    - [ ] C++
    - [ ] Java 
    - [ ] Python

**Comment by Siddhant-K-code** [comment]
Can I work on `BFS & DFS in C++`

**Comment by rudrakshi99** [comment]
@Siddhant-K-code The algorithm is already included. I have updated the link in readme. You can check [here](https://github.com/Algo-Phantoms/Algo-Tree/blob/main/Graph/readme.md) but you can work on any other issue.

**Comment by Siddhant-K-code** [comment]
Can I implement Shortest Path or Other Graph Algorithms like Dijkstra algorithm, Backtracking?

**Comment by rudrakshi99** [comment]
@Siddhant-K-code Yes, you can. Firstly, create an issue and link your PR with it when you will get assigned.
