### ISSUE TITLE
 Storing the DSU(Disjoint Set Union) explicitly in a set list

### ISSUE THREAD

**Issue by nitrr26** [Algo-Phantoms/Algo-Tree#600]
Hey!! @tarun26091999, @rudrakshi99,  I want to add

     Storing the DSU(Disjoint Set Union) explicitly in a set list / Applications of this idea when merging 
     various data structures / Time complexity with the explanation.

I am a GSSOC’21 participant, Please assign me this issue.
Thank You :)

**Comment by OjusWiZard** [comment]
Will reopen the issue after you specify the language that you want to use.
