### ISSUE TITLE
[GSSOC'21] Seive of Eratosthenes algorithm in c++

### ISSUE THREAD

**Issue by anotherwebguy** [Algo-Phantoms/Algo-Tree#601]
Plz assign me this issue as a part of gssoc'21. I would like to work on this issue.

In this algorithm we can find all the prime numbers within a given range ,provided n.

Plz assign me this issue @rudrakshi99 @tarun26091999 @plazzy99 @anubhavitis

**Comment by OnewayShruti** [comment]
Hey @avijit1999 @tarun26091999 @dheerajkotwani @anubhavitis 
I am a GSSOC'21 participant(Discord Username -Oneway_Shruti(P)#9537)
I wish to contribute to Seive of Eratosthenes algorithm in c++.I am familiar with C,C++ and python.
I can write this algorithm in O(n) time complexity,do consider assigning me .

**Comment by anotherwebguy** [comment]
> Hey @avijit1999 @tarun26091999 @dheerajkotwani @anubhavitis
> I am a GSSOC'21 participant(Discord Username -Oneway_Shruti(P)#9537)
> I wish to contribute to Seive of Eratosthenes algorithm in c++.I am familiar with C,C++ and python.
> I can write this algorithm in O(n) time complexity,do consider assigning me .

Hey @OnewayShruti  since i've raised the issue so i would be working on it but i'am sure u can find another issues to contribute to or u can even raise an issue

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.


@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by shreyanspoddar** [comment]
This issue has been already assigned before refer #47
