### ISSUE TITLE
[gssoc] Add basic mathematics algorithms

### ISSUE THREAD

**Issue by itsIapetus** [Algo-Phantoms/Algo-Tree#605]
I would like to add the following math algorithms in C++ and Python.
Area of shapes
Ackermann Function
Catalan number
Euler totient function
Armstrong Number
Ugly Numbers
Binary Exponentiation

Kindly assign this issue to me under GSSoC'21.
Thank you.

**Comment by avijit1999** [comment]
I want that in java

**Comment by itsIapetus** [comment]
Can someone assign it to me please? Thank you.

**Comment by itsIapetus** [comment]
@plazzy99 Could someone assign it to me?

**Comment by Upasana1216** [comment]
I am a GSSOC'21 participant and I would really like to contribute to this in C++ with added comments ,test cases and time and space complexity . Looking forward to the contribution.

**Comment by OjusWiZard** [comment]
Raise separate issues for separate issues.
