### ISSUE TITLE
Count set bits (Kernighan'sAlgo )

### ISSUE THREAD

**Issue by Prajwal-ctrl** [Algo-Phantoms/Algo-Tree#606]
Hey @dheerajkotwani  @tarun26091999  @avijit1999 i am a GSSOC participant can i work on this Problem . let me know

**Comment by tarun26091999** [comment]
@Prajwal-ctrl do it in C++.

**Comment by prityusha** [comment]
hey @tarun26091999  @dheerajkotwani @avijit1999 i am a GSSOC'21 participant and i can work on this problem in cpp, kindly assign this issue to me.

**Comment by ganesh-sai-a** [comment]
Hey! @tarun26091999 @dheerajkotwani @avijit1999 
I am GSSOC 21 participant, I wish to work on this issue.
I will work on this project in CPP using Kernighan's Algo, could you please assign me the issue.

**Comment by raksha009** [comment]
Issue present at #44
