### ISSUE TITLE
  Code for Insertion Sort in c++  

### ISSUE THREAD

**Issue by mu593** [Algo-Phantoms/Algo-Tree#61]

**Comment by mu593** [comment]
#61 please assign me this issue.

**Comment by sukhpreet-singh1** [comment]
if no one is working on this issue, can you  please assign me for this issue ?

**Comment by Siddhartha1999** [comment]
I want to work on this issue...Please assign it to me

**Comment by kunal299** [comment]
@mu593 will u plz assign this issue to me as a part of Gssoc.

**Comment by Amulya310** [comment]
I would really like to work on this issue and contribute to this amazing repository .Kindly consider assigning this to me under GSSoC'21.

**Comment by maanpatel2492** [comment]
Hey,I can work on this issue.Assign me.

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by rudrakshi99** [comment]
Already added in the repo. Check [this](https://github.com/Algo-Phantoms/Algo-Tree/blob/main/Code/C%2B%2B/insertion_sort.cpp)
