### ISSUE TITLE
Merge Two Sorted Linked Lists

### ISSUE THREAD

**Issue by atharva1608** [Algo-Phantoms/Algo-Tree#613]
I want to add code for merging two sorted linked lists in C++ . 
As a GSSoC'21 participant please assign this issue to me.

**Comment by vedant-jain03** [comment]
I can do this program using C,C++ and python
please assign me this issue.
@raksha009 @tarun26091999 @plazzy99

**Comment by anujjain5699** [comment]
Can you assign this issue to me.

**Comment by mdsadiqueinam** [comment]
I want to add code for merge and sort the  multiple sorted Linked Lists using the divide and conquer method
please assign this issue to me.
Thank You

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by tarun26091999** [comment]
present at #468
