### ISSUE TITLE
[GSSoC'21] Calculate factorial using Recursion.

### ISSUE THREAD

**Issue by dcs-soni** [Algo-Phantoms/Algo-Tree#614]
## Hey @tarun26091999 @shreyanspoddar @rudrakshi99 and all other mentors.

I am currently practising **DSA** in **C++** and found this project to contribute to under GSSoC'21. 

I want to add the program which calculates the factorial of the given number using **Recursion** in **C++**. Please assign this issue to me under **GSSoC'21**.

**Comment by NidhiNivedita6** [comment]
I am a GSSoC'21 participant. I want to do this in Java. Please assign me this @tarun26091999 @shreyanspoddar @rudrakshi99  and all mentors.

**Comment by Mayankjha997** [comment]
Hello sir;
I am a GSSoC participant , I would like to Contribute in this by python.  Please assign me this @tarun26091999 @shreyanspoddar @rudrakshi99 and all mentors.

**Comment by preetiahuja18** [comment]
Please assign this to me  under GSSOC'21. I want to add the proper program in c++. I will give my best .

**Comment by vedant-jain03** [comment]
I can do this program using C,C++ and python
please assign me this issue.

**Comment by OnewayShruti** [comment]
Hey @tarun26091999 @rudrakshi99 
I am a GSSOC'21 participant(Discord Username -Oneway_Shruti(P)#9537)
I wish to contribute to Calculate factorial using Recursion. I can write the code in C++ with a time complexity of O(n) and also in python, along with  well explained comments.
Do consider assigning me on this.

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by reerajput930** [comment]
Hello, I would like to contribute to this project in c++ language with help of recursion.
->with O(n) time complexity
->with O(1) space complexity
I am a GSsoc'21  participant.
waiting for a positive response.

**Comment by tarun26091999** [comment]
present at #276
