### ISSUE TITLE
Bridges(Cut-Edge) and Articulation Point(Cut-Vertex) In Graph using C++

### ISSUE THREAD

**Issue by Naman-18** [Algo-Phantoms/Algo-Tree#615]
Hey! @tarun26091999  @rudrakshi99  @shreyanspoddar  @nakul-19 @plazzy99 
I am GSSOC'21 Participant and I would like to implement following Graph Algorithm in C++ which are inter-related:

1) Algorithm to Find Bridges(Cut Edge) in Graph : A Bridge is defined as an edge in the graph whose removal either makes a graph disconnected or increase number of disconnected components of graph. 

2) Algorithm to Find Articulation Point(Cut Vertex):  An Articulation Point is defined as a vertex whose removal of self and related edge makes a graph disconnected. In a Graph if an edge (node1,node2) is a bridge then either node1 or node2 is an articulation point. In a condition if there are no bridge , Even then if a cycle exist it is also an indication of probable existence of an Articulation point.

I can contribute clean and well-commented code so that it gives readability to all users. Please assign me this issue.

**Comment by tarun26091999** [comment]
both are different problems, you need to raise separate issues.
