### ISSUE TITLE
Prime Number in range ( Method 1) ( Algorithm ) (JAVA)

### ISSUE THREAD

**Issue by shiv-30** [Algo-Phantoms/Algo-Tree#617]

**Comment by shiv-30** [comment]
Hi, I am a GSSOC'21 participant. I want to implement this issue in JAVA with proper comment and indentation.
Please assign this issue to me.

**Comment by Amanduttbhagat** [comment]
Hello,
I am a GSSoC 2021 Participant and would like contribute to this issue in Java
kindly assign me the issue

**Comment by OjusWiZard** [comment]
Please describe your method 1 which you are talking about.
Will reopen after your response.
