### ISSUE TITLE
[GSSOC21] [JAVA] SPIRAL TRAVERSAL IN A MATRIX

### ISSUE THREAD

**Issue by Saikat-Chowdhury90** [Algo-Phantoms/Algo-Tree#622]
@tarun26091999 @rudrakshi99 
Sir,
I am a participant of GSSOC21 and want to contribute in your project . I want to add a code of spiral traversal in a matrix in java.
We will accept a 2-D Matrix from the user and then we will print the spiral traversal of that Matrix.
Test Case
4 4
1 2 3 4
5 6 7 8
9 7 6 4
1 2 3 6
Output
1 2 3 4 8 4 6 3 2 1 9 5 6 7 6 7

Please assign this work to me

**Comment by pallavidhere23** [comment]
I can implement this issue in java,c++,python.I am good at data structures and algorithm .Please assign me this issue under GSSOC'2021.

**Comment by tarun26091999** [comment]
present at #83
