### ISSUE TITLE
kadane's algorithm for maximum sum subarray 

### ISSUE THREAD

**Issue by anshulsharma123** [Algo-Phantoms/Algo-Tree#623]
hello admins I would like to add kadane's algorithm for maximum sum subarray please assign this work to me 
I will contribute the code in c++ language

**Comment by Saikat-Chowdhury90** [comment]
@tarun26091999 @rudrakshi99 
sir,
i am a participant of gssoc21 and would like to code kadane's algorithm for maximum sub array in java 
please assign this issue to me

**Comment by vedant-jain03** [comment]
I can do this program using C,C++ and python
please assign me this issue.

**Comment by tarun26091999** [comment]
#178 is same
