### ISSUE TITLE
Overall median of the matrix A.

### ISSUE THREAD

**Issue by IShahnawazShaikh** [Algo-Phantoms/Algo-Tree#627]
Note: Rows are sorted
A = [   [1, 3, 5],
        [2, 6, 9],
        [3, 6, 9]   ]
output: 5
hey @tarun26091999 @shreyanspoddar I am GSSOC'21 participant may I work on this issue.
 I will implement this in TC O(N) without using extra space (using Binary search).
if we use extra space Space complexity would be O(row*column).

**Comment by Amanduttbhagat** [comment]
Hello,
I am a GSSoC 2021 Participant and would like contribute to this issue in Java
kindly assign me the issue

**Comment by tarun26091999** [comment]
> Note: Rows are sorted
> A = [ [1, 3, 5],
> [2, 6, 9],
> [3, 6, 9] ]
> output: 5
> hey @tarun26091999 @shreyanspoddar I am GSSOC'21 participant may I work on this issue.
> I will implement this in TC O(N) without using extra space (using Binary search).
> if we use extra space Space complexity would be O(row*column).

do it in C++.

**Comment by IShahnawazShaikh** [comment]
@tarun26091999 sir can i implement Java? I can implement in  C++ also.

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. I will be using Java. Thanks!

**Comment by omniasalah276** [comment]
@tarun26091999 
 I would like to do it in python, could you please assign it to me?

**Comment by omniasalah276** [comment]
Hello @tarun26091999 !
I am a GSSoC'21 Participant and I would like to do it in python, could you please assign it to me?
