### ISSUE TITLE
Bubble Sort 

### ISSUE THREAD

**Issue by sonal251001** [Algo-Phantoms/Algo-Tree#630]
Hello @rudrakshi99  I am Sonal Singh. A GSSoC'21 participant. I would like to add the bubble sort technique in the code . My folder would be arrays. I have read the contribution guidelines and would like you to assign this to me.

**Comment by Aarti002** [comment]
hey @tarun26091999 @rudrakshi99 under gssoc'21 can i work on this issue in oython
Thank you!

**Comment by Aarti002** [comment]
*python

**Comment by aradhana72** [comment]
@rudrakshi99  I would like to add c++ code for bubble sort under GSSOC'21.Can I work on this ?

**Comment by reerajput930** [comment]
Hello, I would like to contribute to this project in c++.
->with O(n*n) time complexity
->with O(1) space complexity
I am a GSsoc'21  participant.
waiting for a positive response.

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue in java as a GSSoC 2021 participant
kindly assign me the issue

**Comment by rk05-lenavo** [comment]
I'm a  participant from GSSOC'21. Kindly assign me this issue.

**Comment by OjusWiZard** [comment]
Duplicate of #440
