### ISSUE TITLE
{gssoc21 }dijkstra algorithm time complexity

### ISSUE THREAD

**Issue by kavyasree-123** [Algo-Phantoms/Algo-Tree#636]
**This is participant of gssoc21** ,have thought of dijkstra algorithm for algo-tree 
which **O ( V + E l o g V )** has its time complexity .
I request  to give a chance on this key issue.

**Comment by kavyasree-123** [comment]
waiting to work on this issue please assign it to me

**Comment by kavyasree-123** [comment]
I have read all the code of conduct and will write the code in much descriptive way along with good explanaition please allow me to work on this issue .

**Comment by OjusWiZard** [comment]
We already have a code for [Dijkstra's Algorithm](https://github.com/Algo-Phantoms/Algo-Tree/blob/main/Code/C%2B%2B/Dijkstra.cpp)
