### ISSUE TITLE
Moore's Voting Algorithm

### ISSUE THREAD

**Issue by rray14** [Algo-Phantoms/Algo-Tree#637]
To find the majority element from an array we can use this algorithm
My name is Ardra, a participant of GSSoC'21
Please assign me this issue
Thanks!!

**Comment by pallavidhere23** [comment]
I can implement this issue in java,c++,python.I am good at data structures and algorithm .Please assign me this issue under GSSOC'2021.

**Comment by SwarnimaShishodia** [comment]
I would like to solve this problem using C++.

**Comment by OnewayShruti** [comment]
Hey @anubhavitis @dheerajkotwani 
I am a GSSOC'21 participant(Discord Username -Oneway_Shruti(P)#9537)
I wish to contribute to Moore's Voting Algorithm I can write the code in C++ with a time complexity of O(n) and  also in python, along  with comments.
Do consider assigning me on this.
