### ISSUE TITLE
[GSSoC'2021] Add Bubble Sort in Python

### ISSUE THREAD

**Issue by AmanUpadhyay8** [Algo-Phantoms/Algo-Tree#647]
Hello mentors, I would like to add bubble sort in python so please assign this to me.

@tarun26091999 @shreyanspoddar @nakul-19 @OjusWiZard @raksha009 @rudrakshi99 please  assign this to me.

**Comment by vedant-jain03** [comment]
Hello mentors I can do this issue using python please assign me this issue.

**Comment by ANAMIKA1410** [comment]
Hello mentors ,
I m Anamika jain .
I wants to contribute to this issue .
please assign this issue to me.
@vedant-jain03 @AmanUpadhyay8 @tarun26091999 @dheerajkotwani @anubhavitis

**Comment by Naman-12911** [comment]
Hello sir , I want to contribute for this issue please assign me this issue .under GSSOC
