### ISSUE TITLE
[GSSOC'21] basic MATH FOLDER 

### ISSUE THREAD

**Issue by dikshajoshi18** [Algo-Phantoms/Algo-Tree#650]
CAN I ADD A BASIC MATH FOLDER FOR BASIC formulas required to solve a problem in a less complex way faster than usual with less time complexity?
discord: diksha#6684
@avijit1999 @tarun26091999 @dheerajkotwani @anubhavitis

**Comment by reerajput930** [comment]
Don't know what's in the math folder, but I can definitely do it in c++ as I am excellent at maths and DSA.
Of course in the least TC  and SC.
looking forward to a positive response!

**Comment by tarun26091999** [comment]
No, math folder is not required
