### ISSUE TITLE
Calculator using Python

### ISSUE THREAD

**Issue by Dhanush2612** [Algo-Phantoms/Algo-Tree#654]
Calculator built using python

**Comment by Tanya933** [comment]
I would like to work on this issue .Please assign this issue to me,I can solve it in python  with proper explanation, comments and sample inputs and outputs.I will follow guidelines given for codebase and contributions.

**Comment by sayantani11** [comment]
I am a participant of GSSoC'21. Please assign me this issue

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this work to me.
