### ISSUE TITLE
Roots of  quadratic equation

### ISSUE THREAD

**Issue by Dhanush2612** [Algo-Phantoms/Algo-Tree#655]
Python program to find roots of quadratic equations

**Comment by AdityaRaj-ar** [comment]
Hello, I am one the participant of GSSOC-21. I request to assign this issue to me. I will solve this issue in JAVA, C++ as well as PYTHON with all the comments clearly explaining the the steps and satisfying all other requirements with least time complexity. Thank You.

**Comment by OjusWiZard** [comment]
We are currently accepting only DSA related issues. But not non-relevant implementation problems.
