### ISSUE TITLE
[GSSOC'21] STRING (Anagram)

### ISSUE THREAD

**Issue by dikshajoshi18** [Algo-Phantoms/Algo-Tree#657]
I would like to add a program to find anagrams of string 
discord: diksha#6684
@avijit1999 @tarun26091999 @dheerajkotwani @anubhavitis

**Comment by Aarti002** [comment]
hello @tarun26091999  @rudrakshi99 can i work on this issue in c++.
Thank you!

**Comment by tarun26091999** [comment]
issue present at #395
