### ISSUE TITLE
JAVA Popular Interview Questions

### ISSUE THREAD

**Issue by wildchaser1703** [Algo-Phantoms/Algo-Tree#669]
Hi @anubhavitis @rudrakshi99 ! I have read the contribution guidelines. 

I think that most of the questions here focus completely on DSA. For complete overall preparation, however, it would be good to add the top interview questions in Java language. 

These will be quality-based and handpicked questions.

I can help with the same. Please assign this issue to me.

**Comment by Simar05519** [comment]
I had practiced its questions. I want to work on this issue. Please assign to me.

**Comment by OjusWiZard** [comment]
Raise separate issues.
