### ISSUE TITLE
Searching algorithm using Java and C++

### ISSUE THREAD

**Issue by lavanya243** [Algo-Phantoms/Algo-Tree#685]
Hey @plazzy99 @rudrakshi99 @nakul-19, I am Lavanya Narayanan, a GSSOC, 2021 participant.
I want to implement Searching algorithms using Java and C++.

Searching Algorithms include:
1. Linear Search (Time complexity : O(n)
2. Binary Search ((Time complexity : O(log n))

I would like to request you to kindly assign me this problem.

**Comment by hritikkhurana10sm** [comment]
Hii , @plazzy99 @rudrakshi99 @nakul-19, I am Hritik Khurana, looking for first commit .
I want to implement Searching algorithms using  C++.
Please assign this to me.

**Comment by tarun26091999** [comment]
cannot ask for two problems in same issue and both algorithms are being worked upon.
