### ISSUE TITLE
Single Number Problem In Bit-Masking Using Java

### ISSUE THREAD

**Issue by asthakri50** [Algo-Phantoms/Algo-Tree#686]
Hey @tarun26091999 @rudrakshi99 @nakul-19 @plazzy99 @OjusWiZard,
 I want to add the important "Single Number I" using Bit Manipulation in  Algo-Tree/Code/Java/

The problem statement is:
Given an array of integers A, every element appears twice except for one. Find that single one.
My algorithm has a linear time runtime complexity without using extra space.

Example:
Input:  1, 2, 2, 3, 1 
Output: 3

I will all the guidelines while contributing.
Kindly assign me this issue.
Thank you.

**Comment by tarun26091999** [comment]
present at #317 we don't need multiple approaches.
