### ISSUE TITLE
 Tree:  Height of Binary Tree (Recursive) (JAVA)  (Issue #348)

### ISSUE THREAD

**Issue by 08Gunjan** [Algo-Phantoms/Algo-Tree#698]
#348
I would like to contribute in your Project by working on Tree (Find the Depth ) (Binary Tree ) Problems using Recursive Approach in JAVA .

- My Approach is Optimize yet Easy to understand .
- Single Line Comments makes it easy to read.
- Required Test Case are added at the end.
- Can make it More Explanatory using the Image

<h4>Please assign me this issue under the label GSSOC21 , Looking Forward To your Response @tarun26091999</h4>

**Comment by japneetbhatia** [comment]
Hello I'm GSSOC'21 participant. I want to work on this isse using java.
I can solve it by counting edge or by counting nodes method. Please assign one of the approach to me if possible.

**Comment by tarun26091999** [comment]
present at #85
