### ISSUE TITLE
Tree:  Diameter of Binary Tree (Recursion) (JAVA) #348

### ISSUE THREAD

**Issue by 08Gunjan** [Algo-Phantoms/Algo-Tree#700]
#348
I would like to contribute in your Project by working on Tree (Diameter of Binary Tree)  Problems using Recursive Approach in JAVA .

- My Approach is Optimize yet Easy to understand .
- Single Line Comments makes it easy to read.
- Required Test Case are added at the end.
- Can make it More Explanatory using the Image

<h4> Please assign me this issue under the label GSSOC21 , Looking Forward To your Response @tarun26091999 </h4>

**Comment by tarun26091999** [comment]
present at #291
