### ISSUE TITLE
Rotate A Number

### ISSUE THREAD

**Issue by japneetbhatia** [Algo-Phantoms/Algo-Tree#701]
Hello, I'm GSSOC'21 participant. I want to work on this issue in c++ and java please assign this to me.

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by Mugdha-Hazra** [comment]
Hello @tarun26091999 @dheerajkotwani @esheetaparulekar @anubhavitis @jeelnathani, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by Varun8216889** [comment]
As I am a beginner, Can I start my contribution by working on this issue under GSSoC'21? Kindly assign it to me.

**Comment by OjusWiZard** [comment]
Will reopen the issue after you mention the approach that you will be using.
