### ISSUE TITLE
Finding Maximum element in Binary Tree

### ISSUE THREAD

**Issue by japneetbhatia** [Algo-Phantoms/Algo-Tree#704]
Hello I'm GSSOC'21 participant. I want to work on this isse using java. please assign this to me

**Comment by jeelnathani** [comment]
hey, I am GSSOC '21 participant too. I would like to implement it in python

**Comment by shahina-bano** [comment]
Please assign this issue, I will solve this using CPP.

**Comment by OjusWiZard** [comment]
Duplicate of #703
