### ISSUE TITLE
Adding greedy algorithms examples

### ISSUE THREAD

**Issue by XZANATOL** [Algo-Phantoms/Algo-Tree#707]
I've noticed that there is a lack of examples on the greedy algorithms, and I can help adding some.

# Details
* Examples are taken from GeeksForGeeks Problem Solving.
* Code will be from my own creativity. (No plagiarism)
* Comments that explains the problem, inputs nature, and the greedy approach will be added.
* User will be able to test his own inputs (I'll change the method of how the inputs will be parsed and will make the algorithm adapt to this parse change)

# Examples
I am thinking to add some beginner examples:
1) Egyptain Fraction.
2) Job Sequencing For Max Profit.

(If I got assigned, I will be willing to add more in furthur contributions)

# Programming Language
- [x] Python

I would like to contribute to this repository under the mentoship of GSSOC'21

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me

**Comment by OjusWiZard** [comment]
Raise separate issues for each algorithm
