### ISSUE TITLE
Stock Span Problem 

### ISSUE THREAD

**Issue by Shreyash41** [Algo-Phantoms/Algo-Tree#709]
## Feature
I would like to implement the Stock Span problem using stack in C++ Language.

@nakul-19  @tarun26091999 I would like to contribute to this problem under GSSOC,21. please assign it to me.

**Comment by Shraddha13Jain** [comment]
Please assign it to me. I can implement it using C/C++/Python/Java.Please assign it to me under gssoc'21

**Comment by raksha009** [comment]
> Please assign it to me @tarun26091999 @nakul-19 . I can implement it using C/C++/Python/Java.Please assign it to me under gssoc'21

Go ahead with Python.

**Comment by Shraddha13Jain** [comment]
@tarun26091999 please review my previous PR of painter partition problem , so that I could make a PR of this issue.I have implemented the code in python.

**Comment by raksha009** [comment]
> @tarun26091999 please review my previous PR of painter partition problem , so that I could make a PR of this issue.I have implemented the code in python.

Dear, pl create a Pr for this issue asap else we would have to unassign you.

**Comment by Shraddha13Jain** [comment]
> > @tarun26091999 please review my previous PR of painter partition problem , so that I could make a PR of this issue.I have implemented the code in python.
> 
> Dear, pl create a Pr for this issue asap else we would have to unassign you.

@tarun26091999  i have made the PR. Please review it.

**Comment by Shraddha13Jain** [comment]
@raksha009 I have made the changes you requested. please review .
PR #1472
