### ISSUE TITLE
[gssoc21] Prim's Minimum Spanning Tree (MST) | Greedy Algo

### ISSUE THREAD

**Issue by kavyasree-123** [Algo-Phantoms/Algo-Tree#711]
hello,this is kavyasree(P) gssoc21 participant want to contribute .I felt it is an important algorithm in dsa .
please allow me to work on this issue.
i have read the guidelines carefully and follow accordingly
thank you.

discord:  kavyasree(P) #7992
@avijit1999 @tarun26091999 @dheerajkotwani @anubhavitis

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by machine-sg** [comment]
Hi @anubhavitis @dheerajkotwani  @tarun26091999 , I am GSSoC'21 participant and I want to do it in C++. Please assign me this.

**Comment by tarun26091999** [comment]
present at #351
