### ISSUE TITLE
Factorial Using BigInteger

### ISSUE THREAD

**Issue by javeed3157** [Algo-Phantoms/Algo-Tree#712]
[JAVA] This program can find the factorial for n value greater than 12 .
This program is to improvise the factorial.java which is already present in repo( because the program in repo cannot get the factorial value >12).Till any value of n .
I will solve this using BigInteger concept
For example : The n=5
Output would be : 120
For example : The n=15
Output would be : 1307674368000
I am GSSOC 2021 Participant.
Please assign me this issue to me

**Comment by Amanduttbhagat** [comment]
Hello,
I am a GSSoC 2021 Participant and would like contribute to this issue in Java
kindly assign me the issue

**Comment by Mugdha-Hazra** [comment]
Hello @tarun26091999 @dheerajkotwani @esheetaparulekar @anubhavitis @jeelnathani, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by tarun26091999** [comment]
present at #362
