### ISSUE TITLE
Split Array Largest Sum

### ISSUE THREAD

**Issue by Atul-Kashyap** [Algo-Phantoms/Algo-Tree#714]
**Problem**
Given an array nums which consists of non-negative integers and an integer m, you can split the array into m non-empty continuous subarrays.
Write an algorithm to minimize the largest sum among these m subarrays.

**Example 1**
Input: nums = [7,2,5,10,8], m = 2
Output: 18

**Example 2**
Input: nums = [1,2,3,4,5], m = 2
Output: 9

Hey, I am Atul Kashyap, a GSSOC'21 participant.
I want to contribute the code for the implementation of the Longest Palindrome Substring in the C++ language.
Please assign this task to me.
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by Mugdha-Hazra** [comment]
Hello @tarun26091999 @dheerajkotwani @esheetaparulekar @anubhavitis @jeelnathani, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by rudrakshi99** [comment]
> **Problem**
> Given an array nums which consists of non-negative integers and an integer m, you can split the array into m non-empty continuous subarrays.
> Write an algorithm to minimize the largest sum among these m subarrays.
> 
> **Example 1**
> Input: nums = [7,2,5,10,8], m = 2
> Output: 18
> 
> **Example 2**
> Input: nums = [1,2,3,4,5], m = 2
> Output: 9
> 
> Hey, I am Atul Kashyap, a GSSOC'21 participant.
> I want to contribute the code for the implementation of the Longest Palindrome Substring in the C++ language.
> Please assign this task to me.
> @anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

Go for the 1st problem only in C++ as we are taking one algorithm in a single issue.

**Comment by rudrakshi99** [comment]
> Hi,
> I am GSSOC'21 participant
> 
> My code will be in JAVA with proper comments and test cases.
> @rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

Go for the 1st problem only in java as we are taking one algorithm in a single issue.

**Comment by Nishayadav-bit** [comment]
Hey , I'm a GSSOC'21 participant . I would like to work this issue please assign to me
