### ISSUE TITLE
Seperate an array of 0's and 1's

### ISSUE THREAD

**Issue by iaditichine** [Algo-Phantoms/Algo-Tree#716]
Problem:
Given an array of size n which contains only 0's and 1's in any order,we have to modify the array in such a way that 0's are on left side and 1's on the right side.
Test case-1:
Input:
N = 5
arr[] = {0, 0, 1, 1, 0}
Output: 0 0 0 1 1

Test case-2:
Input:
Input:
N = 4
Arr[] = {0, 0, 0, 0}
Output: 0 0 0 0
 There are no 1's in the given array, 
so the modified array is 0 0 0 0.
Hello I am Aditi Chine, a GSSOC'21 participant.I want to solve this problem using counters.Please assign this to me.
@rudrakshi99

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by drishika2002** [comment]
Hello, I am a GSSOC'21 participant and I want to code this problem in cpp.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue.

**Comment by iaditichine** [comment]
@drishika2002, I've already coded this in C++.

**Comment by vedant-jain03** [comment]
I can do this in C++ and python

**Comment by drishika2002** [comment]
@iaditichine  Okay :)

**Comment by aanchalsethi** [comment]
I code this issue in CPP. Please assign me this issue.

**Comment by iaditichine** [comment]
Hey @aanchalsethi , I've already created a code of this problem in C++ and created a PR. Can you try using some other language?

**Comment by eishagoel15** [comment]
I am a Gssoc participant and I can contribute to this issue by writing the code for this problem in python. So plz assign this issue to me.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by aanchalsethi** [comment]
yes, i can code it java as well.

**Comment by iaditichine** [comment]
@rudrakshi99 , I want to solve my issue using C++.Please assign it to me.

**Comment by beenusingh** [comment]
Hey, I’m a GSSOC'21 participant.I'd like to provide an understandable code with proper comments for this issue in Java.
Please assign this issue to me.

**Comment by OjusWiZard** [comment]
Counting sort already exists in the repo.
Raise a separate issue if you want to add the Counting sort in python because we still don't have any request for Python.
