### ISSUE TITLE
Job scheduling using greedy approach (c++,java,python)

### ISSUE THREAD

**Issue by deepika9560** [Algo-Phantoms/Algo-Tree#721]
Hey !! I am GSSOC'21 participant.I will provide the solution in all three languages .Please assign this issue to me.
@tarun26091999 @anubhavitis @dheerajkotwani @avijit1999 @todi-2000

**Comment by vedant-jain03** [comment]
Hello mentors.
I can do this issue in C++ and python

**Comment by tarun26091999** [comment]
present at #151
