### ISSUE TITLE
Prime factorization using Sieve of Eratosthenes

### ISSUE THREAD

**Issue by aanchalsethi** [Algo-Phantoms/Algo-Tree#723]
Wap to find the prime factors of a given no. using the sieve of Eratosthenes.
Test Case-
input=12246
output-2 3 13 157

I am gssoc'21 participant. Please allow me to work on this issue.

**Comment by kirtijha014** [comment]
Hello Maintainers
I  can work on this issue and provide the required algorithm in C++ as well as Java. I will work with Time Complexity O(log n) and Space Complexity O(n).
Please allow me to work on this issue. I am GSSoc'21 participant.

**Comment by shreyanspoddar** [comment]
This issue has been already assigned before refer #47
