### ISSUE TITLE
I want to add these sorting algo in C++, Java and python

### ISSUE THREAD

**Issue by nabin-nath** [Algo-Phantoms/Algo-Tree#730]
1. Bubble sort
2. Bucket sort
3. Radix sort

**Comment by nabin-nath** [comment]
I am a GSSOC participant and would like to add these algorithms

**Comment by aadya7104** [comment]
Hello, I am  GSSOC 21 participant. Please assign the sorting to me for Java. Thank you.

**Comment by Mugdha-Hazra** [comment]
Hello @tarun26091999 @dheerajkotwani @esheetaparulekar @anubhavitis @jeelnathani, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me under GSSOC'21?

**Comment by shreyanspoddar** [comment]
All the sorting algorithms are being worked on in the issue no #124 . You can ask there if any algorithm is missing.
