### ISSUE TITLE
Add contributor section in  readme.md 

### ISSUE THREAD

**Issue by rohank2502** [Algo-Phantoms/Algo-Tree#731]
I will like to add the contributor section in read me so it will make this more attractive !!

**Comment by rohank2502** [comment]
@rudrakshi99  Please give  it a review can we do such  changes ?

**Comment by devanshi-code** [comment]
I want to work in this issue . Can you plz assign it to me

**Comment by OjusWiZard** [comment]
It'll be handled by the maintainers soon. Thanks for your concern though :D
