### ISSUE TITLE
All dynamic programming codes of (ADITYA VERMA) 

### ISSUE THREAD

**Issue by ASHISH-GITHUB2495** [Algo-Phantoms/Algo-Tree#738]
**I have coded all Dynamic Programing questions from Playlist of Aditya Verma...
Can you please assign it to me sir...**
****

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me

**Comment by OjusWiZard** [comment]
Raise separate issues for separate problems.
Also, make sure to add your original intuition to the problems.
