### ISSUE TITLE
Merge Two Sorted Arrays (Two Pointer Approach) Java

### ISSUE THREAD

**Issue by mohdarif8299** [Algo-Phantoms/Algo-Tree#740]
Merging Two Sorted Arrays using Two Pointers Approach in Java.
Total Time Complexity  O(sum of Arrays Length)
Space Complexity  O(Sum of Arrays Size)
I'm a GSSOC'21 Participant
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by Mugdha-Hazra** [comment]
Hello @tarun26091999 @dheerajkotwani @esheetaparulekar @anubhavitis @jeelnathani, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me under GSSOC'21?

**Comment by tarun26091999** [comment]
this is not the most efficient algorithm to merge two sorted arrays, as it can be done in constant extra space, which is present at #1088
