### ISSUE TITLE
Print all Unique Subset lexicographically using Recursion and Backtracking in Java

### ISSUE THREAD

**Issue by IShahnawazShaikh** [Algo-Phantoms/Algo-Tree#749]
Hey! @tarun26091999 sir I am GSSOC'21 Participant and I want to add this issue if you allow.
input : 1 2  2 3
Output :
{}
1
1 2
1 2 2
1 2 2 3
2 
2 2
2 2 3
2 3
3.

We will have all the unique subset in lexicographic order.

**Comment by tarun26091999** [comment]
@IShahnawazShaikh do not spam issues. You already raised this at #747

**Comment by IShahnawazShaikh** [comment]
@tarun26091999  sir Issue #747 is different from this one.

**Comment by tarun26091999** [comment]
https://github.com/Algo-Phantoms/Algo-Tree/issues/747#issuecomment-805916869
