### ISSUE TITLE
Most occurred element of an array

### ISSUE THREAD

**Issue by krishna-NIT** [Algo-Phantoms/Algo-Tree#755]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by sakshi012000** [comment]
Hi,
I am GSSOC'21 participant
please assign me this. I will do this in C++

**Comment by 04akvs** [comment]
Hi,
I am GSSOC'21 participant
I would implement this in C++, can I get assigned to this issue?
@rudrakshi99  @nakul-19  @plazzy99  please assign me this issue

**Comment by adityaiiitL** [comment]
Hi
I am GSSoC'21 participant, please assign this work to me. I code in C++
