### ISSUE TITLE
reversing letters of word in sentence where words sequence will remain same [STRING JAVA]

### ISSUE THREAD

**Issue by krishna-NIT** [Algo-Phantoms/Algo-Tree#756]
eg: 
INPUT :   hi i am krishna
Output : ih o ma anhsirk

In Algo-Tree/string/ 
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by tarun26091999** [comment]
present at #416
