### ISSUE TITLE
Trapping Rainwater 

### ISSUE THREAD

**Issue by Rishika30** [Algo-Phantoms/Algo-Tree#767]
I am a GSSOC'21 participant and i would like to add Trapping Rainwater problem's solution in C++. I will add the test cases and the time ,space complexity of this as well.Please assign this issue to me.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me as I had recently solved the question with less time complexity

**Comment by tarun26091999** [comment]
present at #594
