### ISSUE TITLE
2D matrix search

### ISSUE THREAD

**Issue by aanchalsethi** [Algo-Phantoms/Algo-Tree#768]
To search an element in a user-defined matrix in which all the rows and columns are also sorted.

I will work on this issue as soon as I am assigned to it.

**Comment by Aarti002** [comment]
hey @rudrakshi99 @tarun26091999 can i do this in c++.
Thank you!

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by adityaiiitL** [comment]
Ma'am, I am a participant at GSSoC'21, Can u assign this work to me? as I can do this in very optimised way rather than the brute force approach. I code in C++.

**Comment by tarun26091999** [comment]
present at #385
