### ISSUE TITLE
Maximum Absolute Difference

### ISSUE THREAD

**Issue by Chirag018** [Algo-Phantoms/Algo-Tree#776]
Hi, I am GSSoC participant,I would like to add this problem with Time and Space Complexity.

**Comment by Chirag018** [comment]
Hi, I am GSSoC participant,I would like to add this problem with Time and Space Complexity.

**Comment by Chirag018** [comment]
Hi, I am GSSoC participant,I would like to add this problem with Time and Space Complexity.

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by AdityaRaj-ar** [comment]
Hello everyone,
I am Aditya Raj, studying in IIT GUWAHATI and i request you to assign this issue to me. I will solve this in very systematic way and explanation of all necessary steps

Thank you.

**Comment by OjusWiZard** [comment]
Might reopen the issue after you describe the problem more briefly.
