### ISSUE TITLE
Find Duplicate in Array

### ISSUE THREAD

**Issue by Chirag018** [Algo-Phantoms/Algo-Tree#777]
Hi, I am GSSoC participant,I would like to add this problem with Time and Space Complexity.

**Comment by prajakta2809** [comment]
i would like to work on this as GSSOC participant.

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue in java as a GSSoC 2021 participant
kindly assign me the issue

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by eishagoel15** [comment]
Hey there, I am a Gssoc'21 participant and I would love to contribute to this issue.

**Comment by shahina-bano** [comment]
Please assign this issue, I will solve this using CPP.

**Comment by yashmita** [comment]
I can solve this problem using Python. Kindly assign me this issue.

**Comment by OjusWiZard** [comment]
@Chirag018 always mention the language that you want to use.

**Comment by Srishti013** [comment]
Hello,
I would like to contribute to this issue in C++ as a GSSoC 2021 participant
kindly assign me the issue if it is not solved already

**Comment by krishna-NIT** [comment]
@OjusWiZard Since Mar 12, we don't have PR for JAVA so, Can I Do it? @tarun26091999 @plazzy99 @rudrakshi99

**Comment by Palakgupta0908** [comment]
I would like to contribute to the above code in java . Kindly assign this to me. Thanks.
