### ISSUE TITLE
Median of two sorted arrays of different size

### ISSUE THREAD

**Issue by Chirag018** [Algo-Phantoms/Algo-Tree#778]
Hi, I am GSSoC participant,I would like to add this problem with Time and Space Complexity.

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue in java as a GSSoC 2021 participant
kindly assign me the issue

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by tarun26091999** [comment]
present at #631
