### ISSUE TITLE
Median of two sorted arrays of equal size

### ISSUE THREAD

**Issue by Chirag018** [Algo-Phantoms/Algo-Tree#779]
Hi, I am GSSoC participant,I would like to add this problem with Time and Space Complexity.

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue in java as a GSSoC 2021 participant
kindly assign me the issue

**Comment by Prakash-poka** [comment]
Check pull request #788 [https://github.com/Algo-Phantoms/Algo-Tree/pull/788](url)

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by Aarti002** [comment]
hello @tarun26091999 @rudrakshi99 can i work on this issue in python
Thank u

**Comment by tarun26091999** [comment]
present at #631
