### ISSUE TITLE
Adding more DS codes and algorithms in Python.

### ISSUE THREAD

**Issue by noviicee** [Algo-Phantoms/Algo-Tree#78]
I see that currently this project has no codes corresponding the Python programming language.
I have good knowledge of Python  programming language as well as fair knowledge of  DS in Python.
I can easily code for Arrays, Stacks, Queues, Linked-List as well as Trees in Python.
I am trying to learn more as well.
Will be glad to make some decent code contributions for all those topics on DSA in python to make this project really awesome.
You can assign any or all of these to me.
I am currently a participant of GSSOC'21
Will be waiting for a response to go ahead :)

**Comment by RhuthuHegde** [comment]
Can I work on this issue, under gssoc'21?

**Comment by tarun26091999** [comment]
@noviicee you cannot solve more than 1 question in a single issue. Raise separate issue for every question.

**Comment by noviicee** [comment]
Okay
