### ISSUE TITLE
Add Array Operations

### ISSUE THREAD

**Issue by jahnavi0105** [Algo-Phantoms/Algo-Tree#79]
Hi
I find that array operations are not implemented. I have a piece of good knowledge on dsa. I can easily implement array operation(Insertion at the middle, Insertion at the end, Deletion at the beginning, Deletion at the middle, Deletion at the end) in c++. I would be happy to make my pull request for this. 
I am currently a GSSOC'21 Participant.
Will you please assign these to me.

**Comment by sunidhi1999-c** [comment]
I have been selected for GSSOC'21, and I am really interested in Algorithms , so I would like to contribute in this amazing repository.I can contribute for this ,I am 2 star codechef candidate and would be great to contribute to open source programs like this one. I can write these articles if given a chance.
Thanks.
Sunidhi,
3rd year,CSE at NMAMIT,Nitte,Karnatak

**Comment by minig-tech** [comment]
I would like to work on this issue. Will you please assign it to me.

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by ahmed-shameem** [comment]
Hi,
Please assign this task to me. I am a GSSoC'21 participant. I can solve the problem using c++.

**Comment by yogitasaini** [comment]
please assign this task to me in java under gssoc'21

**Comment by anubhab-code** [comment]
I am a GSSoC'21 participant.
I can contribute to this issue in Python3 language.
If this hasn't been assigned to anyone with Python3 language, I would love to work on it.

**Comment by Tanya933** [comment]
I would like to work on this issue in c++ as a GSSoC'21 participant. Please assign this issue to me.
