### ISSUE TITLE
Count Sort

### ISSUE THREAD

**Issue by aanchalsethi** [Algo-Phantoms/Algo-Tree#790]
I can write the algorithm for the count sort in CPP.

**Comment by abhay27chauhan** [comment]
I can write the algorithm for the count sort in Java

**Comment by priyanka001tech** [comment]
I can write the algorithm for the count sort in CPP. Please assign this to me.

**Comment by OjusWiZard** [comment]
Duplicate of #398 and C++ code already exist in the repository.
