### ISSUE TITLE
Implementing Interpolation search

### ISSUE THREAD

**Issue by XZANATOL** [Algo-Phantoms/Algo-Tree#794]
Interpolation search algorithm is not included in the "Searching_Sorting" section, tho it is mentioned. I would like to add the algorithm under the mentorship of GSSOC'21 with the following details:

# Details
* Explaining what is Interpolation search.
* When should it be applied.
* Mention its time complexity.
* Allow the user to enter his own custom inputs.
* Commenting the code so it is easy to read and follow the flow of the algorithm.

# Skill set
- [x] Python
- [x] C++

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me

**Comment by XZANATOL** [comment]
@tarun26091999 any updates on assigning this issue?

**Comment by ShubhamGupta577** [comment]
@OjusWiZard, Under GSSOC21 I want to work on this issue using C++ or Python. Please assign me this issue.

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.
