### ISSUE TITLE
Fibonacci Series in python

### ISSUE THREAD

**Issue by Prakash-poka** [Algo-Phantoms/Algo-Tree#795]
There should be a Fibonacci series in every data structure algorithm repository.

**Comment by Harikrishnaa3131** [comment]
Kindly assign this issue to me .I am a gssoc'21 participant

**Comment by eishagoel15** [comment]
Hey there, I think I can solve this issue, I will write this code in python and I will complete this code in max one hour after it is assigned to me. So please assign this issue to me.

**Comment by yogitasaini** [comment]
please assign this issue tome in java under GSSOC'21

**Comment by tarun26091999** [comment]
present at #635
