### ISSUE TITLE
Find Loop in a Linked List.

### ISSUE THREAD

**Issue by Ayush12062000** [Algo-Phantoms/Algo-Tree#798]
Hello, I think this is an important question and this should definitely be added in the Algo-Tree and I will start working on it as soon as I get assigned!! as I am a part of GSSoC'21, so I would like to implement this in c++.

Kindly assign this issue to me!
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by shreya-dotcom** [comment]
Hey ,I am a part of GSSoC'21,  I would like to implement this problem in java. Kindly assign this issue to me.
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by tarun26091999** [comment]
present at #189
