### ISSUE TITLE
Fibonacci Series using recursion

### ISSUE THREAD

**Issue by Prakash-poka** [Algo-Phantoms/Algo-Tree#800]
Recursion is a very important concept. Let's do the Fibonacci series using recursion.

**Comment by AdityaRaj-ar** [comment]
I request you to assign this issue to me. I will solve this issue in a very **systematic** way along with **all the explanation of the necessary steps.**

Thank you.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this work to me.

**Comment by ShreyaTarwey** [comment]
Hello, Could you please assign this issue to me under GSSOC'21.

**Comment by priyanka001tech** [comment]
I would like to solve the problem as a participant of GSSoC'21 please assign this issue to me.

**Comment by tarun26091999** [comment]
present at #635
