### ISSUE TITLE
GSSOC'21 : Deletion from Linked List

### ISSUE THREAD

**Issue by TawfikYasser** [Algo-Phantoms/Algo-Tree#805]
Hi @tarun26091999 
I want to add the following 3 methods to linked list in c++
- [ ] Delete from beginning
- [ ] Delete from end
- [ ] Delete from specific position

I am in GSSOC'21 program

Thanks

**Comment by rk05-lenavo** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by Upasana1216** [comment]
I want to contribute to this in c++ with easy explanation, time complexity and edge cases. Please assign this to me

**Comment by khusheekapoor** [comment]
Hello! I am a participant in GSSoC'21. I am really intrigued by this issue. Would be highly obliged if you could assign this to me. I will be using Java. Thanks!

**Comment by ayush78781** [comment]
Hey! @OjusWiZard I would like to work over this issue in C++. Please assign it to me.
