### ISSUE TITLE
Implement Stack Class in Python 

### ISSUE THREAD

**Issue by sujoy-coder** [Algo-Phantoms/Algo-Tree#809]
Hello, I'm a GSSoC '21 participant. I would like to work on the **implementation of Stack Class in Python** .
I have read the contribution guidelines as well I request you to kindly assign this issue to me. 

@plazzy99 @nakul-19  @todi-2000 @rudrakshi99

**Comment by Simar05519** [comment]
I had an experience as I had worked on projects. I want to work on this issue. Please assign to me.

**Comment by OjusWiZard** [comment]
Duplicate of #516

**Comment by sujoy-coder** [comment]
Thank You for your response 😑
