### ISSUE TITLE
[GSSOC'21] Inverse of 2-D Array in C++ language

### ISSUE THREAD

**Issue by Aarushi3113** [Algo-Phantoms/Algo-Tree#815]
Let A be a 2-D Array.
Then,

         **A^(-1) = (1 / (det(A)) * adj(A)**    where, A^(-1) is the inverse of A

Inverse is used to find solution to a system of linear equations.

I would like to add the code for this problem in _C++ language_.
I will write clean code with proper documentations and will follow the code of conduct.

Kindly assign this issue to me under GSSOC'21 label.

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by Aarushi3113** [comment]
Kindly assign this issue to me.

**Comment by madhvi02** [comment]
@tarun26091999  Sir 
Please Assign this to me.I would like to code this in C++. I m a GSSOC'21 Partcipant .I will assure you that I will provide a commented code with efficient time complexity.
Regards 
Madhvi .

**Comment by khusheekapoor** [comment]
Hello! I am a participant in GSSoC'21. I am really intrigued by this issue. Would be highly obliged if you could assign this to me. I will be using Java. Thanks!

**Comment by OjusWiZard** [comment]
@krishna-NIT Mention me on issue #727 for java

**Comment by OjusWiZard** [comment]
Duplicate of #727
