### ISSUE TITLE
Floyds triangle 

### ISSUE THREAD

**Issue by soukarsha122** [Algo-Phantoms/Algo-Tree#823]
Hello @nakul-19 @plazzy99 @rudrakshi99 I want to implement a code in C++ that prints the Floyd's triangle upto n rows.

My code will have proper test cases and comments to make it understandable. I will be very happy if you assign me this issue.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by OjusWiZard** [comment]
This is not a DSA problem, rather an implementation based problem.
