### ISSUE TITLE
find the  total number of odd and  even numbers present in a LINKED LIST.

### ISSUE THREAD

**Issue by Roshni1809** [Algo-Phantoms/Algo-Tree#825]
The code will find out the total number of odd and even numbers present in a linked list.
I will be implementing this problem in CPP.
Kindly assign me this issue @tarun26091999 .

**Comment by 04akvs** [comment]
The code will find out the total number of odd and even numbers present in a linked list.
I will be implementing this problem in CPP.
Can this be assigned to me?

**Comment by SwarnimaShishodia** [comment]
Hi, I can solve this problem using C++. Please assign this issue to me.

**Comment by tarun26091999** [comment]
this is simply traversal of a linked list and that is already present. We accept the standard algorithms only.
