### ISSUE TITLE
Spiral Print of Matrix

### ISSUE THREAD

**Issue by sujal111** [Algo-Phantoms/Algo-Tree#83]

**Comment by maanpatel2492** [comment]
I would like to solve #83 today.
(under GSSOC21)

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by rudrakshi99** [comment]
@sujal111 mention the language in which you want to code.

**Comment by ahmed-shameem** [comment]
Hi,
Please assign this task to me. I am a GSSoC'21 participant. I can solve the problem using c++.

**Comment by sujal111** [comment]
I want to solve it in Python

**Comment by Meghna180401** [comment]
I would like to provide a JAVA solution for issue #83 as a part of GSSOC'21.

**Comment by DEEPIKA-SUK** [comment]
I am a participant of GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021. I would like to provide solution in c++.
Thank you.

**Comment by DEEPALI-SUK** [comment]
I want to work on this issue and want to contribute to this. I am a participant of GSSOC 2021. Please could you assign me this issue as a part of GSSOC 2021. I will implement in C++.
Thank you.

**Comment by Vansh-Gupta4** [comment]
i like to contribute to this project ...my code will be in java with proper comments and test cases

**Comment by kshittijagrawal** [comment]
Hey there!
I'd like to contribute to the project. I want to address and fix this issue. My implementation will be in python with a clean code and documentation. Kindly provide me with this issue.
I'm also a GSSOC'21 participant.

**Comment by himali08** [comment]
hey I am a GSSOC 21 participant and I am looking forward to work on this in C and C ++language

**Comment by neha030** [comment]
I am GSSOC'21 participant , I want to work on the in C++ code.
I have good understanding about C and C++ language..so I request , to please assign me the work.
The code will be properly indented with proper comments and description.

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.


@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99
