### ISSUE TITLE
Infix to postfix  conversion

### ISSUE THREAD

**Issue by vabhv1903** [Algo-Phantoms/Algo-Tree#835]
Hey, I am Vabhv1903 a GSSOC'21 Participant. I am having experience in C++ Coding as well as I am doing Competitive coding in the C++ programming language.

Please assign this task to me :)
Thank-you.
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by SwarnimaShishodia** [comment]
Hi, I would like to solve this problem using C++. Please assign this issue to me.

**Comment by Riya1718** [comment]
Hey, I am Riya Jain, a GSSOC,21 Participant. I would like to solve this problem using Java. Please assign this issue to me.
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by shreya-shah-28** [comment]
i want to work on this issue please assign this to me

**Comment by raksha009** [comment]
Present at #511
