### ISSUE TITLE
weird algorithm 

### ISSUE THREAD

**Issue by vabhv1903** [Algo-Phantoms/Algo-Tree#836]
in this problem there is an algorithm that takes as input a positive integer n. If n is even, the algorithm divides it by two, and if n is odd, the algorithm multiplies it by three and adds one. The algorithm repeats this, until n is one.

Hey, I am Vabhv1903 a GSSOC'21 Participant. I am having experience in C++ Coding as well as I am doing Competitive coding in the C++ programming language.

Please assign this task to me :)
Thank-you.
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by tarun26091999** [comment]
We do not accept the problems available on competitive sites. We only accept standard algorithms and questions.

https://www.codechef.com/problems/WALG
