### ISSUE TITLE
Transpose of a Matrix in C++

### ISSUE THREAD

**Issue by sujal111** [Algo-Phantoms/Algo-Tree#84]

**Comment by sujal111** [comment]
Allow me to work on this issue

**Comment by sunidhi1999-c** [comment]
I have been selected for GSSOC'21, and I am really interested in Algorithms , so I would like to contribute in this amazing repository.I can contribute for this ,I am 2 star codechef candidate and would be great to contribute to open source programs like this one. I can write these articles if given a chance.
Thanks.
Sunidhi,
3rd year,CSE at NMAMIT,Nitte,Karnatak

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by AkanshaUniyal** [comment]
Hello! I want to write this algorithm in JAVA under GSSOC'21

**Comment by sakshi2707** [comment]
Hello, I am from GSSoC 2021, I would like to contribute to this issue. Could you assign me this? I will implement it in C++

**Comment by adityaiiitL** [comment]
Hello, I am a GSSoC'21 participant, please assign this work to me

**Comment by yashmita** [comment]
I would like to work on this issue in Python. Kindly assign it to me @plazzy99.
