### ISSUE TITLE
Java program for Perfect number

### ISSUE THREAD

**Issue by IdealisticINTJ** [Algo-Phantoms/Algo-Tree#843]

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 please assign me this issue

**Comment by OjusWiZard** [comment]
Duplicate of #753
