### ISSUE TITLE
Binary tree level order traversal in spiral form 

### ISSUE THREAD

**Issue by tk315** [Algo-Phantoms/Algo-Tree#853]
Would like to add an algorithm for printing level order traversal of tree in spiral form in C++. 
Please assign this to me under gssoc2021.

**Comment by kshithih** [comment]
hello GSSOC'21
I would like to implement this issue in C

**Comment by codeakki** [comment]
### HEY I Would like to Add an Algorithm
Under Gssoc'21 i Will implement printing level order traversal of tree in Spiral Form in java and C++.
Please assign this issue to me.

**Comment by Masters-Akt** [comment]
I would like to implement it in python. Please assign it to me.

**Comment by khushboojoshi3** [comment]
I would like to implement this issue in C++, please assign it to me.

**Comment by Deepaliiii** [comment]
I would like to implement this issue in C++, please assign it to me.
