### ISSUE TITLE
Add Matrix Multiplication

### ISSUE THREAD

**Issue by jahnavi0105** [Algo-Phantoms/Algo-Tree#86]
Hi pls assign this to me. I  would be happy to make a pull request on this .I  would like to implement in cpp.

**Comment by sunidhi1999-c** [comment]
I have been selected for GSSOC'21, and I am really interested in Algorithms , so I would like to contribute in this amazing repository.I can contribute for this ,I am 2 star codechef candidate and would be great to contribute to open source programs like this one. I can write these articles if given a chance.
Thanks.
Sunidhi,
3rd year,CSE at NMAMIT,Nitte,Karnatak

**Comment by maanpatel2492** [comment]
I would like to solve this issue today.
(under GSSOC21)

**Comment by rudrakshi99** [comment]
@jahnavi0105 mentions the language also.

**Comment by pri1311** [comment]
Would like to add Strassen's multiplication in c++

**Comment by nikitajuneja1** [comment]
I would love to contribute to solving the problem, I am a GSSOC'21 participant. Please assign it to me. I will try my best and provide proper comments and implement different test cases for better understanding.

**Comment by iamvs-2002** [comment]
Kindly allow me to implement the same in Java.

**Comment by kshittijagrawal** [comment]
Hey there!
I'd like to contribute to the project. I want to address and fix this issue. My implementation will be in python with a clean code and documentation. Kindly provide me with this issue.
I'm also a GSSOC'21 participant.

**Comment by kishanks412** [comment]
Hello, I'm Kishan Kumar Seth participating in GSSOC'21. I would like to contribute in this project. Please assign me this issue.

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Add Matrix Multiplication using C/C++ , JAVA 
i will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.

so i would like @rudrakshi99 , @plazzy99  , @nakul-19  to please assign this Issue to me :)

**Comment by Tanya933** [comment]
I would like to work on this issue in c++ as a GSSoC'21 participant. Please assign this issue to me.

**Comment by cintamg** [comment]
I am a participant in GSSOC'21. I would like to contribute to this issue in c++, can you please assign this issue to me.

**Comment by ayush78781** [comment]
Hello Maintainers of the Project! @tarun26091999 Sir, @rudrakshi99 Mam, I am GSSoC'21 participant I would like to work over this issue in C , C++ or Python, please assign it to me. so that I could resolve it  as early as possible.
