### ISSUE TITLE
Vaccum Cleaner Route

### ISSUE THREAD

**Issue by Vanshikaa00** [Algo-Phantoms/Algo-Tree#867]
Given a string representing the sequence of moves a robot vacuum makes, return whether or not it will return to its original position. The string will only contain L, R, U, and D characters, representing left, right, up, and down respectively.
Ex: Given the following strings...
"LR", return true "URURD", return false "RUULLDRD", return true

I would like to work upon this problem. Can you assign it to me under GSSOC'21?

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me

**Comment by OjusWiZard** [comment]
Always mention the language
