### ISSUE TITLE
Fibonacci series using recursion 👨‍💻

### ISSUE THREAD

**Issue by Aj7t** [Algo-Phantoms/Algo-Tree#868]
hi, I am a Gssoc'21 participant I have created this issue and  I want to work on the "Fibonacci series using recursion " in python.
could you please assign me .

@tarun26091999 @shreyanspoddar @nakul-19 @rudrakshi99 @raksha009

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign me.

**Comment by RiyaVashishtha** [comment]
Hello, @rudrakshi99 
I am a GSSOC'21 participant and would like to contribute to this issue " Fibonacci series using recursion" in Python.
I will make sure that the code is readable and understandable by the beginner by using proper comments.
Please, assign this issue to me.

**Comment by tarun26091999** [comment]
present at #635
