### ISSUE TITLE
Add String Searching Algorithms

### ISSUE THREAD

**Issue by jahnavi0105** [Algo-Phantoms/Algo-Tree#87]
Hi
I see that string searching algorithms(Brute-Force algorithm, Knuth-Morris-Pratt algorithm, Boyer-Moore algorithm, Robin-Karp algorithm)  are not been implemented. I have good knowledge of them. I would like to implement them in c++. I am a participant in GSSOC'21. I would be happy to make a pull request on this. Will you pls assign this to me.

**Comment by maanpatel2492** [comment]
I would like to solve this issue today.
(under GSSOC21)

**Comment by minig-tech** [comment]
I would like to work on this issue. Will you please assign it to me. I am a participant in GSSOC'21.

**Comment by krishna-NIT** [comment]
I am a GSSOC '21 participant.

I wish to contribute a JAVA code for this issue:

My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by Amit366** [comment]
Can I implement this issue using Java? I am a GSSOC participant.

**Comment by tarun26091999** [comment]
you cannot ask to solve more than 1 question in a single issue.
