### ISSUE TITLE
ADDING PATTERN PROBLEMS

### ISSUE THREAD

**Issue by vishakha-aggarwal** [Algo-Phantoms/Algo-Tree#871]
### **EXPLANATION:**

OUR TASK IS TO PRINT THE PATTERNS THE FOLLOWING PATTERNS BY IMPLEMENTING LOOPS ::
1. FLOYD'S TRIANGLE
2. HOLLOW BUTTERFLY
3. SOLID BUTTERFLY
4. HOLLOW RECTANGLE
5. HOLLOW PARALLELOGRAM
6. SOLID PARALLELOGRAM
7. HOLLOW DIAMOND
8. SOLID DIAMOND
9. PASCAL TRIANGLE
10. PALINDROME PATTERN

Hey, @rudrakshi99  , I want to add these pattern problems in C++ language in `Algo-Tree/Code/C++` .

**Comment by vishakha-aggarwal** [comment]
Hey , I have created this issue. I want to work on this under GSSOC'21. Please assign it to me. 
I have read all the contributing guidlines.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by Sweeti-Gupta** [comment]
I also want to work on this issue. Please assign it to me.

**Comment by Simar05519** [comment]
Thank you for assigning

**Comment by drishika2002** [comment]
Hello, I want to code this issue in C language under GSSOC'21. 
Please assign this issue to me.

**Comment by Sweeti-Gupta** [comment]
Hey @rudrakshi99 ,I want to add these pattern problems in java language in Algo-Tree/Code/Java.

I want to contribute to this as a part of GSSOC. Please assign this issue to me.

**Comment by OjusWiZard** [comment]
Raise separate issues
