### ISSUE TITLE
Find factorial of a large number in cpp

### ISSUE THREAD

**Issue by prityusha** [Algo-Phantoms/Algo-Tree#872]
[GSSoC'21][CPP]Given a big integer like 100 or 1000 it's factorial will be very large and cannot be stored in any of the data types in c++, Create an algorithm to implement it.

hey @tarun26091999  @dheerajkotwani @tarun26091999 @rudrakshi99  am GSSoC'21 participant and doing competitive programming and I can solve this probem in cpp, kindly please assign this issue to me.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by Tj8864** [comment]
I want to work on this issue in C++, please assign this to me under GSSoC'21

**Comment by shahina-bano** [comment]
Please assign this me issue, I will solve this problem using JAVA.

**Comment by tarun26091999** [comment]
#362
