### ISSUE TITLE
Linked_list : All operation in linked_list using java

### ISSUE THREAD

**Issue by ashutosh-cusat** [Algo-Phantoms/Algo-Tree#874]
**Explanation**

A list of data given. print the data based on which operation whatever you select like 1:insert_first 2:delete 3:traversal 4:insert_after 5:DELETE-KEY 6:insert_last 7:delete_last.

hey @tarun26091999 @rudrakshi99 I want to add this important question in the "Algo-Tree/Code/Java/".

**Comment by tarun26091999** [comment]
all these issue are assigned already.
