### ISSUE TITLE
[Binary Search][CPP]Allocate minimum number of pages (in CPP)

### ISSUE THREAD

**Issue by prityusha** [Algo-Phantoms/Algo-Tree#876]
Given number of pages in n different books and m students. The books are arranged in ascending order of number of pages. Every student is assigned to read some consecutive books. The task is to assign books in such a way that the maximum number of pages assigned to a student is minimum.

array[] = [10,20,30,40]
m = 2

hey @tarun26091999  @dheerajkotwani @tarun26091999 @rudrakshi99I am GSSoC'21 participant and doing competitive programming and I can solve this probem in cpp, kindly please assign this issue to me.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by tarun26091999** [comment]
@rudrakshi99 see this

**Comment by prityusha** [comment]
@tarun26091999 @rudrakshi99  please assign this issue to me I am a participant in GSSOC'21 and would like to solve this issue in cpp.

**Comment by OjusWiZard** [comment]
Duplicate of #665
