### ISSUE TITLE
Add BST Traversals

### ISSUE THREAD

**Issue by jahnavi0105** [Algo-Phantoms/Algo-Tree#88]
Hi
I see that Binary search tree traversals(Inorder, Preorder, Postorder) are not implemented. I can implement them in c++. I am a participant in GSSOC'21. I would be happy to make a PR on this. Will you pls assign this to me.

**Comment by kanak22** [comment]
I can implement them in c. I am a participant in GSSOC'21. Kindly assign it to me.

**Comment by ahmed-shameem** [comment]
Hi,
Please assign this task to me. I am a GSSoC'21 participant. I can solve the problem using c++. I will be adding BFS and DFS (Preorder, Inorder and Postorder) traversals using iterative as well as recursive way.

**Comment by ireneelizabethsabu** [comment]
Hi,
I am a GSSoC'21 participant. I would like to contribute the recursive and iterative (Preorder,Postorder,Inorder) tree traversals in Java.Kindly assign this to me.

**Comment by hritikkhurana10sm** [comment]
Hi,
I would like to work on this issue in C++. Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!
