### ISSUE TITLE
N-queen problem using backtracking using C++

### ISSUE THREAD

**Issue by gupta31** [Algo-Phantoms/Algo-Tree#883]

**Comment by Tj8864** [comment]
Please assign this to me under GSSoC'21

**Comment by gupta31** [comment]
I want to work on my own raised issue under GSSOC21.Please assign to me

**Comment by reerajput930** [comment]
Hello, I would like to contribute to this project in c++ language with help of backtracking.
->in O(n!) time complexity
->in O(n) space complexity
I am a GSsoc'21 participant.
waiting for a positive response.

**Comment by tarun26091999** [comment]
present at #381
