### ISSUE TITLE
Stack operations 

### ISSUE THREAD

**Issue by mehak2323** [Algo-Phantoms/Algo-Tree#89]
I would like to work on the stack operations mentioned below in C++.
1. count(): It returns the total number of elements available in a stack.
2. change(): It changes the element at the given position.
3. display(): It prints all the elements available in the stack.
I'm a participant of GSSOC 21, and would like to be assigned this issue :)

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by Avnish5** [comment]
Kindly assign this task to me.
I am selected as a participant in GSSOC 2021.
I can the code and function which you mentioned in c++.

**Comment by ahmed-shameem** [comment]
Hi,
Please assign this task to me. I am a GSSoC'21 participant. I can solve the problem using c++.

**Comment by harshbhalala-04** [comment]
I would like to work on this issue using c++, I am a GSSOC'21 participant. Please assign me this issue.

**Comment by aish2002** [comment]
I am a GSSOC'21 participant. I can implement the count() and display() operations on stack in java

**Comment by rahulsrivastava1** [comment]
Hey @rudrakshi99 @plazzy99 @nakul-19 i want to work on this issue,i know this concept, i am able to do this.
kindly assign me to this.
