### ISSUE TITLE
Sorting algorithms in C++

### ISSUE THREAD

**Issue by neha07kumari** [Algo-Phantoms/Algo-Tree#895]
### Feature
Solutions of all sorting algorithms

### Have you read the Contributing Guidelines on Pull Requests?
Yes

### Motivation
I want to contribute to it under GSSoC'21.

### Pitch:
I would like to take up this task to implement it in C++. @rudrakshi99

**Comment by yogitasaini** [comment]
please assign this task to me in java under GSSOC'21

**Comment by samar08** [comment]
I would like to implement the sorting algorithms in python. Please assign this issue to me.

**Comment by HitainKakkar** [comment]
I would like to contribute the code for Merge Sort in Linked List.
The code is ready.
Kindly assign it to me.

**Comment by samya02** [comment]
I would like to contribute as a GSSOC'21 participant using python.
Kindly assign this task to me.
Thanks!

**Comment by madhvi02** [comment]
@tarun26091999 
Please Assign this to me.I would like to code this in C++. I m a GSSOC'21 Partcipant .I will assure you that I will provide a commented code with efficient time complexity.
Regards 
Madhvi .

**Comment by raksha009** [comment]
Issue for all sorting algorithms present at #124
