### ISSUE TITLE
Diameter of a Binary Tree in Java

### ISSUE THREAD

**Issue by siddharth-bhatnagar** [Algo-Phantoms/Algo-Tree#903]
I'd like to create a java program which prints the diameter of a binary tree the console. Diameter is defined as the distance between two farthest nodes in the given binary tree. Please assign this issue to me. I'm a GSSOC'21 participant. @anubhavitis

**Comment by machine-sg** [comment]
Hi @anubhavitis  , I am GSSoC'21 participant and I want to do it in C++. Please assign me this.

**Comment by raksha009** [comment]
Issue exists at #291
