### ISSUE TITLE
Kth smallest element in Matrix

### ISSUE THREAD

**Issue by CSAURABH** [Algo-Phantoms/Algo-Tree#910]
Find the kth smallest element in the matrix.
Example 1 :-
Input:
N = 4
mat[][] =     {{16, 28, 60, 64},
                   {22, 41, 63, 91},
                   {27, 50, 87, 93},
                   {36, 78, 87, 94 }}
K = 3
Output: 27

Example 2 :-
Input:
N = 4
mat[][] =     {{10, 20, 30, 40}
                   {15, 25, 35, 45}
                   {24, 29, 37, 48}
                   {32, 33, 39, 50}}
K = 7
Output: 30

@rudrakshi99 @nakul-19 I would like to solve this issue in C++. Please assign this to me under GSSOC'21.

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue in java as a GSSoC 2021 participant
kindly assign me the issue

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 @tarun26091999  please assign me this issue
