### ISSUE TITLE
Find common elements in rows of a matrix

### ISSUE THREAD

**Issue by CSAURABH** [Algo-Phantoms/Algo-Tree#911]
Given an m x n matrix, find all common elements present in all rows of a matrix.
Example :-
Input:
mat[4][5] = {{1, 2, 1, 4, 8},
             {3, 7, 8, 5, 1},
             {8, 7, 7, 3, 1},
             {8, 1, 2, 7, 9},
            };
Output: 8 1

@rudrakshi99 @nakul-19 I would like to solve this issue in C++. Please assign this to me under GSSOC'21.

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue in java as a GSSoC 2021 participant
kindly assign me the issue

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 @tarun26091999  please assign me this issue

**Comment by CSAURABH** [comment]
@yasharth291 sir Please assign this issue to me
