### ISSUE TITLE
Longest Prefix Suffix Problem #499

### ISSUE THREAD

**Issue by Sanjsarma** [Algo-Phantoms/Algo-Tree#912]
Hello, I am Sanjana S, a participant of GSSOC'21 and would like to contribute the solution to the longest prefix suffix problem in Python.
Kindly assign this issue to me.
Thank you.
@tarun26091999

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue in java as a GSSoC 2021 participant
kindly assign me the issue

**Comment by tarun26091999** [comment]
present at #499
