### ISSUE TITLE
Middle element in a linked list 

### ISSUE THREAD

**Issue by tk315** [Algo-Phantoms/Algo-Tree#915]
Would like to add an algorithm for finding middle element in linked list in C++.
Please assign this to me under gssoc2021.

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Finding middle element in a linked list issue #915
i will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.

so i would like @anubhavitis , @dheerajkotwani , @tarun26091999 , @avijit1999 to please assign this Issue to me :)

**Comment by Aarti002** [comment]
hey @tarun26091999 @rudrakshi99 under gssoc'21 can i work on this issue in python
Thank you!

**Comment by adistar01** [comment]
Hi i am a participant of gssoc 21 and i want to contribute the code in java for this issue. Please assign this issue to me.

**Comment by jugalnagar** [comment]
@tarun26091999 
Can I work on this issue in java.
