### ISSUE TITLE
DP on Tree

### ISSUE THREAD

**Issue by machine-sg** [Algo-Phantoms/Algo-Tree#931]
Hi @anubhavitis @dheerajkotwani @tarun26091999 @avijit1999 @todi-2000 , I am GSSoC'21 participant and I want to add the concept of DP on Tree and I'll give examples with proper explanation. Please assign me this.

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for DP on Tree #931 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by tarun26091999** [comment]
you need to be specific about the problem you want to solve, there are many DP problems which include trees.
