### ISSUE TITLE
Adding code and file for Greedy algorithm 

### ISSUE THREAD

**Issue by DarthSalad** [Algo-Phantoms/Algo-Tree#936]
Hi, want to add file for an example of greedy algorithm(c++).
Please assign it to me.
This is regarding GSSOC 2021.

**Comment by Amanduttbhagat** [comment]
Hello,
I want to add an example of greedy algorithm in java as a GSSoC 2021 participant
kindly assign me the issue

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for greedy algorithm in C++/CPP.
The code is ready. I have added the code for merge sort in linked list , along with proper explanation of the algorithm of merge sort, test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for greedy algorithm in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
