### ISSUE TITLE
Infix to Postfix using Stack

### ISSUE THREAD

**Issue by pro-vider** [Algo-Phantoms/Algo-Tree#944]
Hey, I want to add the code of Infix to Postfix( C ).
please assign it to me.
This is regarding to GSSOC'21

**Comment by HitainKakkar** [comment]
I would like to contribute the code for Infix to Postfix in c++.
The code is ready.
Kindly assign it to me

**Comment by muthuannamalai12** [comment]
I would love to solve this is in python. Kindly assign it to me.

**Comment by ANSHIKA1806** [comment]
I'm a GSSOC'21 participant and I would like to work on this issue in C++.
I will write clean code and use proper comments.
Thank you.

**Comment by raksha009** [comment]
Present at #511
