### ISSUE TITLE
Routing for graphs(Minimum Spanning Tree,Shortest path problem)

### ISSUE THREAD

**Issue by Anupreetadas** [Algo-Phantoms/Algo-Tree#949]
Hi,
I am GSSOC'21 participant.
I would like to write the code for Kruskal's algorithm, Prim's algorithm for Minimum spanning tree and Bellman–Ford algorithm,Dijkstra's algorithm,Floyd–Warshall algorithm for Shortest path problem in c,c++.
Please assign it to me.

**Comment by tarun26091999** [comment]
you cannot solve multiple ques in same issue and all the issues has been assigned before.
