### ISSUE TITLE
Dutch National Flag Algorithm

### ISSUE THREAD

**Issue by HitainKakkar** [Algo-Phantoms/Algo-Tree#958]
Greetings sir/Mam,
I would like to contribute the code for this issue in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

**Comment by Shulabh-968026** [comment]
Dear sir/Mam,
I would like to contribute the code for this issue in Python.
I will added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

**Comment by Rajashri14** [comment]
Hello  admin , I would like to contribute for this issue in java.
I will do this as per your guidelines. Please assign this issue to me. 
This is regarding GSSOC'21.

**Comment by raksha009** [comment]
Plz try solving it in O(n) instead of O(2n).
