### ISSUE TITLE
Dfs and Bfs on 2d grid

### ISSUE THREAD

**Issue by janhavitripurwar** [Algo-Phantoms/Algo-Tree#96]
Hello,  @rudrakshi99 @nakul-19 @plazzy99 
I am GSSOC'21 participant. 

What I will include -: (suggest if something needs to be added)
1. dfs on 2d grid (theory ,example and code)
2. Find number of islands(dfs on 2d grid problem )
3. bfs on 2d grid(theory, example and code)
4. Min and max moves to reach target by knight(bfs on 2d grid problem)
5. language used for coding - cpp

**Comment by janhavitripurwar** [comment]
I will explain the question , approach, code, time complexity, space complexity, along with some images for clear understanding and examples for the theory.
The code will be quite simple to understand .
Also 3-4 test cases will be provided for each. 
Please assign this issue to me  @rudrakshi99

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you .
Thank you .
