### ISSUE TITLE
Greedy algorithm to find minimum number of coins

### ISSUE THREAD

**Issue by HitainKakkar** [Algo-Phantoms/Algo-Tree#965]
Greetings sir/Mam,
I would like to contribute the code for this issue in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 @tarun26091999  please assign me this issue

**Comment by rk05-lenavo** [comment]
I'm the Participant in GSSOC'21. Please assign me this issue. I'll use Python code .

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. Thanks!

**Comment by Shraddha13Jain** [comment]
I could do it using python/c++/java. Please assign it to me under gssoc'21

**Comment by sandipswain** [comment]
Hey @raksha009, I am a participant of GSSo'C. I would love to take up this issue and solve it using python. Please assign me this issue

**Comment by raksha009** [comment]
> Hey @raksha009, I am a participant of GSSo'C. I would love to take up this issue and solve it using python. Please assign me this issue

We allot issues on first come first basis. Plz look for other issues :)

**Comment by rk05-lenavo** [comment]
@raksha009  Sir I have created the pull request. Please check the code if it looks good please merge it sir.

**Comment by manasvvi1** [comment]
Hey!! I would like to work on the issue in cpp or c @raksha009
