### ISSUE TITLE
Detect a cycle in Linked List

### ISSUE THREAD

**Issue by HitainKakkar** [Algo-Phantoms/Algo-Tree#977]
Greetings sir/Mam,
I would like to contribute the code for this issue in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by krishna-NIT** [comment]
Hi,
I am GSSOC'21 participant

My code will be in JAVA with proper comments and test cases.
@rudrakshi99 @nakul-19 @plazzy99 @tarun26091999  please assign me this issue

**Comment by tarun26091999** [comment]
present at #189
