### ISSUE TITLE
Reversing a string using stacks

### ISSUE THREAD

**Issue by prateek-jpg** [Algo-Phantoms/Algo-Tree#98]
for example-prateek
output-keetarp

**Comment by prateek-jpg** [comment]
@rudrakshi99 I would like to solve this issue in JAVA. Please assign this to me under GSSOC'21.

**Comment by rohitsigar** [comment]
@rudrakshi99 I would love to work on this issue by writing good quality code in c++. please assign it to me

**Comment by rahulsrivastava1** [comment]
i can do this .
please assign this to me.

**Comment by jankivaghasiya** [comment]
Hello sir,
I am Janki Vaghasiya - a GSSOC'21 participant.
I would like to solve this issue using C++. I will try my best to comment code in the best way and use proper testcases

**Comment by rahulsrivastava1** [comment]
Thank you

**Comment by rahulsrivastava1** [comment]
Hey @raksha009, i just created pull request kindly check it out and do the needful.
Thankss!

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.
