### ISSUE TITLE
Display and Size of Linked List | Question

### ISSUE THREAD

**Issue by HitainKakkar** [Algo-Phantoms/Algo-Tree#988]
Greetings sir/Mam,
I would like to contribute the code for this issue in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by nikitajangid33** [comment]
Hello i am nikita jangid, i can contribute the code for this issue. 
Kindly assign this to me.

**Comment by Shulabh-968026** [comment]
Hello Sir/Maam
  I would like to resolve this issue in python and java. Please assign this issue to me.
