### ISSUE TITLE
Counting sort in java

### ISSUE THREAD

**Issue by prateek-jpg** [Algo-Phantoms/Algo-Tree#99]
Hi please assign me this task under GSSOC'21 and I would using counting sort for solving the issue which will also handle the elements that are repeated.

@rudrakshi99 I would like to solve this issue in JAVA. Please assign me this task.

**Comment by yogitasaini** [comment]
please , this task to me in java under gssoc'21

**Comment by Amanduttbhagat** [comment]
Hello,
Please assign me this issue, I would be using Radix Sort in Java

**Comment by Jagruthi13** [comment]
Hey @rudrakshi99
I am a GSSoC'21 participant. I would like to do this problem in cpp.
Can you assign me this issue

**Comment by rk05-lenavo** [comment]
I am a GSSoC'21 participant. I would like to do this problem in python.
Can you assign me this issue
